@startuml 131_p1ProvideCcIdentifiersForEthernetContainer
skinparam responseMessageBelowArrow true

title
p1ProvideCcIdentifiersForEthernetContainer
end title

participant "requestor" as requestor
participant "p1ProvideCcIdentifiersForEthernetContainer" as getIds #LightBlue

activate getIds


note over requestor
  Hand over a mountName and portId
  to lookup the associated ControlConstruct
  Ids (ltpUuid, lpLocalId) in
  LtpStructureAndAugment data
  
  Note: to find a match, the portId
  must exactly match the notations used for
  <i>original-ltp-names</i> in SDN.
end note
requestor -> getIds: {mountName, portId, ltpStructureAndAugment}

note over getIds
  Iterate over ltpStructureAndAugment to find the target
  LTP <i>ltp</i>:
  IF (<i>ltp</i>.ltpLayerProtocolName == ETHERNET_CONTAINER)
      AND (<i>ltp</i>.ltp-augment/original-ltp-name contains portId)
  THEN
    return <i>ltp</i>.uuid and <i>ltp</i>.localId
end note

getIds --> requestor: {mountName, uuid, localId}

deactivate getIds