@startuml onDemandUpdate
skinparam responseMessageBelowArrow true

title
  On demand update of the PM data
end title

participant "requestor\n" as tool
participant "initiatePmDataUpdate\n" as initUpdate #Cyan
participant "p1LoadParameters\n" as p1LoadParams
participant "p2StreamPmData\n" as p2StreamPm
participant "MWDI:\n/provideDeviceStatusMetadata" as mwdiMeta
participant "MWDI:\n/live/control-construct" as mwdiLive
database "Device" as device
database "MWDI ES" as cache
participant "p2ProcessDevice\n" as p2ProcessPm

activate p2StreamPm

tool -[#Cyan]> initUpdate : { [mountNames] }
activate initUpdate #Cyan

  initUpdate -> mwdiMeta : { [mountNames] }
  initUpdate <-- mwdiMeta : { [metaData] }

  note over device #White
    Leider wird lastCompleteControlConstructUpdateTimeAttempt
    nicht zum Zeitpunkt des Sendens an MWDI://live/control-construct
    aktualisiert, sondern erst beim Abschluss des Uploads/Timeouts.
    Darum kann nicht auf einen gegenwärtig laufenden CC Upload
    geschlossen werden
  end note

  note over initUpdate
    IF all [mountNames] in [metaData]
  end note
  note left initUpdate
    ELSE
    - sends error message
      "server responds, but service/resource doesn't exist"
      application: 533 (hidden server: 404)
    - terminates
  end note
  tool <-[#Cyan]- initUpdate : 533\n{ [missingMountNames] }
  note over initUpdate
    THEN
  end note
  note over device #White
    Soll neuen Zuschnitt des Simulationsgebietes ermöglichen
  end note

  note over initUpdate
    IF all [mountNames] in connected state
  end note
  note left initUpdate
    ELSE
    - sends error message
      "server does not respond, even on ping"
      application: 532 (hidden server: no response)
    - terminates
  end note
  tool <-[#Cyan]- initUpdate : 532\n{ [unconnectedMountNames] }
  note over initUpdate
    THEN
  end note
  note over device #White
    Soll neuen Zuschnitt des Simulationsgebietes ermöglichen
  end note

  note over initUpdate
    IF [lastControlConstructNotificationUpdateTime] elder than 15min
  end note
  note left initUpdate
    ELSE
    - sends warning message
    - removes up-to-date devices from [mountNames]
    - continues with reduced [mountNames]
  end note
  tool <-[#Cyan]- initUpdate : 200\n{ [alreadyUpToDateMountNames] }
  note over initUpdate
    THEN
  end note
  note over device #White
    Soll nur darüber informieren, dass für diese Geräte
    keine neuen Daten zu erwarten sind
  end note
  tool <-[#Cyan]- initUpdate : 204

  initUpdate -> p1LoadParams : {functionName=\n"initiatePmDataUpdate"}
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters
      from configFile
    end note
  initUpdate <-- p1LoadParams : { {parameters}\n{configFile} }
  deactivate p1LoadParams

  loop FOR all [mountNames]

    note over initUpdate
      sends requests at a configurable
      time interval (waitTimeForSending)
    end note

    initUpdate -> mwdiLive : { mountName }
    activate mwdiLive

deactivate initUpdate

      note right mwdiLive #LightGreen
        MWDI to be changed (MWDI issue 1566)
        in such a way that it refuses to forward
        duplicate requests (same path, same device)
      end note

      note over mwdiLive  #LightGreen
        IF CC upload already on-going
      end note

      note left mwdiLive #LightGreen
        THEN
      end note
      initUpdate <-- mwdiLive : { errorMessage }
      note over initUpdate #White
        ignored
      end note

      note over mwdiLive #LightGreen
        ELSE
      end note

      mwdiLive -> device : { mountName }
      activate device

          note left device #White
            takes 8min
            in average
          end note
      
      mwdiLive <-- device : { {controlConstruct} }
      deactivate device

      mwdiLive -> cache : { {controlConstruct} }

      note over mwdiLive
        lastSuccessfulCompleteControlConstructUpdateTime
        updated in [metaData]
      end note

    initUpdate <-- mwdiLive : { {controlConstruct} }
    deactivate mwdiLive

    note over initUpdate #White
      ignored
    end note

  end loop

  loop endless

    note over p2StreamPm
      - replicates MWDI ES into DPMDP Replica
      - reads lastSuccessfulCompleteControlConstructUpdateTime from [metaData] 
    end note

    loop for every updated CC

      p2StreamPm -> p2ProcessPm
      activate p2ProcessPm

        note over p2ProcessPm
          - processes PM data
          - transmits PM data
        end note

      p2StreamPm <-- p2ProcessPm
      deactivate p2ProcessPm

    end loop

@enduml
