openapi: 3.0.0
info:
  title: p1GetSortedBatchTimestampsFromDs
  version: 1.0.0

x-javascript-interface:
  p1GetSortedBatchTimestampsFromDs:
    summary: 'Gets the batch timestamps from the dataStore and returns them as a sorted list'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - data-store-es-client
              - mount-name
            properties:
              data-store-es-client:
                type: object
                description: >
                  'Data Store ElasticSearch address'
              mount-name:
                type: string
                description: >
                  'MountName'
    output:
      success:
        description: 'Sorted list of batch timestamps provided'
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
              description: >
                'The list of sorted batch timestamps (from old to new)
                from [/get-sorted-batch-timestamps-from-ds/sorted-batch-timestamps]'
      error:
        description: 'Reading batch timestamps failed'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'dataStoreEsClient not provided'
                - 'dataStoreEsClient invalid'
                - 'MountName not provided'
                - 'MountName invalid'
                - 'General processing error'
    processing:
      readTimestampsFromDs:
        url: # [{/get-sorted-batch-timestamps-from-ds/data-store-url}][/data-store/device={/get-sorted-batch-timestamps-from-ds/mount-name}/batch]
        output:
          success:
            description: 'Batch timestamps provided.'
            content:
              application/json:
                schema:
                  required:
                    - batch-timestamps
                  properties:
                    batch-timestamps:
                      type: array
                      items:
                        type: string
                      description: >
                        'Iterate over each batch item, extract its batch-timestamp and add it to batch-timestamps.
                        If no data is found return an empty list.'
          error:
            description: 'Reading batch timestamps failed'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'General processing error'
      sortTimestamps:
        input:
          required: true
          content:
            application/json:
              schema:
                required:
                  - batch-timestamps
                properties:
                  batch-timestamps:
                    type: array
                    items:
                      type: string
                    description: >
                      'List of unsorted batch timestamps
                      from [/get-sorted-batch-timestamps-from-ds/batch-timestamps]'
        output:
          success:
            description: 'Sorted batch-timestamps provided.'
            content:
              application/json:
                schema:
                  required:
                    - sorted-batch-timestamps
                  properties:
                    batch-timestamps:
                      type: array
                      items:
                        type: string
                      description: >
                        'List of batch timestamps
                        from {$sortTimestamps.input/batch-timestamps} sorted from oldest to newest timestamp value'
paths:
  /:
    description: 'no rest path provided by this module'