@startuml 101_p1ProcessingOrchestrator
skinparam responseMessageBelowArrow true

title
p1ProcessingOrchestrator
end title

participant "MWDI" as mwdi
participant "DPMDP" as dpmdp
participant "p1ProcessingOrchestrator" as po #LightBlue
participant "p1CreateDsfpOutput\nObjectFromCacheData" as createDsfp #LightBlue
participant "p1SetOutOfLevelValues\nToDefault" as setLevel #LightBlue
participant "p1Inquire15min\nAirInterfaceKpis\nFromCaca" as kpiAi #LightBlue
participant "p1Inquire15min\nEthernetContainerKpis\nFromCaca" as kpiEth #LightBlue
participant "p1ReplaceOnfDefaultValues" as replaceDef #LightBlue
participant "p1SetMostRecentTimestamp\nInDeviceTable" as deviceTable #LightBlue


note over mwdi, dpmdp #LightGrey
Notification can be provided via:
  - Kafka
  - or Webhook (subscription to MWDI)
end note

mwdi -> dpmdp : {counter, timestamp,\nobjectPath, attributeName,\nnewValue, \ndeviceType}
dpmdp -> po: {counter, timestamp,\nobjectPath, attributeName,\nnewValue, \ndeviceType}
activate po



note over po #LightSalmon
  Identify relevant notifications as:
  - IF (attributeName == 'timeOfLatestChange')
    AND (objectPath contains 'air-interface-historical-performances'
         or 'ethernet-container-historical-performances')
  - AND IF (no notification processed for the same mount-name within
    timeframe <i>waitingTimeForProcessingNotificationsForSameDevice</i>)

  IF (notification == irrelevant)
    terminate process
end note

po --> dpmdp: 204

note over po #LightSalmon
  ELSE
    create [/data-structure-for-processing] (Dsfp),
    fill in values from notification, set
    [/data-structure-for-processing/device-type]
    to <i>deviceType</i>
end note

note over po
  <u>SetDsfpOutput</u>
  Read the DsfpOutput object
  set [/data-structure-for-processing/output] = DsfpOutput.

  <i>dataHandle</i>: create a dataHandle pointing to the DsfpOutput
  object in memory for allow direct reading of/writing to
  DspfOuput from/in memory in subsequent steps.
end note
po -> createDsfp: {mountName from objectPath}
createDsfp --> po: {DsfpOutput}

note over po
  <u>ReplaceOutOfRangeLevelValues</u>
  The executed function replaces out-of-range level values by -1,
  the received changes are written back to DsfpOutput.
  (DspfOutput object identified by dataHandle.)
end note
po -> setLevel: {dataHandle}
setLevel --> po: {modified DsfpOutput.air-interface-list}

note over po
  <u>SetAirIfKpis</u>
  The executed function calls CapacityCalculator to
  compute AirInterface capacity KPIs (default=-1).
  The computed attribute values are set in
  DsfpOutput.
end note
po -> kpiAi: {dataHandle}
kpiAi --> po: {computed AirInterace KPIs}

note over po
  <u>SetEthContainerKpis</u>
  The executed function calls CapacityCalculator to
  compute EthernetContainer KPIs (default=-1).
  The computed attribute values are set in
  DsfpOutput.
end note
po -> kpiEth: {dataHandle}
kpiEth --> po: {computed EthernetContainer KPIs}

note over po
  <u>ReplaceOnfDefaultValues</u>
  The executed function replaces ONF default
  values (-1, "-1") of counter attributes in DsfpOutput
  - number: null
  - string: emptyString
end note
po -> replaceDef: {dataHandle}
replaceDef --> po: {modified DsfpOutput}

note over po
  <u>SetMostRecentTimestamps</u>
  The executed function reads the mostRecent timestamp
  for each interface from DsfpOutput and writes the
  information into DPMDP's internal deviceTable.
end note
po -> deviceTable: {dataHandle}

po --> dpmdp: 200, {[/data-structure-for-processing]}

deactivate po