@startuml p1LoadOffsetsAndStatusData
skinparam responseMessageBelowArrow true

title
  p1LoadOffsetsAndStatusData
end title

participant "p1ProcessDevice\n" as requestor
participant "p1LoadOffsetsAndStatusData\n" as cur
database "DataStore" as datastore

requestor -> cur: { {dataStoreEsClient},\nmountName }
activate cur

  note over cur
    retrieveOffsets
  end note
  cur -> datastore: { dataStoreEsClient://data-store/device=mountName/offsets }
  cur <-- datastore: { [offsets] }

  note over cur
    retrieveStatusData
  end note
  cur -> datastore: { dataStoreEsClient://data-store/device=mountName/status-data }
  cur <-- datastore: { [status-data] }
  
requestor <-- cur: { [offsets],\n[status-data] }
deactivate cur

@enduml
