openapi: 3.0.0
info:
  title: p1CreateResultCc
  version: 1.0.0

x-javascript-interface:
  p1CreateResultCc:
    summary: 'Creates the PM data (resultCc) from the raw data (rawCc)'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - raw-cc
            properties:
              parameters:
                type: object
                description: 'Hierarchical object holding the parameter settings'
              raw-cc:
                type: object
                description: >
                  'rawCc'
    output:
      success:
        description: 'Result CC data created'
        content:
          application/json:
            schema:
              type: object
              required:
                - result-cc
              properties:
                result-cc:
                  type: object
                  description: >
                    'The result control construct, following ONF structure.
                    from [/create-result-cc/result-cc]'
      error:
        description: 'Result CC data could not be created'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'parameters not provided'
                - 'parameters invalid'
                - 'rawCc not provided'
                - 'rawCc invalid'
                - 'resultCc could not be provided'
                - 'General processing error'
    processing:
      createResultCcFromRawCc:
        summary: 'Creates the resultCc object and fills it from rawCc data'
        input:
          required: true
          content:
            application/json:
              schema:
                required:
                  - raw-cc
                properties:
                  raw-cc:
                    type: object
                    description: >
                      'RawCc
                      from [/create-result-cc/raw-cc]'
        output:
          success:
            description: 'ResultCc provided'
            content:
              application/json:
                schema:
                  properties:
                    type: object
                    properties:
                      result-cc:
                        type: object
                        description: >
                          'ResultCc
                          from {$input#/raw-cc}'
        error:
          description: 'ResultCc could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'rawCc not provided'
                  - 'rawCc invalid'
                  - 'resultCc could not be provided'
                  - 'General processing error'
      p1PrepareTxModes:
        summary: 'Removes unused transmission modes and completes used ones with AirInterface capacity'
        input:
          required: true
          content:
            application/json:
              schema:
                required:
                  - historical-performance-data-list
                  - transmission-mode-list
                properties:
                  historical-performance-data-list:
                    type: array
                    description: >
                      'historicalPerformanceDataList
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/layer-protocol=*/air-interface-2-0:air-interface-pac/air-interface-historical-performances/historical-performance-data-list]'
                  transmission-mode-list:
                    type: array
                    description: >
                      'transmissionModeList
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/layer-protocol=*/air-interface-2-0:air-interface-pac/air-interface-capability/transmission-mode-list]'
        output:
          success:
            description: 'transmissionModeList provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - historical-performance-data-list
                    - transmission-mode-list
                  properties:
                    historical-performance-data-list:
                      type: array
                      description: >
                        'historicalPerformanceDataList'
                    transmission-mode-list:
                      type: array
                      description: >
                        'transmissionModeList'
          error:
            description: 'transmissionModeList could not be provided'
            content:
              application/json:
                schema:
                  type: string
      substringLinkId:
        summary: 'Creates the linkId from linkEndpointId'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - link-endpoint-id
                properties:
                  link-endpoint-id:
                    type: object
                    pattern: '^[0-9]{9}[AB]$'
                    description: >
                      'linkEndpointId
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/ltp-augment-1-0:ltp-augment-pac/external-label]'
        output:
          success:
            description: 'linkId provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - link-id
                  properties:
                    link-id:
                      type: string
                      description: >
                        'linkId = input.link-endpoint-id.substring(0, 9)'
        error:
          description: 'ResultCc could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'linkEndpointId not provided'
                  - 'linkEndpointId invalid'
                  - 'linkId could not be provided'
                  - 'General processing error'
      findParallelPhysic:
        summary: 'Finds parallel physical LTPs'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - ltp-uuid
                  - aggregation-group-list
                properties:
                  ltp-uuid:
                    type: string
                    description: >
                      'UUID of the LTP to find parallel physical LTPs for
                      from [/create-result-cc/result-cc/logical-termination-point=*/uuid]'
                  aggregation-group-list:
                    type: array
                    description: >
                      'List of Layer1AggregationGroups
                      from [/create-result-cc/aggregation-group-list]'
        output:
          success:
            description: 'List of parallel physical LTPs provided, might be empty'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - physical-server-ltp-list
                  properties:
                    physical-server-ltp-list:
                      type: array
                      items:
                        type: string
                      description: >
                        'List of UUIDs of parallel LTPs (AirInterfaces or WireInterfaces in the same Layer1AggregationGroup)
                        IF {$findParallelPhysic.input#ltp-uuid} is part of any {$findParallelPhysic.input#/aggregation-group-list=*/physical-server-ltp-list}
                        THEN all other members of same {$findParallelPhysic.input#/aggregation-group-list=*/physical-server-ltp-list}'
        error:
          description: 'List of parallel physical LTPs could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'ltpUuid not provided'
                  - 'ltpUuid invalid'
                  - 'aggregationGroupList not provided'
                  - 'aggregationGroupList invalid'
                  - 'General processing error'
      findMostRecentPeriodEndTime:
        summary: 'Finds most recent periodEndTime of a 15minutes slice in historicalPerformanceDataList'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - historical-performance-data-list
                properties:
                  historical-performance-data-list:
                    type: array
                    description: >
                      'historicalPerformanceDataList
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/layer-protocol=*/air-interface-2-0:air-interface-pac/air-interface-historical-performances/historical-performance-data-list
                              or /create-result-cc/result-cc/logical-termination-point={[/create-result-cc/ethernet-container-uuid[n]]}/layer-protocol=*/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances/historical-performance-data-list]'
        output:
          success:
            description: 'mostRecentPeriodEndTime provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - most-recent-period-end-time
                  properties:
                    most-recent-period-end-time:
                      type: string
                      description: >
                        'mostRecentPeriodEndTime
                        from max( {$input#/historical-performance-data-list=*/period-end-time} for {$input#/historical-performance-data-list=*/granularity-period}=={"air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN" OR "ethernet-container-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN"} )'
        error:
          description: 'mostRecentPeriodEndTime could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'historicalPerformanceDataList not provided'
                  - 'historicalPerformanceDataList invalid'
                  - 'mostRecentPeriodEndTime could not be provided'
                  - 'General processing error'
      findMostRecentPeriodEndTime24:
        summary: 'Finds most recent periodEndTime of a 24hours slice in historicalPerformanceDataList'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - historical-performance-data-list
                properties:
                  historical-performance-data-list:
                    type: array
                    description: >
                      'historicalPerformanceDataList
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/layer-protocol=*/air-interface-2-0:air-interface-pac/air-interface-historical-performances/historical-performance-data-list
                              or /create-result-cc/result-cc/logical-termination-point={[/create-result-cc/ethernet-container-uuid[n]]}/layer-protocol=*/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances/historical-performance-data-list]'
        output:
          success:
            description: 'MostRecentPeriodEndTime24 provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - most-recent-period-end-time-24
                  properties:
                    most-recent-period-end-time-24:
                      type: string
                      description: >
                        'mostRecentPeriodEndTime24
                        from max( {$input#/historical-performance-data-list=*/period-end-time} for {$input#/historical-performance-data-list=*/granularity-period}=={"air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS" OR "ethernet-container-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS"} )'
        error:
          description: 'mostRecentPeriodEndTime24 could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'historicalPerformanceDataList not provided'
                  - 'historicalPerformanceDataList invalid'
                  - 'mostRecentPeriodEndTime24 could not be provided'
                  - 'General processing error'
      p1CalculateEthernetKpis:
        summary: 'Adds Ethernet KPIs to historicalPerformanceDataList'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - historical-performance-data-list
                properties:
                  historical-performance-data-list:
                    type: array
                    description: >
                      'historicalPerformanceDataList
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/ethernet-container-uuid[n]]}/layer-protocol=*/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances/historical-performance-data-list]'
        output:
          success:
            description: 'Ethernet KPIs added'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - historical-performance-data-list
                  properties:
                    historical-performance-data-list:
                      type: array
                      description: >
                        'historicalPerformanceDataList'
        error:
          description: 'Ethernet KPIs could not be added'
          content:
            application/json:
              schema:
                type: string

paths:
  /:
    description: 'no rest path provided by this module'
