@startuml p1StreamPmData
skinparam responseMessageBelowArrow true

title
  p1StreamPmData
end title

participant "embedYourself\n" as embed
participant "p1StreamPmData\n" as p1RMWDI #LightCyan
participant "p1LoadParameters\n" as p1LP #LightCyan
participant "p1ResolveEsAddress\n" as p1REA #LightCyan
participant "p1CreateEs\n" as p1CMR #LightCyan
participant "p1UpdateMwdiReplica\n" as p1UMR #LightCyan
participant "p1ProcessDevice\n" as p1ProcessPm #LightCyan
participant "p1MaintainDs\n" as p1MDS #LightBlue

note right embed
  Automatically start
  p1StreamPmData
end note
embed -> p1RMWDI : {}
activate p1RMWDI #LightCyan

  p1RMWDI -> p1LP : {functionName=\n"p1StreamPmData"}
  activate p1LP #LightCyan
    note over p1LP
      Load parameters
      from configFile
    end note
  p1RMWDI <-- p1LP : {{parameters},\n{configFile}}
  deactivate p1LP

  Loop FOR all esName

    p1RMWDI -> p1REA : {{parameters},\n{configFile},\nesName}
    activate p1REA #LightCyan
      note over p1REA
        Resolve ES address
      end note
    p1RMWDI <-- p1REA : {{esAddress}}
    deactivate p1REA

    p1RMWDI -> p1CMR : {{parameters},\n{esAddress}}
    activate p1CMR #LightCyan
      note over p1CMR
        Create ES
      end note
    p1RMWDI <-- p1CMR
    deactivate p1CMR

  end Loop

  p1RMWDI -> p1MDS : {{parameters},\n{dataStoreAddress}}
  activate p1MDS #LightBlue
    note over p1MDS
      Maintain DataStore
    end note

  Loop endless

    p1RMWDI -> p1UMR : {{parameters},\nlastReplicaTime,\n{mwdiEsClient},\n{mwdiReplicaEsClient},\n{loggingEsClient}}
    activate p1UMR #LightCyan
      note over p1UMR
        Replicate updated CCs
      end note
    p1RMWDI <-- p1UMR : {[updatedMountNames],\ntimestamp}
    deactivate p1UMR

    p1RMWDI -> p1ProcessPm : {mountName,\n{parameters},\n{configFile}}
    activate p1ProcessPm #LightCyan
      note over p1ProcessPm
        Process PM data
      end note
    p1RMWDI <-- p1ProcessPm
    deactivate p1ProcessPm

  end Loop

@enduml
