@startuml p2DiscardIrrelevantPmRecords
skinparam responseMessageBelowArrow true

title
  p2DiscardIrrelevantPmRecords
end title

participant "requestor\n(e.g. p2LoadRawCc)" as requestor
participant "p1DiscardIrrelevant\nPmRecords" as cur


requestor -> cur: { [historicalPerformanceDataList],\n{offset} }
activate cur

loop FOR EACH record in [historicalPerformanceDataList]

  note over cur
    IF record.periodEndTime is not newer than:
      - 15min: /offset/mostRecentPeriodEndTime
      - 24h: /offset/mostRecentPeriodEndTime24
    THEN discard record
  end note

  note over cur
    For 15min granularity record:
      IF record.periodEndTime > new_mostRecentPeriodEndTime
      THEN new_mostRecentPeriodEndTime = record.periodEndTime
  end note

  note over cur
    For 24h granularity slirecordce:
      IF record.periodEndTime > new_mostRecentPeriodEndTime24
      THEN new_mostRecentPeriodEndTime24 = record.periodEndTime
  end note

end loop

note over cur
  /offset/mostRecentPeriodEndTime = new_mostRecentPeriodEndTime
  /offset/mostRecentPeriodEndTime24 = new_mostRecentPeriodEndTime24
end note

requestor <-- cur: { [filteredHistoricalPerformanceDataList],\n{offset} }

deactivate cur

@enduml
