openapi: 3.0.0
info:
  title: p2DiscardIrrelevantPmRecords
  version: 1.0.0

x-javascript-interface:
  p2DiscardIrrelevantPmRecords:
    summary: 'This function discards irrelevant PM records'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - historical-performance-data-list
              - former-most-recent-period-end-time
              - former-most-recent-period-end-time-24
            properties:
              historical-performance-data-list:
                type: array
                description: 'The list of historical PM records, that shall be filtered'
              former-most-recent-period-end-time:
                type: string
                description: >
                  'mostRecentPeriodEndTime from past processing'
              former-most-recent-period-end-time-24:
                type: string
                description: >
                  'mostRecentPeriodEndTime from past processing'
    output:
      success:
        description: 'filteredHistoricalPerformanceDataList provided'
        content:
          application/json:
            schema:
              type: object
              required:
                - filtered-historical-performance-data-list
                - new-most-recent-period-end-time
                - new-most-recent-period-end-time-24
                - received
              properties:
                filtered-historical-performance-data-list:
                  type: array
                  description: >
                    'Filtered list of historical PM records
                    from [/discard-irrelevant-pm-records/filtered-historical-performance-data-list]'
                new-most-recent-period-end-time:
                  type: string
                  description: >
                    'newMostRecentPeriodEndTime
                    from [/discard-irrelevant-pm-records/new-most-recent-period-end-time]'
                new-most-recent-period-end-time-24:
                  type: string
                  description: >
                    'newMostRecentPeriodEndTime24
                    from [/discard-irrelevant-pm-records/new-most-recent-period-end-time-24]''
                received:
                  type: array
                  description: >
                    'Number of received 15min PM records categorized by date
                    from [/discard-irrelevant-pm-records/received]'
      error:
        description: 'filteredHistoricalPerformanceDataList could not be provided'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'historicalPerformanceDataList not provided'
                - 'historicalPerformanceDataList invalid'
                - 'formerMostRecentPeriodEndTime not provided'
                - 'formerMostRecentPeriodEndTime invalid'
                - 'formerMostRecentPeriodEndTime24 not provided'
                - 'formerMostRecentPeriodEndTime24 invalid'
                - 'historicalPerformanceDataList filtering error'
                - 'updateNewMostRecentPeriodEndTime update error'
                - 'number of received 15min PM records could not be updated'
                - 'general processing error'
    processing:
      countReceived15MinPmSlices:
        summary: 'Counts the number of received, but not filtered out 15min PM slices per date'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - received
                  - granularity-period
                  - period-end-time
                properties:
                  received:
                    type: array
                    description: >
                      'Number of received 15min PM records categorized by date
                      from [/discard-irrelevant-pm-records/received]'
                  granularity-period:
                    type: string
                    description: >
                      'granularityPeriod
                      from [/discard-irrelevant-pm-records/historical-performance-data-list=*/granularity-period]'
                  period-end-time:
                    type: string
                    description: >
                      'periodEndTime
                      from [/discard-irrelevant-pm-records/historical-performance-data-list=*/period-end-time]'
        output:
          success:
            description: 'Received 15min PM record counted'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - received
                  properties:
                    received:
                      type: array
                      x-key: date
                      items:
                        type: object
                        required:
                          - date
                          - count
                        properties:
                          date:
                            type: integer
                            description: >
                              'date
                              receivedDate = parsing periodEndTime of the currently processed 15min PM slice and expressing in the format YYYY/MM/DD
                              new instance in [received] to be added, if {$input#received={receivedDate}} not yet existing
                              already existing as {receivedDate} or created from {receivedDate}'
                          count:
                            type: integer
                            description: >
                              'The count of received 15min PM slices for that date
                              if {receivedDate} not yet exists, initialized with 0
                              from {IF {$input#granularity-period==15-MIN} THEN {$input#received={receivedDate}/count to be incremented by 1} }'
          error:
            description: 'Received 15min PM record could not be counted'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'received not provided'
                    - 'received invalid'
                    - 'granularityPeriod not provided'
                    - 'granularityPeriod invalid'
                    - 'periodEndTime not provided'
                    - 'periodEndTime invalid'
                    - 'general processing error'
      updateNewMostRecentPeriodEndTime:
        summary: 'Overwrites newMostRecentPeriodEndTime or newMostRecentPeriodEndTime24 with latest value (means, most recent date) of periodEndTime (includes periodEndTimes from discarded records).'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - new-most-recent-period-end-time
                  - new-most-recent-period-end-time-24
                  - granularity-period
                  - period-end-time
                properties:
                  new-most-recent-period-end-time:
                    type: string
                    description: >
                      'newMostRecentPeriodEndTime
                      from [/discard-irrelevant-pm-records/new-most-recent-period-end-time]'
                  new-most-recent-period-end-time-24:
                    type: string
                    description: >
                      'newMostRecentPeriodEndTime24
                      from [/discard-irrelevant-pm-records/new-most-recent-period-end-time-24]'
                  granularity-period:
                    type: string
                    description: >
                      'granularityPeriod
                      from [/discard-irrelevant-pm-records/historical-performance-data-list=*/granularity-period]'
                  period-end-time:
                    type: string
                    description: >
                      'periodEndTime
                      from [/discard-irrelevant-pm-records/historical-performance-data-list=*/period-end-time]'
        output:
          success:
            description: 'newMostRecentPeriodEndTime provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - new-most-recent-period-end-time
                    - new-most-recent-period-end-time-24
                  properties:
                    new-most-recent-period-end-time:
                      type: string
                      description: >
                        'newMostRecentPeriodEndTime
                        if {$input#granularity-period} indicates 15-MIN
                          from { max ( {$input#period-end-time}, {$input#new-most-recent-period-end-time} ) }
                        else
                          from {$input#new-most-recent-period-end-time} (unchanged)'
                    new-most-recent-period-end-time-24:
                      type: string
                      description: >
                        'newMostRecentPeriodEndTime24
                        if {$input#granularity-period} indicates 24-HOURS
                          from { max ( {$input#period-end-time}, {$input#new-most-recent-period-end-time-24} ) }
                        else
                          from {$input#new-most-recent-period-end-time-24} (unchanged)'
          error:
            description: 'newMostRecentPeriodEndTime could not be provided'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'newMostRecentPeriodEndTime not provided'
                    - 'newMostRecentPeriodEndTime invalid'
                    - 'newMostRecentPeriodEndTime24 not provided'
                    - 'newMostRecentPeriodEndTime24 invalid'
                    - 'granularityPeriod not provided'
                    - 'granularityPeriod invalid'
                    - 'periodEndTime not provided'
                    - 'periodEndTime invalid'
                    - 'newMostRecentPeriodEndTime could not be provided'
                    - 'general processing error'

paths:
  /:
    description: 'no rest path provided by this module'
