@startuml p2DiscardIrrelevantPmRecords
skinparam responseMessageBelowArrow true

title
  p2DiscardIrrelevantPmRecords
end title

participant "requestor\n(e.g. p2LoadRawCc)" as requestor
participant "p2DiscardIrrelevant\nPmRecords" as cur


requestor -> cur: { [historicalPerformanceDataList],\nformerMostRecentPeriodEndTime,\nformerMostRecentPeriodEndTime24 }

activate cur

  note over cur
    Initializes:
      newMostRecentPeriodEndTime
      newMostRecentPeriodEndTime24
  end note
  note over cur
    Initializes:
      received = { [day, count] }
  end note

  loop FOR EACH record in [historicalPerformanceDataList]

    note over cur
      IF (record.periodEndTime) is not newer than:
        - 15min: formerMostRecentPeriodEndTime
        - 24h: formerMostRecentPeriodEndTime24
    end note
    note right cur
      THEN
        discard record
      ELSE
        update received for day parsed
        from record.periodEndTime as
        { [day, count++] }
    end note

    note over cur
      updateNewMostRecentPeriodEndTime
    end note

  end loop

requestor <-- cur: { [filteredHistoricalPerformanceDataList],\nnewMostRecentPeriodEndTime,\nnewMostRecentPeriodEndTime24,\nreceived }

deactivate cur

@enduml
