@startuml p1FormattingOutputOnf
skinparam responseMessageBelowArrow true

title
  p1FormattingOutputOnf
end title

participant "requestor\n(e.g. p1ProcessDevice)" as requestor
participant "p1FormattingOutputOnf\n" as cur #LightCyan
participant "p1FieldsFilter\n" as fieldsFilter #LightBlue

requestor -> cur: { {parameters},\n{resultCc} }
activate cur #LightCyan

  note over cur
    Creates onfOutputFormat
  end note

  cur -> fieldsFilter: { {onfOutputFormat},\nfieldsFilter }
  activate fieldsFilter #LightBlue
    note over fieldsFilter
      Applies FieldsFilter
    end note
  cur <-- fieldsFilter: { {onfOutputFormat} }
  deactivate fieldsFilter #LightBlue

requestor <-- cur: { {onfOutputFormat} }
deactivate cur

@enduml
