@startuml p1FormattingOutputOnf
skinparam responseMessageBelowArrow true

title
  p1FormattingOutputOnf
end title

participant "requestor\n(e.g. p2ProcessDevice)" as requestor
participant "p1FormattingOutputOnf\n" as cur
participant "p1FieldsFilter\n" as fieldsFilter

requestor -> cur: { {parameters},\n{resultCc} }
activate cur

  note over cur
    Creates onfOutputFormat
  end note

  cur -> fieldsFilter: { {onfOutputFormat},\nfieldsFilter }
  activate fieldsFilter
    note over fieldsFilter
      Applies FieldsFilter
    end note
  cur <-- fieldsFilter: { {onfOutputFormat} }
  deactivate fieldsFilter

requestor <-- cur: { formatName,\n{outputFormat} }
deactivate cur

@enduml
