@startuml hl_sequence
skinparam responseMessageBelowArrow true

title
  DevicePerformanceManagementDataProcessor
end title

participant "cronjob\nin ES" as cjes
participant "regardAttribute-\nValueChange" as rAVC #LightCyan
participant "p1ProcessingOrchestrator\nForHistoricalPm" as p1ProOrch #LightCyan

activate rAVC #LightCyan

cjes -> rAVC : { [mountName] }
note over rAVC
  cronjob informs about new or
  updated CCs in MWDI ES Replica
end note

rAVC -> p1ProOrch : {mountName}
activate p1ProOrch #LightCyan

  note over p1ProOrch
    Process PM data
  end note


@enduml
