@startuml p1CreateActiveFunctionsTxtDoc
skinparam responseMessageBelowArrow true

title
  p1CreateActiveFunctionsTxtDoc
end title

participant "requestor\n" as requestor
participant "p1CreateActiveFunctionsTxtDoc\n" as cur #LightCyan
participant "p1LoadParameters\n" as loadParams


requestor -> cur: { functionName }
activate cur

    cur -> loadParams: { functionName=\ntargetFunctionName }
    activate loadParams

      note over loadParams
        Loads parameters from configFile
        (parameters = recursively combined
        function information)
      end note

    cur <-- loadParams: { {parameters} }
    deactivate loadParams

    note over cur
      Parse (sub)-function information
      (for active functions only),
      format and add it to documentation:
      - keep functionName, functionDescription
        - same for subfunctions
      - keep string parameters info:
        stringName, stringPurpose, stringValue
      - add identation according to element level
    end note

requestor <-- cur: { documentation }
deactivate cur

@enduml
