@startuml p1CalculateIntervalCapacity
skinparam responseMessageBelowArrow true

title
  p1CalculateIntervalCapacity
end title

participant "p1IterateAi\nPmSlices" as requestor
participant "p1Calculate\nIntervalCapacity" as intCC #LightBlue

  requestor -> intCC : { [time-xstates-list],\n[transmission-mode-list] }
  activate intCC #LightBlue
    note over intCC
      Calculates intervalCapacity
    end note
  requestor <-- intCC: {intervalCapacity}
  deactivate intCC

@enduml
