@startuml embedYourself
skinparam responseMessageBelowArrow true

title
  embedYourself
end title

participant "RegistryOffice\n" as RO
participant "embedYourself\n" as embed
participant "bequeathYourDataAndDie\n" as bequeath

participant "p2StreamPmData\n" as p2Stream


RO -> embed
activate embed

  embed -> bequeath
  activate bequeath
    note over bequeath
      [further steps for handing over
      data potentially to be added]
    end note
  embed <-- bequeath : 204
  deactivate bequeath

  note over embed
    [further steps of the embedding
    process potentially to be added]
  end note

  note right embed
    Automatically start
    p2StreamPmData
  end note
  embed -> p2Stream
  activate p2Stream

deactivate embed

@enduml
