@startuml p1FormattingOutputApt
skinparam responseMessageBelowArrow true

title
  p1FormattingOutputApt
end title

participant "requestor\n(e.g. p1ProcessDevice)" as requestor
participant "p1FormattingOutputApt\n" as cur

requestor -> cur: { {resultCc} }
activate cur

  note over cur
    Transforms resultCc data into
    aptOutputFormat (incl.
    batchTimestamp)
  end note

requestor <-- cur: { formatName,\n{outputFormat} }
deactivate cur

@enduml
