@startuml p1CalculateBusyHourPerformanceIndicators
skinparam responseMessageBelowArrow true

title
  p1CalculateBusyHourPerformanceIndicators
end title

participant "p2IterateEcPmSlices\n" as requestor
participant "p1CalculateBusyHour\nPerformanceIndicators" as calBh

requestor -> calBh : { {historicalPerformanceData},\n{status} }
activate calBh

  note over calBh
    summarize total-bytes-output for each hour of the day
    summarize values in [/interface-status/15-minute-values-by-day={day}/15-minute-values-by-hour=*/15-minute-values/total-bytes-output]
  end note

  note over calBh
    identify the hour with the highest sum of total-bytes-output as busy hour
  end note

  note over calBh
    transfer all values of the period-end-time attribute of the 15-minute-values into the /busy-hour/period-end-time-list
  end note


requestor <-- calBh : { {historicalPerformanceData} }
deactivate calBh

deactivate requestor

@enduml
