@startuml p1MaintainDeviceInDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1MaintainDeviceInDs
end title

participant "p1MaintainDs" as requestor
participant "p1MaintainDeviceInDs" as cur #LightCyan
participant "p1MaintainDevInterfaceInDs" as intf #LightCyan
participant "p1ReadLotTimestampsInDs" as lotTs #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{dataStoreEsClient},\nretentionPeriod,\nmountName}
activate cur #LightCyan

  note over cur #LightGray
    Steps: (box tb removed)
    - maintain device/interface:
      - get interfaceList
      - iterate over interfaceList to maintain each interface
    - delete devices without remaining interfaces:
      - get interfaceCount
      - delete device if interfaceCount==0
    - delete expired lots:
      - get sortedLotTimestamps
      - iterate of each timestamp: delete lot if expired,
        break if not-expired timestamp seen
  end note

  ' Interfaces
  == Maintain device interfaces ==

  note over cur
    <u>GetDeviceInterfaceMetadata</u>
      Read the interface metadata for the mountName
      from [/data-store/device=mountName]
  end note
  cur -> ds: {mountName}
  note over ds #WhiteSmoke
    read
  end note
  cur <-- ds: {{interfaceMetadata}}

  loop FOR EACH interface in interfaceMetadata
    note over cur
      <u>p1MaintainDevInterfaceInDs</u>
    end note
    cur -> intf: {{dataStoreEsClient},\nretentionPeriod,\nmountName,\n{interface}}
    activate intf #LightCyan
      note over intf
        Deletes the interfaceInstance
        from DS if expired
      end note
      intf -> ds
      note over ds #WhiteSmoke
        delete
      end note
      intf <-- ds
    cur <-- intf
    deactivate intf

  end loop

  ' Device deletion
  == Delete the device from DS if expired ==

  note over cur
    <u>GetInterfaceCount</u>
    Returns the size of interfaceMetadata
    (i.e. number of records)
  end note
  cur -> ds: {mountName}
  note over ds #WhiteSmoke
    read
  end note
  cur <-- ds: {interfaceCount}

  note over cur
    <u>DeleteExpiredDevice</u>
    IF (interfaceCount==0)
    THEN DELETE complete device [/data-store/device=mountName]
         from dataStore
         and exit
  end note
  cur -> ds: {mountName}
  note over ds #WhiteSmoke
    delete
  end note
  cur <-- ds
  requestor <-- cur: (if device deleted)

  ' Lot deletion
  == Delete expired lots for the device from dataStore ==

  note over cur
    <u>p1GetSortedBatchTimestampsFromDs</u>
      Get the list of sorted batch timestamps from dataStore
      (sorted from oldest to newest).
  end note
  cur -> lotTs: {{dataStoreEsClient},\nmountName}
  activate lotTs #LightCyan
    lotTs -> ds
    note over lotTs
      Read and sort list of
      batch timestamps
    end note
    note over ds #WhiteSmoke
    read
    end note
    lotTs <-- ds
  cur <-- lotTs: {{sortedBatchTimestamps}}
  deactivate lotTs


  loop FOR EACH timestamp in sortedLotTimestamps
    note over cur
      <u>DeleteExpiredBatches</u>
        IF (timestamp older than allowed by retentionPeriod)
        THEN DELETE related batch from datastore:
          [/data-store/device=mountName/batch=timestamp]
        ELSE
          break
    end note

  cur -> ds: {mountName, timestamp}
  note over ds #WhiteSmoke
    delete
  end note
  cur <-- ds

  end loop

requestor <-- cur

deactivate cur




@enduml
