@startuml diagram
skinparam responseMessageBelowArrow true

title
  p1ProcessDevice
end title

participant "requestor\ne.g. regardAttributeValueChange" as requestor
participant "p1ProcessDevice" as po #LightBlue
participant "p1LoadRawCc" as loadData #LightCyan
participant "tb added later\n(not pre-release scope)" as tbd #LightGray
participant "p1FormattingOutputApt" as outputApt #LightCyan
participant "p1TransmittingKafka" as p1Trans #LightCyan
participant "p1PrepareStoring\n(not pre-release scope)" as p1PrepStore #LightGray
participant "p1Storing\n(not pre-release scope)" as p1Store #LightGray


requestor -> po : {mountName, processingStartTime}
activate po

== Creation of DSFP and adding rawCC data ==

note over po
  Create DataStructureForProcessing (DSFP)
  incl. mountName and processingStartTime
end note

note over po
  <u>RetrievalOfRawDeviceData</u>
  The called function retrieves the ControlConstruct
  data for the mountName from the ElasticSearch copy.
  Thereby it ensures that only relevant data is kept.
  It does not return the data itself, but a reference
  to the raw ControlConstruct object in DPMDP runtime
  memory. This object follows ONF format.
end note

po -> loadData: {mountName}
po <-- loadData: {_rawCC*}

note over po
  Determine if the CC in _rawCC* contains
  any AirInterface or EthernetContainer layerProtocols.
  If not, then no new PM data was seen and
  the process is to be terminated.
end note

note over po
  The rawCC* object referenced in the response
  is stored in DSFP.

  <i>The stored data contains information about </i>
  <i>the deviceType (equipAugment/deviceModelName),</i>
  <i>in case deviceType-specific processing is</i>
  <i>required in subsequent steps.</i>
end note

== Creation of resultCC ==

note over po #LightGray
  The _rawCC* data is used to create the resultCC object.
  This object is also in ONF schema, but extended by additional attributes
  (e.g. for storing KPI values).
  
  Various functions will be executed here with _rawCC* as input.
  Their output will be written to the resultCC.
  
  These steps are out of scope for the pre-release and
  therefore not described in detail here.
end note

po --> tbd: <i>{_rawCC*}</i>
po <-- tbd: <i>{_resultCC}</i>

== Creation of Output object ==

note over po
  Create the OutputApt object from _resultCC data.
  The returned output gets added to DSFP.
end note
note over po #Orange
  In pre-release call with _rawCC* instead!
end note

po -> outputApt: {_resultCC, {input}, {parameters}}
po <-- outputApt: {output}

== Transmit to Kafka ==

note over po
  The output gets transmitted.
end note

po -> p1Trans: {_output, {input}, {parameters}}
po <-- p1Trans

== Storing of Data ==

note over po #LightGray
  The DSFP object needs to be prepared
  for data storing (e.g. delete {rawCC*}
  and {output}).
  This is out of scope for pre-release
end note
po -> p1PrepStore: {_DataStructureForProcessing}
po <-- p1PrepStore

note over po #LightGray
  The prepared DSFP object gets stored.
  This is out of scope for pre-release
end note
po -> p1Store: {_DataStructureForProcessing}
po <-- p1Store

deactivate po

@enduml

