@startuml p1GetSortedBatchTimestampsFromDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1GetSortedBatchTimestampsFromDs
end title

participant "requestor\n" as requestor
participant "p1GetSortedBatch\nTimestampsFromDs" as cur #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{dataStoreEsClient},\nmountName}
activate cur #LightCyan

  note over cur
    <u>ReadTimestampsFromDs</u>
    Read the timestamp of each lot
    in the dataStore for the input device
    from [/data-store/device=mountName/lot/timestamp]
  end note
  cur -> ds: {mountName}
  cur <-- ds: {{batchTimestamps}}

  note over cur
    <u>SortTimestamps</u>
    Sort the timestamps in batchTimestamps
    from old to new.

    Return the sorted list.
  end note
  requestor <-- cur: {{sortedTimestamps}}

deactivate cur

@enduml
