@startuml 011_p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput
skinparam responseMessageBelowArrow true

title
p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput
end title

participant "requestor" as requestor
participant "p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput" as setLvl #LightBlue

activate setLvl
requestor -> setLvl: {DsfpOutput.air-interface-list}

note over setLvl
  <u>ReplaceOutOfRangeValues</u>
  Iterate over all items in air-interface-list.
  
  If out-of-range values for any transmit-level or receive-level attributes are encountered,
  the respective attribute value is set to default (-1):

  IF NOT (transmit-level attribute within range [-30, 40]) THEN replace with -1
  IF NOT (reveive-level attribute within range (-129, -99.9) AND (-99.9, -10)) THEN replace with -1
end note

setLvl --> requestor: {modified DsfpOutput.air-interface-list}

deactivate setLvl