@startuml 012_p1Inquire15minAirInterfaceKpisFromCacaAndSetInDsfpOutput
skinparam responseMessageBelowArrow true

title
p1Inquire15minAirInterfaceKpisFromCacaAndSetInDsfpOutput
end title

participant "requestor" as requestor
participant "p1Inquire15minAirInterfaceKpisFromCacaAndSetInDsfpOutput" as setKpi #LightBlue
participant "CaCa://v1/compute-air-interface-capacity-kpis-for-list-of-air-interfaces" as caca

activate setKpi
requestor -> setKpi: {DsfpOutput.air-interface.list}

note over setKpi
<u>GetKpis</u>
  Send relevant data from DsfpOutput.air-interface-list to CaCa.
  CaCa will attempt to compute the capacity KPIs for every
  AirInterface from the list.
  (Where KPI computation failed, CaCa will return -1 as attribute value.)
end note

setKpi -> caca: {DsfpOutput.air-interface-list.excerpt}
caca --> setKpi: {computedKpiAttributes}

note over setKpi
<u>SetKpiValues</u>
  in DsfpOutput
  and return the modifiedDsfpOutput.
end note

setKpi --> requestor: {modified DsfpOutput.air-interface.list}

deactivate setKpi