@startuml 014_p1ReplaceOnfDefaultValuesInDsfpOutput
skinparam responseMessageBelowArrow true

title
p1ReplaceOnfDefaultValuesInDsfpOutput
end title

participant "requestor" as requestor
participant "p1ReplaceOnfDefaultValuesInDsfpOutput" as replace #LightBlue

activate replace
requestor -> replace: {DsfpOutput}

note over replace
<u>ReplaceOnfDefaultValues</u>
  replace ONF default values of counter attributes as follows:
  - integer: -1 -> null
  - string: "-1" -> emptyString

  Note:
  - some EthernetContainer counter attributes are provided as string
  - default values not yet finally aligned with customers
end note

replace --> requestor: {modified DsfpOutput}

deactivate replace