openapi: 3.0.0
info:
  title: p1TransmittingKafka
  version: 1.0.0

x-javascript-interface:
  p1TransmittingKafka:
    summary: 'Transmits payloads to kafka'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - config-file
              - output-format
              - kafka-transmitter
            properties:
              parameters:
                type: object
                description: >
                  'Subtree of the parameters object for p1TransmittingKafka'
              config-file:
                type: object
                description: >
                  'configFile content'
              output-format:
                type: array
                x-key: format-name
                description: >
                  'Array of output formats to be transmitted'
              kafka-transmitter:
                type: string
                description: >
                  'Identifies KafkaClient and output format to be used for this run of p1TransmittingKafka'
    output:
      success:
        description: 'Objects sent via Kafka'
      error:
        description: 'Objects could not be sent via Kafka'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'Producer connection error'
                - 'Other transmission error'
    processing:
      kafkaProducerService.sendMessage:
        summary: 'This function sends message to provided topic'
        input:
          content:
            application/json:
              schema:
                required:
                  - topic
                  - message
                properties:
                  topic:
                    type: string
                    description: >
                      'Target topic in Kafka broker where the messages shall be sent
                      from [/transmitting-kafka/topic-name]'
                  message:
                    type: object
                    description: >
                      'The object that shall be sent
                      from [/transmitting-kafka/message-object]'
        output:
          success:
            description: 'Message successfully sent'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    response:
                      type: object
                      properties:
                        status:
                          type: integer
                          minimum: 200
                          maximum: 200
          error:
            description: 'Message could not be sent to Kafka'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    response:
                      type: object
                      properties:
                        status:
                          type: integer
                          minimum: 532
                          maximum: 532

paths:
  /:
    description: 'no rest path provided by this module'
