@startuml p1TransmittingKafka
skinparam responseMessageBelowArrow true

title
  p1TransmittingKafka
end title

participant "requestor\n" as requestor
participant "p1TransmittingKafka\n" as p1Trans #LightCyan
participant "kafkaProducerService.\nsendMessage" as p1KafkaP #LightCyan
queue "kafka\n" as kafka

activate p1KafkaP #LightCyan

requestor -> p1Trans : {{parameters},\n{configFile},\nkafkaClientName,\n{messageObject}}
activate p1Trans #LightCyan

  note over p1Trans
    Resolve connection parameters
  end note

  p1Trans -> p1KafkaP : {topicName,\n{messageObject}}

    note over p1KafkaP
      Send object 
      to Kafka
    end note

    p1KafkaP -> kafka : {SEND_MESSAGE event}
    p1KafkaP <-- kafka

  p1Trans <-- p1KafkaP

requestor <-- p1Trans
deactivate p1Trans

@enduml