@startuml curmittingKafka
skinparam responseMessageBelowArrow true

title
curmittingKafka
end title

participant "embedYourself" as embed
participant "p1ProcessDevice" as processDevice #LightCyan
participant "p1TransmittingKafka" as cur #LightCyan


participant "p1KafkaProducer" as p1KafkaP #LightGreen

participant "function for init connection" as initCon #Violet
participant "function for transmit payload" as transmitData #Violet

queue "kafka" as kafka #LightSkyBlue

== Initialization Stage ==
note right embed
Initialize Connection
to Kafka
end note

embed -> cur

activate cur #LightCyan

note over cur
establishInitialConnection
end note

note over cur
extract clientId, brokerList 
from parameters and configFile
end note

note over cur #Violet
  functionname==connect seems to be wrong
end note
cur -> p1KafkaP : {clientId, brokerList, \nfunctionName=connect}
activate p1KafkaP #LightGreen

' ----- initCon ------------
activate initCon #Violet
cur --> initCon #Violet
  note over initCon #Violet
    init connection with own function?
    (replace p1KafkaProducer)
  end note
cur <-- initCon
deactivate initCon
' ---------------------------

note over p1KafkaP
establish session to
kafka as producer
end note
p1KafkaP -> kafka : {CONNECT event}
kafka --> p1KafkaP
p1KafkaP --> cur : success

deactivate p1KafkaP

deactivate cur

== Payload Transmit Stage - request-based invokation == 
processDevice -> cur : {_outputFormat, parameters}
activate cur #LightCyan

' ----- transmitData ------------
activate transmitData #Violet
cur --> transmitData #Violet
  note over transmitData #Violet
    transmit data via 2nd function?
    (replace p1KafkaProducer) 
  end note
cur <-- transmitData
deactivate transmitData
' ---------------------------


note over cur#LightPink
  Messages are only pushed to Kafka,
  while profileInstance
  <i>kafkaNotificationProvisioningSwitch</i> == on
end note

note over cur
extract 
topicName=(output-format/format-name 
              match config-file/topic-name)
payload=(output-format/content)
end note

cur -> p1KafkaP : {topicName, payload \n functionName=sendMessage}
activate p1KafkaP #LightGreen
note over p1KafkaP
send payload 
to kafka
end note

p1KafkaP -> kafka : {message}
note over kafka
stores in 
given topic
end note

kafka --> p1KafkaP

p1KafkaP --> cur : {sucess/error}

deactivate p1KafkaP

cur --> processDevice : {sucess/error}
deactivate cur

@enduml