openapi: 3.0.0
info:
  title: p1CreateResultCc
  version: 1.0.0

x-javascript-interface:
  p1CreateResultCc:
    summary: 'Creates the PM data (resultCc) from the raw data (rawCc)'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - raw-cc
            properties:
              parameters:
                type: object
                description: >
                  'parameters object for p1CreateResultCc'
              raw-cc:
                type: object
                description: >
                  'rawCc'
    output:
      success:
        description: 'Result CC data created'
        content:
          application/json:
            schema:
              type: object
              required:
                - result-cc
              properties:
                  result-cc:
                    type: object
                    description: >
                      'The result control construct, following ONF structure.
                      from [/create-result-cc/result-cc]'
      error:
        description: 'Result CC data could not be created'
        content:
          application/json:
            schema:
              type: string
              enum:
                # todo: reasonable error messages to be added
                - 'Input data structure incomplete or invalid'
                - 'General processing error'
    processing:
      createResultCcFromRawCc:
        description: >
          'Creates the resultCc object and fills it from rawCc data'
        input:
          content:
            application/json:
              schema:
                properties:
                  raw-cc:
                    type: object
                    description: >
                      'RawCc
                      from [/create-result-cc/raw-cc]'
        output:
          success:
            description: 'ResultCc provided'
            content:
              application/json:
                schema:
                  properties:
                    type: object
                    properties:
                      result-cc:
                        type: object
                        description: >
                          'ResultCc'
        error:
          description: 'ResultCc could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'RawCc missing'
                  - 'RawCc incomplete or invalid'
                  - 'RawCc could not be copied to ResultCc'
                  - 'General processing error'
      p1CleanupTxModes:
        description: >
          'Removes transmissionModeList entries not referenced in Configuration or timeXstatesList'
        # Will be added in next release
      p1CleanupAdmCounters:
        description: >
          'Removes timeXstatesList entries with time==0'
        # Will be added in next release
      substringLinkId:
        description: >
          'Creates the linkId from linkEndpointId'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - link-endpoint-id
                properties:
                  link-endpoint-id:
                    type: object
                    pattern: '^[0-9]{9}[AB]$'
                    description: >
                      'linkEndpointId
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/ltp-augment-1-0:ltp-augment-pac/external-label]'
        output:
          success:
            description: 'linkId provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - link-id
                  properties:
                    link-id:
                      type: string
                      description: >
                        'linkId = input.link-endpoint-id.substring(0, 9)'
        error:
          description: 'ResultCc could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'linkEndpointId missing'
                  - 'linkEndpointId invalid'
                  - 'linkId could not be created'
                  - 'General processing error'
      p1ComputePhysicalLag:
        description: >
          '
          '
        # Nicht klar, was hier gemacht werden soll
        # Die AggregationGroup ist im Layer1AggregationProfile beschrieben
        # d.h. eigentlich muss die Gruppe nicht aus clientLtp/serverLtp gebildet werden
        # sondern nur das Layer1AggregationProfile mit ins radCC aufgenommen werden

      p1CalculateAiCapacity:
        description: >
          'Calculates the AirInterface capacity according to ONF TR-532 v2.0'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - channel-bandwidth
                  - symbol-rate-reduction-factor
                  - number-of-states-in-modulation
                  - code-rate
                properties:
                  channel-bandwidth:
                    type: integer
                    description: >
                      'Channel bandwidth in kHz
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/air-interface-augment-1-0:air-interface-augment-pac/air-interface-capability/transmission-mode-list={transmission-mode-name}/channel-bandwidth]'
                  symbol-rate-reduction-factor:
                    type: integer
                    description: >
                      'Symbol rate reduction factor
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/air-interface-augment-1-0:air-interface-augment-pac/air-interface-capability/transmission-mode-list={transmission-mode-name}/symbol-rate-reduction-factor]'
                  number-of-states-in-modulation:
                    type: integer
                    description: >
                      'Number of states in modulation
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/air-interface-augment-1-0:air-interface-augment-pac/air-interface-capability/transmission-mode-list={transmission-mode-name}/modulation-scheme]'
                  code-rate:
                    type: integer
                    description: >
                      'Code rate in percent
                      from [/create-result-cc/result-cc/logical-termination-point={[/create-result-cc/air-interface-uuid[n]]}/air-interface-augment-1-0:air-interface-augment-pac/air-interface-capability/transmission-mode-list={transmission-mode-name}/code-rate]'
        output:
          success:
            description: 'AirInterface capacity calculated'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - air-interface-capacity
                  properties:
                    air-interface-capacity:
                      type: integer
                      description: >
                        'airInterfaceCapacity'
          error:
            description: 'AirInterface capacity could not be calculated'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'Input parameters missing'
                    - 'Input parameters invalid'
                    - 'General processing error'








      addMostRecentPeriodEndTime:
        description: >
          'Adds mostRecentPeriodEndTime attribute to HistoricalPerformances'
        input:
          content:
            application/json:
              schema:
                # todo: define input schema
        output:
          success:
            description: 'mostRecentPeriodEndTime attributes added'
            content:
              application/json:
                schema:
                  # todo: define output schema
        error:
          description: 'mostRecentPeriodEndTime attributes could not be added'
          content:
            application/json:
              schema:
                type: string
                enum:
                  # todo: reasonable error messages to be added

      #addLinkId:
      #addAggregationGroup:

      #p1DefaultValueTreatment
      #p1OutOfRangeValueTreatment
      #p1CalculateAiCapacity
      #p1EthernetKpiCalculation


paths:
  /:
    description: 'no rest path provided by this module'
