@startuml p1CreateResultCc
skinparam responseMessageBelowArrow true

title
  p1CreateResultCc
end title

participant "p1ProcessDevice\n" as requestor
participant "p1CreateResultCc\n" as cur #LightCyan

participant "p1Prepare\nTxModes" as prepTxModes #LightCyan
participant "p1Calculate\nAiCapacity" as aiCC #LightCyan

participant "p1OutOfRange\nValueTreatment" as outOfRange
participant "p1Ethernet\nKpiCalculation" as ethKpis #White
participant "p1Harmonize\nTemperature" as harmTemp #White
participant "p1Default\nValueTreatment" as defaultValues

requestor -> cur: {{parameters},\n{rawCC}}
activate cur #LightCyan

  note over cur #LightCyan
    Create resultCC from rawCC
  end note



  note over aiCC #LightCoral
    Proceeding:
      - Explicitly (in detail) represent resultCC in variable.yaml
      - Create sub-folders in /p1CreateResultCc for required sub-functions (even if category is white)
        - add readme file with overview chapter describing purpose of sub-function
        - add interface.yaml with input/output description
        - if category=white set output value by enum with one value or min=max for int
      - Add entries in processing section of interface.yaml
        - Reference ("from [/create-result-cc/result-cc/...]") at input
      - Identify source of value in variable.yaml ("from {$p1ComputePhysicalLag.output#/...}")
      until all required attributes are covered
  end note



  loop for all AirInterfaces in resultCC

    cur -> prepTxModes : {[performanceDataList],\n[transmissionModeList]}
    activate prepTxModes

      loop for all entries of [performanceDataList]
        loop for all entries in [timeXStatesList]
          note over prepTxModes
            IF time > 0
              THEN add transmissionMode to
                   [usedTransmissionModesList]
              ELSE delete transmissionMode 
                    from [timeXStatesList]
          end note
        end loop
      end loop

      loop for all entries of [transmissionModeList]

        note over prepTxModes
          IF transmissionMode NOT IN 
              [usedTransmissionModesList]
            THEN 
              - Delete transmissionMode
                from [transmissionModeList]
            ELSE
              - Complement entry in
                [transmissionModeList]
                with AirInterfaceCapacity
        end note

        prepTxModes -> aiCC : {channelBandwidth,\nsymbolRateReductionFactor,\nnumberOfStatesInModulation,\ncodeRate}
        activate aiCC #LightCyan
          note over aiCC
            Calculate AirInterfaceCapacity
            according to ONF TR-532 v2.0 Chapter 6.5
          end note
        prepTxModes <-- aiCC: {airInterfaceCapacity}
        deactivate aiCC

      end loop

    cur <-- prepTxModes : {[performanceDataList],\n[transmissionModeList]}
    deactivate prepTxModes

    ' ----- Link ID --------------------------
    note over cur
      Add linkId to resultCC
    end note

    ' ----- Aggregation Group --------------------------
    note over cur
      Add list of parallel LTPs
    end note

    ' ----- mostRecentPeriodEndTime --------------------------
    note over cur
      Add mostRecentPeriodEndTime
      to resultCC
    end note

    note over cur
      Add mostRecentPeriodEndTime24
      to resultCC
    end note

  ' ----- OutOfRange TxLevel --------------------------
  note over cur #LightGray
    Delete attributes with 
    values outside range
  end note

  cur -> outOfRange: {{resultCC}}
  activate outOfRange #LightGray
  cur <-- outOfRange
  deactivate outOfRange

 end

  loop for all EthernetContainers in resultCC

    ' ----- EthContainer KPIs --------------------------
    note over cur #White
      Add EthernetContainer KPIs
    end note
    
    cur -> ethKpis: {{rawCC}}
    activate ethKpis #LightBlue
    cur <-- ethKpis: {computed EthernetContainer KPIs}
    deactivate ethKpis

  end

  ' ----- Temperature --------------------------
  note over cur #White
    Derive IDU temperature by
    device type specific method
  end note

  cur -> harmTemp: {{resultCC}}
  activate harmTemp #LightBlue
  cur <-- harmTemp
  deactivate harmTemp

  ' ----- ONF default values --------------------------
  note over cur #LightGray
    Delete attributes with 
    ONF default values
  end note

  cur -> defaultValues: {{resultCC}}
  activate defaultValues #LightGray
  cur <-- defaultValues
  deactivate defaultValues

requestor <-- cur: {{resultCC}}

deactivate cur

