openapi: 3.0.0
info:
  title: p1ProvideListOfInterfacesToBeProcessed
  version: 1.0.0




# to be written




x-javascript-interface:
  p1ProvideListOfInterfacesToBeProcessed:
    summary: 'Creates DataStructureForProcessing and triggers the Functions that are processing the PM data provisioning'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - attribute-value-changed-notification
            properties:
              attribute-value-changed-notification:
                type: object
                required:
                  - counter
                  - timestamp
                  - object-path
                  - attribute-name
                  - new-value
                properties:
                  counter:
                    type: integer
                    description: 'Sequence number of callbacks sent through this forwarding'
                  timestamp:
                    type: string
                    description: 'Time when the callback is send'
                  object-path:
                    type: string
                    description: 'Path (cache path as available at the MWDI API) to the object that holds the attribute that changed its value'
                  attribute-name:
                    type: string
                    description: 'Name of the attribute that changed its value'
                  new-value:
                    type: string
                    description: 'New value of the attribute'
            example:
              attribute-value-changed-notification:
                counter: 132
                timestamp: '2010-11-20T14:00:00+01:00'
                object-path: '/core-model-1-4:network-control-domain=cache/control-construct=513250009/logical-termination-point=RF-2146697857/layer-protocol=2146697857/air-interface-2-0:air-interface-pac/air-interface-historical-performances'
                attribute-name: 'time-of-latest-change'
                new-value: '2010-11-20T13:59:00+01:00'
    output:
      success:
        description: 'PM data processed, sent and stored'
      error:
        description: 'just for preventing an error in VSCode'
        # todo: description potentially to be deleted; behavior in case of errors to be described
    processing:
      CreatingDsfp:
        url: #[dpmdpIpAddress]:[dpmdpPort]
          description: >
            'In case of relevant notification, this processingOrchestrator creates a DataStructureForProcessing object and fills it with notification information
            The notification is irrelevant IF:
            - NOT(object-path.contains((air-interface-historical-performances) OR (ethernet-container-historical-performances)) AND (attribute-name==time-of-latest-change))
            - its object-path and attribute-name point to the correct attribute, but within the timeframe configured in integerProfile waitingTimeForProcessingNotificationsForSameDevice
              another notification about a historical-performances/time-of-latest-change update has already been received and processed'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-structure-for-processing:
                        type: object
                        properties:
                          counter:
                            type: string
                            description: >
                              'counter from the initial notification
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/counter}'
                          timestamp:
                            type: string
                            description: >
                              'timestamp from the initial notification
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/timestamp}'
                          object-path:
                            type: string
                            description: >
                              'objectPath from the initial notification
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/object-path}'
                          attribute-name:
                            type: string
                            description: >
                              'attributeName from the initial notification
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/attribute-name}'
                          new-value:
                            type: string
                            description: >
                              'newValue from the initial notification
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/new-value}'
                          mount-name:
                            type: string
                            description: >
                              'The mount-name of the device, extracted
                              from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/object-path}'
                          device-type:
                            type: string
                            description: >
                              'deviceType as derived from MWDI, will be set by callback {ReadingOfDeviceTypeFromMwdiForDsfpObject}'
                          processing:
                            type: array
                            description: >
                              'This array holds the names of the internal functions and their response-codes which will be executing during this function execution.
                              Each of the subsequent callbacks, for which an internal p1-function is executed, shall add the function-name and the response-code to the list'
                            items:
                              type: object
                              required:
                                - function-name
                                - response-code
                              properties:
                                function-name:
                                  type: string
                                  description: 'functionName of the ProcessingFunction'
                                response-code:
                                  type: integer
                                  description: 'responseCode that resulted from executing the ProcessingFunction'
                              example:
                                - function-name: 'p1CreateDsfpOutputObjectFromCache'
                                  response-code: 200
                                - function-name: 'p1SetOutOfRangeLevelValuesToDefault'
                                  response-code: 204
                                - function-name: 'p1Inquire15minAirInterfaceKpisFromCaca'
                                  response-code: 204
                                - function-name: 'p1Inquire15minEthernetContainerKpisFromCaca'
                                  response-code: 204
                                - function-name: 'p1ReplaceOnfDefaultValues'
                                  response-code: 204
                                - function-name: 'p1SetMostRecentTimestampAndDatavInDeviceTable'
                                  response-code: 500
                          output:
                            type: object
                            description: >
                              'The output object generated from processed ControlConstruct data. Intially null, will be set and modified in subsequent steps.'
            responses:
              success:
                description: '[/data-structure-for-processing] object created'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      ReadingOfDeviceTypeFromMwdiForDsfpObject:
        url: #[/core-model-1-4:control-construct/logical-termination-point=dpmdp-1-0-0-tcp-c-mwdi-2-0-1-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]://[/core-model-1-4:control-construct/logical-termination-point=dpmdp-1-0-0-tcp-c-mwdi-2-0-1-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name or /core-model-1-4:control-construct/logical-termination-point=dpmdp-1-0-0-tcp-c-mwdi-2-0-1-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]:[/core-model-1-4:control-construct/logical-termination-point=dpmdp-1-0-0-tcp-c-mwdi-2-0-1-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port][/core-model-1-4:control-construct/logical-termination-point=dpmdp-1-0-0-op-c-is-mwdi-2-0-1-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
          description: >
            'The deviceType obtained here is to be set in the data-structure-processing object created by callback {CreatingDsfp}'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      mount-name-list:
                        type: array
                        description: >
                          'The mount-name-list is filled with a single mount-name
                          from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/object-path} extract the mount-name'
                        items:
                          type: string
            responses:
              success:
                description: 'Only relevant attributes listed'
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        device-status-metadata:
                          type: array
                          items:
                            type: object
                            properties:
                              device-type:
                                type: string
                                description: >
                                  'The device-type as provided by MWDI. If not available in MWDI return: unknown'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      #TODO: change all functions + function calls to use requestBody/responseBody (no dataHandle)
      CreatingDsfpOutput:
        url: #[dpmdpIpAddress]:[dpmdpPort][/p1/create-dsfp-output-object-from-cache-data]
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      mount-name:
                        type: string
                        example: '513250010'
                        description: > 
                          'The mount-name of the device that is addressed by this function
                          from {request.body#object-path} extract the mount-name, which is the ID following the control-construct= part'
            responses:
              success:
                description: 'DataStructureForProcessing output object containing new 15min PM data'
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        data-handle:
                          type: string
                          example: '513250010-2024-03-06T13:00:00+01:00-a0893b37'
                          description: >
                            'This id is used to uniquely identify the output object in the DPMDP memory.'
                        output:
                          type: object
                          description: 'Output - see T1out_Output.yaml, starting at properties keyword'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      ReplacingOutOfRangeLevelValues:
        url: #[dpmdpIpAddress]:[dpmdpPort][/p1/set-out-of-range-level-values-to-default]
          description: >
            'This callback reads the DsfpOutput data from memory and writes changes also directly back into this DsfpOutput object'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-handle:
                        type: string
                        description: >
                          'The function will read the DsfpOutput data associated with this dataHandle directly from memory as input'
            responses:
              success:
                description: 'Out-of-range level values set to defaults in [/data-structure-for-processing/output]'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      InquiringAirIfKpis:
        url: #[dpmdpIpAddress]:[dpmdpPort][/p1/inquire-15min-air-interface-kpis-from-caca]
          description: >
            'This callback reads the DsfpOutput data from memory and writes changes also directly back into this DsfpOutput object'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-handle:
                        type: string
                        description: >
                          'The function will read the DsfpOutput data associated with this dataHandle directly from memory as input'
            responses:
              success:
                description: 'AirInterface capacity KPIs written to [/data-structure-for-processing/output]'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      InquiringEthernetContainerKpis:
        url: #[dpmdpIpAddress]:[dpmdpPort][/p1/inquire-15min-ethernet-container-kpis-from-caca]
          description: >
            'This callback reads the DsfpOutput data from memory and writes changes also directly back into this DsfpOutput object'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-handle:
                        type: string
                        description: >
                          'The function will read the DsfpOutput data associated with this dataHandle directly from memory as input'
            responses:
              success:
                description: 'EthernetContainer KPIs written to [/data-structure-for-processing/output]'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      CallingReplaceOnfDefaultValuesFunction:
        url: #[dpmdpIpAddress]:[dpmdpPort][/p1/replace-onf-default-values]
          description: >
            'This callback reads the DsfpOutput data from memory and writes changes also directly back into this DsfpOutput object'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-handle:
                        type: string
                        description: >
                          'The function will read the DsfpOutput data associated with this dataHandle directly from memory as input'
            responses:
              success:
                description: 'ONF default values replaced in [/data-structure-for-processing/output]'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      SettingMostRecentTimestampsAndDatavInDeviceTable:
        url: #[dmpdpIpAddress]:[dpmdpPort][/p1/set-most-recent-timestamp-and-datav-in-device-table]
          description: >
            'This callback reads the DsfpOutput data from memory, gathers the mostRecentTimestamp and number of records/date per mountname/interface information and writes it into the DMPDP deviceTable'
          post:
            requestBody:
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data-handle:
                        type: string
                        description: >
                          'The function will read the DsfpOutput data associated with this dataHandle directly from memory as input'
            responses:
              success:
                description: 'MostRecentTimestamps written to DMDP deviceTable.'
              error:
                description: 'just for preventing an error in VSCode'
                # todo: description potentially to be deleted; behavior in case of errors to be described
      #UpdatingProcessorControllerDataStore
      #ProvisioningOf15minPmDataToKafka

paths:
  /:
    description: 'no rest path provided by this module'
