@startuml p2IterateEcPmSlices
skinparam responseMessageBelowArrow true

title
  p2IterateEcPmSlices
end title

participant "p2CreateResultCc\n" as cur

participant "p2IterateEcPmSlices\n" as iterateSlices
participant "p1Calculate\nEthernetKpis" as intCC
participant "p1Remove\nDefaultValues" as p1RemDefault
participant "p2Calculate\nUtilization" as p2CalcUtil
participant "p1CategorizeDataVolume\n" as p1CatDataVo
participant "p1CalculateBusyHour\nPerformanceIndicators" as p1CalcBH

cur -> iterateSlices : { parameters,\n[historicalPerformanceDataList],\n{aggregationGroup},\n{resultCc},\n{interfaceStatus},\nuuidOfEthernetContainer }
activate iterateSlices

  loop FOR [historicalPerformanceDataList]   (15min slices to be processed first)

    iterateSlices -> intCC : { {performance-data} }
    activate intCC
      note over intCC
        Adds Ethernet KPIs
      end note
    iterateSlices <-- intCC: { {performance-data} }
    deactivate intCC

    iterateSlices -> p1RemDefault : { {/parameters/sub-function=p1RemoveDefaultValues},\n{performance-data} }
    activate p1RemDefault
      note over p1RemDefault
        Deletes default values
      end note
    iterateSlices <-- p1RemDefault: { {performance-data} }
    deactivate p1RemDefault

    note left iterateSlices #Orange
      Please note:
      {performance-data} and
      {historical-performance-data}
      pass two slightly different
      sub-objects of
      [historical-performance-data-list].
    end note


    iterateSlices -> p2CalcUtil : { {historical-performance-data},\n{aggregation-group},\n{result-cc},\nuuidOfEthernetContainer }
    activate p2CalcUtil
      note over p2CalcUtil
        Adds utilization
      end note
    iterateSlices <-- p2CalcUtil: { {historical-performance-data} }
    deactivate p2CalcUtil

    note over iterateSlices
      IF granularityPeriod == 15-MIN
    end note

    note right iterateSlices
      THEN
    end note

    iterateSlices -> p1CatDataVo : { {historical-performance-data},\n{interfaceStatus} }
    activate p1CatDataVo
      note over p1CatDataVo
        Categorizes PM data
        by day and hour
      end note
    iterateSlices <-- p1CatDataVo: { {interfaceStatus} }
    deactivate p1CatDataVo

    note over iterateSlices
      IF granularityPeriod == 24-HOURS
    end note

    note right iterateSlices
      THEN
    end note

    iterateSlices -> p1CalcBH : { {historical-performance-data},\n{interfaceStatus} }
    activate p1CalcBH
      note over p1CalcBH
        Adds BusyHourKPIs
      end note
    iterateSlices <-- p1CalcBH: { {historical-performance-data} }
    deactivate p1CalcBH

  end loop

cur <-- iterateSlices : { [historicalPerformanceDataList],\n{interfaceStatus} }
deactivate iterateSlices

deactivate cur

@enduml
