openapi: 3.0.0
info:
  title: p1Storing
  version: 1.0.0

# TODO: during maintainance, devices are locked to prevent writing while maintaining
#      storing spec doesn't include/mention lock...

x-javascript-interface:
  p1Storing:
    summary: 'Stores the resultCc in the dataStore and updates dataStore interface information.'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - data-store-es-client
              - result-cc
              - interface-metadata-list
            properties:
              data-store-es-client:
                type: object
                description: >
                  'DataStore ElasticSearch address'
              result-cc:
                type: object
                description: >
                  'The resultCc to be stored'
              interface-metadata-list:
                type: object
                description: >
                  'interfaceMetadataList'
    output:
      success:
        description: 'resultCc stored'
      error:
        description: 'resultCc could not be stored'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'dataStoreEsClient not provided'
                - 'dataStoreEsClient invalid'
                - 'resultCc not provided'
                - 'resultCc invalid'
                - 'interfaceMetadataList not provided'
                - 'interfaceMetadataList invalid'
                - 'resultCc could not be stored'
                - 'interfaceMetadataList could not be stored'
                - 'General processing error'
    processing:
      storeInterfaceMetadataList:
        url:  # [{/storing/data-store-url}][/data-store/device={/storing/mount-name}/interface-metadata-list]
        input:
          required: true
          content:
            application/json:
              schema:
                type: array
                x-key: uuid
                description: >
                  'Performs a bare write operation on the entire interfaceMetadataList as a block
                  interfaceMetadataList of existing devices is overwritten, interfaceMetadataList of non-existing mountName is created
                  from [/storing/interface-metadata-list]'
        output:
          success:
            description: 'interfaceMetadataList stored'
          error:
            description: 'interfaceMetadataList could not be stored'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'dataStoreUrl not provided'
                    - 'dataStoreUrl invalid'
                    - 'mountName not provided'
                    - 'interfaceMetadataList not provided'
                    - 'interfaceMetadataList invalid'
                    - 'Writing to dataStore failed'
                    - 'General processing error'
      storeResultCc:
        url:  # [{/storing/data-store-url}][/data-store/device={/storing/mount-name}/batch={/storing/batch-timestamp}]
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: >
                  'Writes the entire batch as a block
                  assuming that the value of the batchTimestamp is always unique, a new entry is created with every storing operation
                  from [/storing/batch]'
        output:
          success:
            description: 'resultCc stored'
          error:
            description: 'resultCc could not be stored'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'batchTimestamp not provided'
                    - 'batchTimestamp invalid'
                    - 'resultCc not provided'
                    - 'Writing to dataStore failed'
                    - 'General processing error'

paths:
  /:
    description: 'no rest path provided by this module'
