@startuml p1Storing
skinparam responseMessageBelowArrow true

title
  p1Storing
end title

participant "p1ProcessDevice\n" as requestor
participant "p1Storing\n" as cur
database "DataStore" as ds


requestor -> cur : { {dataStoreEsClient},\n{resultCc},\n{interfaceMetadataList} }
activate cur

  note over cur
    storeInterfaceMetadataList
  end note
  cur -> ds: { [interface-metadata-list] }
  cur <-- ds

  note over cur
    storeResultCc
  end note
  cur -> ds: { {batch} }
  cur <-- ds

requestor <-- cur

deactivate cur

@enduml
