openapi: 3.0.0
info:
  title: p1LoadRawCc
  version: 1.0.0

# was ist anders?
# - applyFilteringForRelevantPmData entfällt
# - es wird nur noch p1DiscardIrrelevantPmRecords auf jedes layerProtocol angewandt
#   - es wird nicht geprüft, ob das layerProtocol AirInterface oder EthernetContainer ist (p1Discard ist das sowieso egal)
#   - layerProtocols ohne PM-Daten bleiben einfach wie sie sind (die werden einfach beim output erzeugen ignoriert
#     (da wird explizit auf AirLayer + EthContainer Bezug genommen) und stehen im Schema auch nicht explizit drin)
#   - beim Discard wird jeweils die Original-PM-Liste durch die bereinigte Liste ersetzt


x-javascript-interface:
  p1LoadRawCc:
    summary: 'Reads device ControlConstruct from MWDI ES replica, applies filtering and returns the remaining data to the caller'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - mount-name
              - parameters
              - mwdi-replica-es-client
              - data-store-es-client
            properties:
              mount-name:
                type: string
                description: 'The mount-name of the device for which ControlConstruct data shall be read'
                mount-name: '100250001'
              parameters:
                type: object
                description: 'Hierarchical object holding the parameter settings'
              mwdi-replica-es-client:
                type: object
                description: 'MWDI Replica ElasticSearch address'
              data-store-es-client:
                type: object
                description: 'Data Store ElasticSearch address'
    output:
      success:
        description: 'Raw CC data loaded'
        content:
          application/json:
            schema:
              type: object
              required:
                - raw-cc
              properties:
                raw-cc:
                  type: object
                  description: >
                    'RawCc read from Replica ES, but reduced by irrelevant data
                    from [/load-raw-cc/raw-cc]'
      error:
        description: 'Raw CC could not be loaded'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'Data structure is missing or invalid'
                - 'General processing error'
    processing:
      readControlConstructFromEs:
        url: # [{/load-raw-cc/mwdi-replica-url}][/control-construct={/load-raw-cc/mount-name}]
          output:
            success:
              description: 'Raw ControlConstruct data read'
              content:
                application/json:
                  schema:
                    description: >
                      'The data format follows ONF schema (but in MWDI core-model-1-4:control-construct is an array).
                      As format follows MWDI, the schema is not explicitly stated here.'
                    required:
                      - core-model-1-4:control-construct
                    properties:
                      core-model-1-4:control-construct:
                        type: array
                        x-key: uuid
                        items:
                          type: object
            error:
              description: 'Data structure could not be read from ElasticSearch'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'Data structure is missing or invalid'
                      - 'ElasticSearch read error'
                      - 'General processing error during reading'
      p1FieldsFilter:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - data-structure
                  - fields-filter-string
                properties:
                  data-structure:
                    type: object
                    description: >
                      'The data structure to be filtered according to the provided fields filter string. It is the raw ControlConstruct content (the object found in the first array element of core-model-1-4:control-construct, without the core-model-1-4:control-construct keyword itself)
                      from [/load-raw-cc/raw-cc]'
                  fields-filter-string:
                    type: string
                    description: >
                      'Fields filter string following NETCONF FieldsFilter syntax and semantics to be applied to the data structure,
                      from [/load-raw-cc/fields-filter]'
        output:
          success:
            description: 'Data structure successfully filtered according to the provided fields filter string'
            content:
              application/json:
                schema:
                  type: object
                properties:
                  filtered-data-structure:
                    type: object
                    description: 'The data structure after filtering according to the provided fields filter string'
          error:
            description: 'Data structure could not be filtered according to the provided fields filter string'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'Data structure is missing or invalid'
                    - 'Invalid fields filter string syntax'
                    - 'General processing error during filtering'
      retrieveMostRecentPeriodEndTimesFromDs:
        url: # [{/load-raw-cc/data-store-url}][/data-store/device={/load-raw-cc/mount-name}/interface]
          description: 'Reads the timestamps of the most recent 15min and 24h PM data records of all interfaces.'
          output:
            success:
              description: 'List of mostRecentPeriodEndTimes provided'
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      interface:
                        type: array
                        x-key: uuid
                        items:
                          type: object
                          properties:
                            uuid:
                              type: string
                            layer-protocol-name:
                              type: string
                            most-recent-period-end-time:
                              type: string
                              description: 'The newest seen periodEndTime for this interface in 15min data'
                            most-recent-period-end-time-24:
                              type: string
                              description: 'The newest seen periodEndTime for this interface in 24h data'
                        example:
                          interface:
                            - uuid: 'RF-819.1.1'
                              layer-protocol-name: 'air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER'
                              most-recent-period-end-time: '2025-11-19T18:33:43.813+01:00'
                              most-recent-period-end-time-24: '2025-11-19T02:33:43.813+01:00'
                            - uuid: 'ETH-785.1.5'
                              layer-protocol-name: 'ethernet-container-2-0:LAYER_PROTOCOL_NAME_TYPE_ETHERNET_CONTAINER_LAYER'
                              most-recent-period-end-time: '2025-11-18T00:00:01+01:00'
                              most-recent-period-end-time-24: '2025-11-18T23:33:43.813+01:00'
            error:
              description: 'MostRecentPeriodEndTimes could not be provided'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'ElasticSearch read error'
                      - 'General processing error'
        p1DiscardIrrelevantPmRecords:
          url: #[p1DiscardIrrelevantPmRecords]
          description: >
            'Called for every layerProtocol separately
            from [/load-raw-cc/raw-cc/layer-protocol/<interface-pac>/<interface>-historical-performances/historical-performance-data-list]'
          input:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    historical-performance-data-list:
                      type: array
                      items:
                        type: object
                        properties:
                          granularity-period:
                            type: string
                            description: 'Indicates the granularity of the PM record'
                          period-end-time:
                            type: string
                            description: 'The timestamp of this PM data record'
                          performance-data:
                            type: object
                            description: 'The object containing actual PM data'
                      description: 'The list of historical PM records, that shall be filtered'
                    most-recent-period-end-time:
                      type: string
                      description: >
                        'The (optional) timestamp for filtering 15min PM records. If not provided any 15min records are treated as newer
                        from [/load-raw-cc/interface={uuid}/most-recent-period-end-time]'
                    most-recent-period-end-time-24:
                      type: string
                      description: >
                        'The (optional) timestamp for filtering 24h PM records. If not provided a 24h record is treated as newer
                        from [/load-raw-cc/interface={uuid}/most-recent-period-end-time-24]'
                    relevant-granularities:
                      type: string
                      description: >
                        'This parameter is a regex pattern, that indicates which granularity periods are relevant
                        from [/load-raw-cc/relevant-granularities]'
          output:
            success:
              description: 'Filtered historicalPerformanceDataList provided'
              content:
                application/json:
                  schema:
                    type: object
                    required:
                      - historical-performance-data-list
                    properties:
                      historical-performance-data-list:
                        type: array
                        description: >
                          'The filtered historicalPerformanceDataList, which only contains new records for relevant granularities.
                          If no data remains for this interface instance after filtering, an empty array is returned.'
                        items:
                          type: object
                          properties:
                            granularity-period:
                              type: string
                            period-end-time:
                              type: string
                            performance-data:
                              type: object
            error:
              description: 'Filtered historicalPerformanceDataList could not be provided'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'Input object incomplete or invalid'
                      - 'Input parameters missing or invalid'
                      - 'General processing error during filtering'

paths:
  /:
    description: 'no rest path provided by this module'
