@startuml 00y_NotificationPollingFromKafkaAndProcessing
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCausesSubscribingForAttributeValueChangeNotificationsAtKafka
PromptForEmbeddingCausesCyclicNotificationPollingAndProcessing
end title


participant "RO" as ro
participant "dpmdp://v1/embed-yourself" as dpmdp
participant "KafkaMessageBroker: \n<i>AttributeValueChangeNotifications</i> topic" as kafka
participant "call \n<i>DPMDP://v1/regard-attribute-value-change </i>\nvia javascript interface" as regard


ro -> dpmdp
activate dpmdp

== subscribe at Kafka ==
note over dpmdp
<u>SubscribeForAttributeValueChangeNotifications</u>
  subscribe at Kafka topic with
  topicName=<i>mwdi_avc_notifications</i>
end note
dpmdp -> kafka: {topicName, brokerId, groupId, clientId} (apiKeyAuth)

== cycically poll new notifications and process them ==
note over dpmdp #LightPink
  Only poll notifications from Kafka
  while profileInstance
  <i>kafkaNotificationConsumptionSwitch</i> == "on",
  when set to "off" no polling to be executed
end note

note over dpmdp
<u>attributeValueChangeNotificationPolling</u>
  Continuously poll all new notifications from Kafka.
end note
dpmdp -> kafka: {pollWaitingTime=0}
kafka -> dpmdp: {consumerRecords = list-of(partition, offset, attributeValueChangeNotification)}

note over dpmdp
<u>IdentifyAndProcessDeviceChangeAndAlarmNotifications</u>
  For each notification call the processing funcationality
  via javascript interface.
end note
dpmdp -> regard: {device-attribute-value-change-notification}

deactivate dpmdp


@enduml