@startuml p1ProcessDevice
skinparam responseMessageBelowArrow true

title
  p1ProcessDevice
end title

participant "p1StreamPmData\n" as requestor
participant "p1ProcessDevice\n" as p1ProOrch #LightCyan
participant "p1LoadRawCc\n" as p1AddRaw #LightCyan
participant "p1CreateResultCc\n" as p1CRC #LightCyan
participant "p1Formatting\nOutputApt" as p1Output #LightCyan
participant "p1Transmitting\nKafka" as p1Trans #LightCyan
participant "p1Storing\n" as p1Store #LightCyan


requestor -> p1ProOrch : { mountName,\n{parameters},\n{configFile},\n{mwdiReplicaEsClient},\n{dataStoreEsClient} }
activate p1ProOrch #LightCyan

  p1ProOrch -> p1AddRaw : { mountName,\n{/parameters/sub-function=loadRawCc},\n{mwdiReplicaEsClient},\n{dataStoreEsClient} }
  activate p1AddRaw #LightCyan

    note over p1AddRaw
      - Loads rawCc from MWDI ES
      - Reduces structure of rawCc
      - Deletess PM data that has
        already been processed in past
    end note

  p1ProOrch <-- p1AddRaw : { {rawCc} }
  deactivate p1AddRaw

  p1ProOrch -> p1CRC : { {/parameters/sub-function=createResultCc},\n{rawCc} }
  activate p1CRC #LightCyan

    note over p1CRC
      - Creates resultCc from rawCc
      - Processes and complements PM data
    end note

  p1ProOrch <-- p1CRC :  { {resultCc},\n{interfaceMetadataList} }
  deactivate p1CRC

  p1ProOrch -> p1Output : { {resultCc} }
  activate p1Output #LightCyan

    note over p1Output
      Creates aptOutputFormat
      from resultCc
    end note

  p1ProOrch <-- p1Output : { {aptOutputFormat} }
  deactivate p1Output

  loop FOR all [kafkaTransmitter]

    p1ProOrch -> p1Trans : { {/parameters/sub-function=p1TransmittingKafka},\n{configFile},\n[outputFormat],\nkafkaTransmitter[n] }
    activate p1Trans #LightCyan

      note over p1Trans
        Transmits object
        to Kafka
      end note

    p1ProOrch <-- p1Trans
    deactivate p1Trans

  end loop

  p1ProOrch -> p1Store : { {dataStoreEsClient},\n{resultCc},\n{interfaceMetadataList} }
  activate p1Store #LightCyan

    note over p1Store
      Stores resultCc
    end note

  p1ProOrch <-- p1Store
  deactivate p1Store

deactivate p1ProOrch

@enduml
