@startuml p1ProcessDevice
skinparam responseMessageBelowArrow true

title
  p1ProcessDevice
end title

participant "p1StreamPmData\n" as requestor
participant "p1ProcessDevice\n" as p1ProOrch
participant "p1LoadRawCc\n" as p1AddRaw
participant "p1CreateResultCc\n" as p1CRC
participant "p1Formatting\nOutputApt" as p1OutputApt
participant "p1Formatting\nOutputOnf" as p1OutputOnf
participant "p1Transmitting\nKafka" as p1Trans
participant "p1Storing\n" as p1Store


requestor -> p1ProOrch : { mountName,\n{parameters},\n{configFile},\n{mwdiReplicaEsClient},\n{dataStoreEsClient} }
activate p1ProOrch

  p1ProOrch -> p1AddRaw : { mountName,\n{/parameters/sub-function=loadRawCc},\n{mwdiReplicaEsClient},\n{dataStoreEsClient} }
  activate p1AddRaw

    note over p1AddRaw
      - Loads rawCc from MWDI ES
      - Reduces structure of rawCc
      - Deletes PM data that has
        already been processed in past
    end note

  p1ProOrch <-- p1AddRaw : { {rawCc} }
  deactivate p1AddRaw

  p1ProOrch -> p1CRC : { {/parameters/sub-function=createResultCc},\n{rawCc} }
  activate p1CRC

    note over p1CRC
      - Creates resultCc from rawCc
      - Processes and complements PM data
    end note

  p1ProOrch <-- p1CRC :  { {resultCc},\n{interfaceMetadataList} }
  deactivate p1CRC

  p1ProOrch -> p1OutputApt : { {resultCc} }
  activate p1OutputApt

    note over p1OutputApt
      Creates aptOutputFormat
      from resultCc
    end note

  p1ProOrch <-- p1OutputApt : { formatName,\n{outputFormat} }
  deactivate p1OutputApt

  p1ProOrch -> p1OutputOnf : { {resultCc} }
  activate p1OutputOnf

    note over p1OutputOnf
      Creates onfOutputFormat
      from resultCc
    end note

  p1ProOrch <-- p1OutputOnf : { formatName,\n{outputFormat} }
  deactivate p1OutputOnf

  p1ProOrch -> p1Trans : { {/parameters/sub-function=p1TransmittingKafka},\n{configFile},\n[outputFormat] }
  activate p1Trans

    note over p1Trans
      Transmits object
      to Kafka
    end note

  p1ProOrch <-- p1Trans
  deactivate p1Trans

  p1ProOrch -> p1Store : { {dataStoreEsClient},\n{resultCc},\n{interfaceMetadataList} }
  activate p1Store

    note over p1Store
      Stores resultCc
    end note

  p1ProOrch <-- p1Store
  deactivate p1Store

deactivate p1ProOrch

@enduml
