@startuml p2IterateAiPmSlices
skinparam responseMessageBelowArrow true

title
  p2IterateAiPmSlices
end title

participant "p2CreateResultCc\n" as cur

participant "p2IterateAi\nPmSlices" as iterateSlices
participant "p1Calculate\nIntervalCapacity" as intCC
participant "p1RemoveOutOf\nRangeLevels" as p1RORL
participant "p1Remove\nDefaultValues" as p1RemDefault


cur -> iterateSlices : { parameters,\n[historicalPerformanceDataList],\n[transmissionModeList] }
activate iterateSlices

  loop FOR [historicalPerformanceDataList]   (15min slices to be processed first)

    iterateSlices -> intCC : { [time-xstates-list],\n[transmission-mode-list] }
    activate intCC
      note over intCC
        Calculates intervalCapacity
      end note
    iterateSlices <-- intCC: { intervalCapacity }
    deactivate intCC

    iterateSlices -> p1RORL : { {/parameters/sub-function=p1RemoveOutOfRangeLevels},\n{historical-performance-data} }
    activate p1RORL
      note over p1RORL
        Deletes TX and RX levels
        outside pre-defined range
      end note
    iterateSlices <-- p1RORL: { historical-performance-data }
    deactivate p1RORL

    iterateSlices -> p1RemDefault : { {/parameters/sub-function=p1RemoveDefaultValues},\n{historical-performance-data} }
    activate p1RemDefault
      note over p1RemDefault
        Deletes default values
      end note
    iterateSlices <-- p1RemDefault: { historical-performance-data }
    deactivate p1RemDefault

  end loop

cur <-- iterateSlices : { [historicalPerformanceDataList] }
deactivate iterateSlices

deactivate cur

@enduml
