@startuml p1CalculateEthernetKpis
skinparam responseMessageBelowArrow true

title
  p1CalculateEthernetKpis
end title

participant "p1CreateResultCc\n" as requestor #LightGrey
participant "p1Calculate\nEthernetKpis" as ethKpis #LightCyan

requestor -> ethKpis : { [historicalPerformanceDataList] }
activate ethKpis #LightCyan

  loop FOR all [historicalPerformanceDataList]

    note over ethKpis
      Adds transmitTraffic
    end note

    note over ethKpis
      Adds receiveTraffic
    end note

    note over ethKpis
      Adds frameLossInput
    end note

    note over ethKpis
      Adds frameLossOutput
    end note

  end loop

requestor <-- ethKpis : { [historicalPerformanceDataList] }
deactivate ethKpis

deactivate requestor

@enduml
