@startuml p2LoadRawCc
skinparam responseMessageBelowArrow true

title
  p2LoadRawCc
end title

participant "p2ProcessDevice\n" as requestor
participant "p2LoadRawCc\n" as cur
database "MWDI ES Replica" as MwdiEs
participant "p1FieldsFilter\n" as fieldsFilter
participant "p2DiscardIrrelevant\nPmRecords" as filterPm

requestor -> cur: { {parameters},\n{mwdiReplicaEsClient},\nmountName,\n[offsets] }
activate cur

  note over cur
    readControlConstructFromReplica
  end note
  cur -> MwdiEs: { mountName }
  cur <-- MwdiEs: { {rawControlConstruct} }

  cur -> fieldsFilter: { {rawControlConstruct},\nfieldsFilter }
  activate fieldsFilter
    note over fieldsFilter
      Applies FieldsFilter
    end note
  cur <-- fieldsFilter: { {rawControlConstruct} }
  deactivate fieldsFilter

  note over cur
    Initialize interfaceOffsets
    if not existing
  end note

  loop FOR all [/raw-cc/logical-termination-point]

    note over cur
      Initialize offset
      if not existing
    end note

    note over cur
      IF layerProtocolName == AirInterface
    end note

    note right cur
      THEN
    end note

    cur -> filterPm: { [historicalPerformanceDataList],\n{offset} }
    activate filterPm
    note over filterPm
      Discards records that are
      already processed from
      historicalPerformanceDataList
    end note
    cur <-- filterPm: { [filteredHistoricalPerformanceDataList],\n{offset} }
    deactivate filterPm

    note right cur
      addBatchTimestamp
    end note

    note over cur
      IF layerProtocolName == EthernetContainer
    end note

    note right cur
      THEN
    end note

    cur -> filterPm: { [historicalPerformanceDataList],\n{offset} }
    activate filterPm
    note over filterPm
      Discards records that are
      already processed from
      historicalPerformanceDataList
    end note
    cur <-- filterPm: { [filteredHistoricalPerformanceDataList],\n[offset] }
    deactivate filterPm

    note right cur
      updateInterfaceOffset for this interface
      with mostRecentPeriodEndTime and
      mostRecentPeriodEndTime24 in this batch
    end note

  end loop

  note over cur
    updateOffsets for this device
    from interfaceOffsets
  end note

requestor <-- cur: { {rawCc},\n[offsets] }
deactivate cur

@enduml
