openapi: 3.0.0
info:
  title: p1ReplicateMwdiEs
  version: 1.0.0

x-javascript-interface:
  p1ReplicateMwdiEs:
    summary: 'Replicates the MWDI ElasticSearch index'
    input:
    output:
      success:
        description: ''
        # todo: Does the Function return any output data on success? If yes, please define them here.
      error:
        description: ''
        # todo: Does the Function return any output data on failure? If yes, please define them here.
    processing:
      logging:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - cronjob-name
                  - last-replication-timestamp
                  - status-message
                properties:
                  cronjob-name:
                    type: string
                    enum:
                      - 'p1ReplicateMwdiEs'
                    description: 'Name of the cronjob'
                  last-replication-timestamp:
                    type: string
                    pattern: '^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2})((\.[0-9]{1,}){0,1})(Z|[\+\-][0-9]{2}:[0-9]{2})$'
                    description: 'Date and time of the last successful replication of the MWDI ES index'
                  status-message:
                    type: string
                    # todo: add enum values, if reasonable
                    enum:
                      - ''
                    # todo: add some information about the thing upon which the status is documented here
                    description: >
                      '
                      '
      p1LoadParameters:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - function-name
                properties:
                  function-name:
                    type: string
                    enum:
                      - 'p1ReplicateMwdiEs'
                    description: 'Name of the Function whose parameters are to be loaded from the configFile'
        output:
          success:
            description: 'Parameters successfully loaded'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - parameters
                  properties:
                    parameters:
                      type: object
                      description: 'Hierarchical object holding the parameter settings'
                    config-file:
                      type: object
                      description: 'configFile content'
          error:
            description: 'Parameters could not be loaded'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'configFile not found or not accessible'
                    - 'configFile is not valid JSON'
                    - 'configFile does not conform to the expected schema'
                    - 'functionName not found in configFile'
                    - 'unknown error occurred'
      p1ProcessingPmData:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - mount-name
                  - parameters
                  - config-file
                properties:
                  mount-name:
                    type: string
                    description: >
                      'MountName from objectPath in AVC notification sent by MWDI indicating change in timeOfLatestChange
                      from {$request.body#microwave-device-inventory-1-0:attribute-value-changed-notification/object-path}'
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from {$p1LoadParameters.output#/parameters}'
                  config-file:
                    type: object
                    description: 'configFile content'
        output:
          success:
            description: 'PM data processed, sent and stored'
            # todo: Does the Function return any output data on success? If yes, please define them here.
          error:
            description: 'MWDI ElasticSearch index could not be replicated'
            content:
              application/json:
                schema:
                  type: string
                  # todo: add enum values for the errorMessages to be thrown, if reasonable
                  enum:
                    - ''

paths:
  /:
    description: 'no rest path provided by this module'
