@startuml p1ReplicateMwdiEs
skinparam responseMessageBelowArrow true

title
  p1ReplicateMwdiEs
end title

participant "embedYourself\n" as embed
participant "p1ReplicateMwdiEs\n" as p1RMWDI #LightCyan
database "ReplicateMwdiEsLog" as log #LightCyan
participant "p1ProcessingPmData\n" as p1ProOrch #LightCyan

embed -> p1RMWDI
activate p1RMWDI #LightCyan

note over p1RMWDI
  Automatically start
  p1ReplicateMwdiEs
end note

group Cyclically update MWDI ES Replica

  note over p1RMWDI
    Replicate MWDI ES index
  end note

  p1RMWDI -> log
  note over log
    Log the following information:
    - Cronjob name
    - Last replication timestamp
    - Status message
  end note
  
  group Trigger processing of updated CC
    p1RMWDI -> p1ProOrch : {mountName}
    activate p1ProOrch #LightCyan

      note over p1ProOrch
        Process PM data
        of device
      end note

  end

end

@enduml
