openapi: 3.0.0
info:
  title: p1CalculateEthernetKpis
  version: 1.0.0

x-javascript-interface:
  p1CalculateEthernetKpis:
    summary: 'Adds Ethernet KPIs to a historicalPerformanceData set'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - historical-performance-data
            properties:
              historical-performance-data:
                type: array
                description: >
                  'historicalPerformanceData set'
    output:
      success:
        description: 'Ethernet KPIs added'
        content:
          application/json:
            schema:
              type: object
              required:
                - historical-performance-data
              properties:
                historical-performance-data:
                  type: object
                  description: >
                    'historicalPerformanceData
                    from [/calculate-ethernet-kpis/historical-performance-data]'
      error:
        description: 'Ethernet KPIs could not be added'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'historicalPerformanceData not provided'
                - 'historicalPerformanceData incomplete'
                - 'historicalPerformanceData invalid'
                - 'transmitTraffic could not be provided'
                - 'receiveTraffic could not be provided'
                - 'frameLossInput could not be provided'
                - 'frameLossOutput could not be provided'
                - 'general processing error'
    processing:
      calculateTransmitTraffic:
        summary: 'Calculates the averaged transmit traffic in Mbps'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - total-bytes-output
                  - time-period
                properties:
                  total-bytes-output:
                    type: string
                    description: >
                      'totalBytesOutput
                      from [/calculate-ethernet-kpis/historical-performance-data/total-bytes-output]'
                  time-period:
                    type: integer
                    description: >
                      'timePeriod in seconds
                      from [/calculate-ethernet-kpis/historical-performance-data/time-period]'
        output:
          success:
            description: 'transmitTraffic provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - transmit-traffic
                  properties:
                    transmit-traffic:
                      type: integer
                      description: >
                        'Averaged transmit traffic in Mbps
                        from [ {$input#/total-bytes-output} / {$input#/time-period} ]'
        error:
          description: 'transmitTraffic could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'totalBytesOutput not provided'
                  - 'totalBytesOutput invalid'
                  - 'timePeriod not provided'
                  - 'timePeriod invalid'
                  - 'general processing error'
      calculateReceiveTraffic:
        summary: 'Calculates the averaged receive traffic in Mbps'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - total-bytes-input
                  - time-period
                properties:
                  total-bytes-input:
                    type: string
                    description: >
                      'totalBytesInput
                      from [/calculate-ethernet-kpis/historical-performance-data/total-bytes-input]'
                  time-period:
                    type: integer
                    description: >
                      'timePeriod in seconds
                      from [/calculate-ethernet-kpis/historical-performance-data/time-period]'
        output:
          success:
            description: 'receiveTraffic provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - receive-traffic
                  properties:
                    receive-traffic:
                      type: integer
                      description: >
                        'Averaged receive traffic in Mbps
                        from [ {$input#/total-bytes-input} / {$input#/time-period} ]'
        error:
          description: 'receiveTraffic could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'totalBytesInput not provided'
                  - 'totalBytesInput invalid'
                  - 'timePeriod not provided'
                  - 'timePeriod invalid'
                  - 'general processing error'
      calculateFrameLossInput:
        summary: 'Calculates the total frame loss on ingress'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - errored-frames-input
                  - dropped-frames-input
                properties:
                  errored-frames-input:
                    type: integer
                    description: >
                      'erroredFramesInput
                      from [/calculate-ethernet-kpis/historical-performance-data/errored-frames-input]'
                  dropped-frames-input:
                    type: integer
                    description: >
                      'droppedFramesInput
                      from [/calculate-ethernet-kpis/historical-performance-data/dropped-frames-input]'
        output:
          success:
            description: 'Total frameLossInput provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - frame-loss-input
                  properties:
                    frame-loss-input:
                      type: integer
                      description: >
                        'Total frame loss on ingress
                        from [ {$input#/errored-frames-input} + {$input#/dropped-frames-input} ]'
        error:
          description: 'Total frameLossInput could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'erroredFramesInput not provided'
                  - 'erroredFramesInput invalid'
                  - 'droppedFramesInput not provided'
                  - 'droppedFramesInput invalid'
                  - 'general processing error'
      calculateFrameLossOutput:
        summary: 'Calculates the total frame loss on egress'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - errored-frames-output
                  - dropped-frames-output
                properties:
                  errored-frames-output:
                    type: integer
                    description: >
                      'erroredFramesOutput
                      from [/calculate-ethernet-kpis/historical-performance-data/errored-frames-output]'
                  dropped-frames-output:
                    type: integer
                    description: >
                      'droppedFramesOutput
                      from [/calculate-ethernet-kpis/historical-performance-data/dropped-frames-output]'
        output:
          success:
            description: 'Total frameLossOutput provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - frame-loss-output
                  properties:
                    frame-loss-output:
                      type: integer
                      description: >
                        'Total frame loss on egress
                        from [ {$input#/errored-frames-output} + {$input#/dropped-frames-output} ]'
        error:
          description: 'Total frameLossOutput could not be provided'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - 'erroredFramesOutput not provided'
                  - 'erroredFramesOutput invalid'
                  - 'droppedFramesOutput not provided'
                  - 'droppedFramesOutput invalid'
                  - 'general processing error'

paths:
  /:
    description: 'no rest path provided by this module'
