@startuml p1CalculateEthernetKpis
skinparam responseMessageBelowArrow true

title
  p1CalculateEthernetKpis
end title

participant "p2IterateEcPmSlices\n" as requestor
participant "p1CalculateEthernetKpis\n" as ethKpis

requestor -> ethKpis : { historicalPerformanceData }
activate ethKpis

    note over ethKpis
      Adds transmitTraffic
    end note

    note over ethKpis
      Adds receiveTraffic
    end note

    note over ethKpis
      Adds frameLossInput
    end note

    note over ethKpis
      Adds frameLossOutput
    end note

requestor <-- ethKpis : { historicalPerformanceData }
deactivate ethKpis

deactivate requestor

@enduml
