@startuml p1MaintainDevInterfaceInDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1MaintainDevInterfaceInDs
end title

participant "p1MaintainDs" as requestor
participant "p1MaintainDevInterfaceInDs" as cur #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{parameters},\n{configFile},\n{dataStoreEsClient},\nmountName,\n{interfaceInstance},\nretentionPeriod}
activate cur #LightCyan

  note over cur
    <u>DeleteExpiredInterface</u>
      IF ((interfaceInstance.mostRecentPeriodEndTime &&
         interfaceInstance.mostRecentPeriodEndTime24))
         are older than allowed by retentionPeriod
      THEN DELETE the interface instance identified as follows from
        the datastore:
        [/data-store/device=mountName/interface=interfaceInstance.uuid]
  end note
  cur -> ds: {mountName, uuid}
  cur <-- ds

  requestor <-- cur

deactivate cur


@enduml
