openapi: 3.0.0
info:
  title: p1CreateEs
  version: 1.0.0

x-javascript-interface:
  p1CreateEs:
    summary: 'Creates an ElasticSearch instance/index, if it does not already exist.'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - es-client
            properties:
              parameters:
                type: object
                description: >
                  'Hierarchical object holding the parameter settings'
              es-client:
                type: object
                description: >
                  'ElasticSearch interface'
    output:
      success:
        description: 'The ElasticSearch index exists and is ready for use'
      error:
        description: 'The ElasticSearch index could not be verified or created'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'ES not reachable'
                - 'Authentication failure'
                - 'Invalid index settings'
                - 'Index creation error'
                - 'Other error'
    processing:
      headGetRequest:
        description: 'Check if the ElasticSearch index already exists'
        input:
          schema:
            type: object
            required:
              - url
              - apiKey
              - indexName
            properties:
              url:
                type: string
                description: >
                  'ElasticSearch URL
                  from [/create-es/es-url]'
              apiKey:
                type: string
                description: >
                  'ElasticSearch API key
                  from [/create-es/es-api-key]'
              indexName:
                type: string
                description: >
                  'ElasticSearch index of MWDI ES
                  from [/create-es/es-index]'
        output:
          success:
            description: 'The index exists and ElasticSearch responded successfully'
          error:
            description: 'ES does not exist'
            enum:
              - 'ES not reachable'
              - 'Index does not exist'
              - 'Authentication failure'
              - 'Other error'
      put:
        description: 'Create ES if it does not exist'
        input:
          schema:
            required:
              - url
              - apiKey
              - indexName
            properties:
              url:
                type: string
                description: >
                  'ElasticSearch URL
                  from [/create-es/es-url]'
              apiKey:
                type: string
                description: >
                  'ElasticSearch API key
                  from [/create-es/es-api-key]'
              indexName:
                type: string
                description: >
                  'ElasticSearch index of MWDI ES
                  from [/create-es/es-index]'
              ?:
                type: integer
                description: >
                  'Number of shards
                  from '
              ??:
                type: integer
                description: >
                  'Number of replicas
                  from '
              ???:
                type: Array
                description: >
                  'Field types
                  from '
              # todo: all attributes that are needed for creating ES instance/index to be added here
              # include datatype and description for each attribute
              # I will complement the source description afterwards
        output:
          success:
            description: 'The index exists now'
          error:
            description: 'The index could not be created'
            enum:
              - 'ES not reachable'
              - 'Authentication failure'
              - 'Missing privileges'
              - 'Invalid index settings'
              - 'Index creation error'
              - 'Other error'

paths:
  /:
    description: 'no rest path provided by this module'