@startuml p1CreateResultCc
skinparam responseMessageBelowArrow true

title
  p1CreateResultCc
end title

participant "p1CreateResultCc\n" as requestor #LightGrey
participant "p1Calculate\nEthernetKpis" as ethKpis #LightCyan

requestor -> ethKpis : {[historicalPerformanceDataList]}
activate ethKpis #LightCyan

  loop for all entries of [historicalPerformanceDataList]

    note over ethKpis
      Add transmitTraffic
    end note

    note over ethKpis
      Add receiveTraffic
    end note

    note over ethKpis
      Add frameLossInput
    end note

    note over ethKpis
      Add frameLossOutput
    end note

  end loop

requestor <-- ethKpis : {[historicalPerformanceDataList]}
deactivate ethKpis

deactivate requestor

@enduml
