@startuml p1FormattingOutputApt
skinparam responseMessageBelowArrow true

title
p1FormattingOutputApt
end title

participant "requestor\n(e.g. p1ProcessingOrchestratorForHistoricalPm)" as requestor
participant "p1FormattingOutputApt" as cur #LightCyan
participant "p1ComputeAirInterfaceNames" as airIfNames #LightCyan
participant "p1ComputeEthContainerName" as ethName #LightCyan
participant "p1ComputeAirIfLag" as airIfLag #LightCyan


requestor -> cur: {_resultCC, {input}, {parameters}}
activate cur #LightCyan

note over cur #LightCoral
  shall this be specific to DPMDP only?
  in that case no CC data needs to be handed over,
  only a reference
end note


note over cur
  <u>TransformOnfFormatIntoAptOutputFormat</u>
  The input CC data in ONF format is transformed
  into the desired APT output format.
  (Non-key) attributes that cannot be computed due to missing input data
  are to be set to a default (-1 for integers).

  Then the output is enriched with Identifiers
  computed during the next steps.
end note

note over cur
  <u>ComputeIfIdentifiers</u>
  The following IDs have to be computed from
  LTP structure and augment information for each
  AirInterface and EthernetContainer from _resultCC:
  - AirInterface: linkEndpointId (= unitId), linkId, LAG
  - EthContainer: interfaceName (= portName)
end note

loop For each airInterface uuid from output.air-interface-list
  note over cur
    Compute the IDs and LAG for
  end note
  cur -> airIfNames: {_rawCC* | LtpStructureAndAugment, uuid, {input}, {parameters}}
  cur <-- airIfNames: {linkEndpointId, linkId}

  cur -> airIfLag: {_rawCC* | LtpStructureAndAugment, uuid, {input}, {parameters}}
  cur <-- airIfLag: {Lag} 

end loop

loop For each ethernetContainer uuid from output.ethernet-container-list
  note over cur
    Compute the IDs
  end note
  cur -> ethName: {_rawCC* | LtpStructureAndAugment, uuid, {input}, {parameters}}
  cur <-- ethName: {interfaceName}
end note



requestor <-- cur: {output}

deactivate cur

