openapi: 3.0.0
info:
  title: p1IterateAiPmSlices
  version: 1.0.0

x-javascript-interface:
  p1IterateAiPmSlices:
    summary: 'Iterates through all AirInterface historical performance data slices and calls the processing Functions'
    input:
      required: true
      content:
        application/json:
          schema:
            required:
              - parameters
              - historical-performance-data-list
              - transmission-mode-list
            properties:
              parameters:
                type: object
                description: 'Hierarchical object holding the parameter settings'
              historical-performance-data-list:
                type: array
                description: >
                  'historicalPerformanceDataList'
              transmission-mode-list:
                type: array
                description: >
                  'transmissionModeList'
    output:
      success:
        description: 'historicalPerformanceDataList processed'
        content:
          application/json:
            schema:
              type: object
              required:
                - historical-performance-data-list
              properties:
                historical-performance-data-list:
                  type: array
                  description: >
                    'historicalPerformanceDataList
                    from [/iterate-ai-pm-slices/historical-performance-data-list]'
      error:
        description: 'historicalPerformanceDataList could not be processed'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'parameters not provided'
                - 'parameters incomplete'
                - 'parameters invalid'
                - 'historicalPerformanceDataList not provided'
                - 'historicalPerformanceDataList incomplete'
                - 'historicalPerformanceDataList invalid'
                - 'transmissionModeList not provided'
                - 'transmissionModeList incomplete'
                - 'transmissionModeList invalid'
                - 'interval capacity could not be calculated'
                - 'out of range levels could not be removed'
                - 'default values could not be removed'
                - 'historicalPerformanceDataList could not be processed'
                - 'General processing error'
    processing:
      p1CalculateIntervalCapacity:
        summary: 'Calculates the AirInterface capacity weighted by duration of operation of the respective transmission mode in kbps'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - time-xstates-list
                  - transmission-mode-list
                properties:
                  time-xstates-list:
                    type: array
                    description: >
                      'timeXStatesList
                      from [/iterate-ai-pm-slices/historical-performance-data-list=*/performance-data/time-xstates-list]'
                  transmission-mode-list:
                    type: array
                    description: >
                      'transmissionModeList
                      from [/iterate-ai-pm-slices/transmission-mode-list]'
        output:
          success:
            description: 'Interval capacity provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - interval-capacity
                  properties:
                    interval-capacity:
                      type: integer
                      description: >
                        'intervalCapacity'
          error:
            description: 'Interval capacity could not be provided'
            content:
              application/json:
                schema:
                  type: string
      p1RemoveOutOfRangeLevels:
        summary: 'Removes out-of-range level attributes from a performance data slice'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - performance-data
                properties:
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from [/iterate-ai-pm-slices/parameters/sub-function=p1RemoveOutOfRangeLevels]'
                  performance-data:
                    type: object
                    description: >
                      'performanceData set of a single time period
                      from [/iterate-ai-pm-slices/historical-performance-data-list=*/performance-data]'
        output:
          success:
            description: 'Performance data slice cleaned from out-of-range level attributes'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - performance-data
                  properties:
                    performance-data:
                      type: object
                      description: >
                        'performanceData set of a single time period'
          error:
            description: 'Performance data slice could not be cleaned from out-of-range level attributes'
            content:
              application/json:
                schema:
                  type: string
      p1RemoveDefaultValues:
        summary: 'Deletes attributes with default values from the transferred object'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - input-object
                properties:
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from [/iterate-ai-pm-slices/parameters/sub-function=p1RemoveDefaultValues]'
                  input-object:
                    type: object
                    description: >
                      'performanceData set of a single time period
                      from [/iterate-ai-pm-slices/historical-performance-data-list=*/performance-data]'
        output:
          success:
            description: 'Input object cleaned from attributes with default values'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - input-object
                  properties:
                    input-object:
                      type: object
                      description: >
                        'Data object from which attributes with default values have been removed'
          error:
            description: 'Input object could not be cleaned from attributes with default values'
            content:
              application/json:
                schema:
                  type: string

paths:
  /:
    description: 'no rest path provided by this module'
