@startuml 011_p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput
skinparam responseMessageBelowArrow true

title
p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput
end title

participant "requestor" as requestor
participant "p1SetOutOfRangeLevelValuesToDefaultInDsfpOutput" as setLvl #LightBlue
participant "DPMDP\n(internal memory)" as data

activate setLvl

note over requestor
  Requestor can hand over either of the two:
  - dataHandle: this points to the Dsfp.output
    target object directly in the DPMDP memory
  - DsfpOutput.air-interface-list: this is the
    data from air-interface-list

  DPMDP ProcessingOrchestrator shall hand over
  the dataHandle.
  Data will be read directly from DPMDP memory and
  will also be written back directly into DPDMP memory
  (204).

  If the function is to be re-used by another Application,
  this application can hand over a complete set of data and
  will also receive the complete set of data
  (200).
end note
requestor -> setLvl: {dataHandle | DsfpOutput.air-interface-list}

note over setLvl
  In case of dataHandle:
  read data from DPMDP memory
end note
setLvl -> data: {dataHandle}
data --> setLvl: {air-interface-list}

note over setLvl
  <u>ReplaceOutOfRangeValues</u>
  Iterate over all items in air-interface-list.
  
  If out-of-range values for any transmit-level or receive-level attributes are encountered,
  the respective attribute value is set to default (-1):

  IF NOT (transmit-level attribute within range [-30, 40]) THEN replace with -1
  IF NOT (reveive-level attribute within range (-129, -99.9) AND (-99.9, -10)) THEN replace with -1
end note

setLvl --> requestor: {modified DsfpOutput.air-interface-list}

deactivate setLvl