@startuml 013_p1Inquire15minEthernetContainerKpisFromCacaAndSetInDsfpOutput
skinparam responseMessageBelowArrow true

title
p1Inquire15minEthernetContainerKpisFromCacaAndSetInDsfpOutput
end title

participant "requestor" as requestor
participant "p1Inquire15minEthernetContainerKpisFromCacaAndSetInDsfpOutput" as setKpi #LightBlue
participant "CaCa://v1/compute-air-interface-capacity-kpis-for-list-of-air-interfaces" as caca

activate setKpi
requestor -> setKpi: {DsfpOutput.ethernet-container-list}

note over setKpi
<u>GetKpis</u>
  Send relevant data from DsfpOutput.ethernet-container-list to CaCa.
  CaCa will attempt to compute the Ethernet KPIs for every
  EthernetContainer from the list.
  (Where KPI computation failed, CaCa will return -1 as attribute value.)
end note

setKpi -> caca: {DsfpOutput.ethernet-container-list.excerpt}
caca --> setKpi: {computedKpiAttributes}

note over setKpi
<u>SetKpiValues</u>
  in DsfpOutput
  and return the modifiedDsfpOutput.
end note

setKpi --> requestor: {modified DsfpOutput.ethernet-container-list}

deactivate setKpi