@startuml p1PrepareTxModes
skinparam responseMessageBelowArrow true

title
  p1PrepareTxModes
end title

participant "p1CreateResultCc\n" as cur

participant "p1Prepare\nTxModes" as prepTxModes #LightCyan
participant "p1Calculate\nAiCapacity" as aiCC #LightCyan
participant "p1Calculate\nIntervalCapacity" as intCC #LightCyan


cur -> prepTxModes : {[historicalPerformanceDataList],\n[transmissionModeList]}
activate prepTxModes #LightCyan

  loop for all entries of [historicalPerformanceDataList]
    loop for all entries in [timeXStatesList]
      note over prepTxModes
        IF time > 0
          THEN add transmissionMode to
                [usedTransmissionModesList]
          ELSE delete transmissionMode 
                from [timeXStatesList]
      end note
    end loop
  end loop

  loop for all entries of [transmissionModeList]

    note over prepTxModes
      IF transmissionMode NOT IN 
          [usedTransmissionModesList]
        THEN 
          - Delete transmissionMode
            from [transmissionModeList]
        ELSE
          - Complement entry in
            [transmissionModeList]
            with AirInterfaceCapacity
    end note

    prepTxModes -> aiCC : {channelBandwidth,\nsymbolRateReductionFactor,\nnumberOfStatesInModulation,\ncodeRate}
    activate aiCC #LightCyan
      note over aiCC
        Calculate airInterfaceCapacity
        according to ONF TR-532 v2.0 Chapter 6.5
      end note
    prepTxModes <-- aiCC: {airInterfaceCapacity}
    deactivate aiCC

  end loop

  loop for all entries of [historicalPerformanceDataList]
    prepTxModes -> intCC : {[time-xstates-list],\n[transmission-mode-list]}
    activate intCC #LightCyan
      note over intCC
        Calculate intervalCapacity
      end note
    prepTxModes <-- intCC: {intervalCapacity}
    deactivate intCC

  end loop

cur <-- prepTxModes : {[historicalPerformanceDataList],\n[transmissionModeList]}
deactivate prepTxModes

deactivate cur

@enduml
