openapi: 3.0.0
info:
  title: p1MaintainDs
  version: 1.0.0

x-javascript-interface:
  p1MaintainDs:
    summary: 'Maintains the dataStore by cleaning up expired data.'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - data-store-es-client
            properties:
              parameters:
                type: object
                description: >
                  'Hierarchical object holding the parameter settings'
              data-store-es-client:
                type: object
                description: >
                  'Data Store ElasticSearch address'
    output:
      # there is no success output as this is an ongoing process with an indefinite loop
      error:
        description: 'DataStore maintenance failed'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'Parameters missing or invalid'
                - 'DataStoreEsClient missing or invalid'
                - 'DataStore error'
                - 'General processing error'
    processing:
      description: >
        'The cleanup is executed cycically, according to the time interval
        from [/maintain-ds/cleanup-period]'
      readMountNamesInDs:
        url: # [{/maintain-ds/data-store-url}][/data-store/device=*]
        output:
          success:
            description: 'MountNames from dataStore provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - mount-names
                  properties:
                    mount-names:
                      type: array
                      items:
                        type: string
                      description: >
                        'For each device in the data-store read the mountName and add it to the mountNames list,
                        from [/data-store/device=*]'
          error:
            description: 'Reading mount-names failed'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'General processing error'
      p1GetSortedBatchTimestampsFromDs:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - data-store-es-client
                  - mount-name
                properties:
                  data-store-es-client:
                    type: object
                    description: >
                      'Data Store ElasticSearch address'
                  mount-name:
                    type: string
                    description: >
                      'MountName
                      from [/maintain-ds/mount-name]'
        output:
          success:
            description: 'Sorted list of batch timestamps provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - sorted-batch-timestamps
                  properties:
                    sorted-batch-timestamps:
                      type: array
                      items:
                        type: string
                      description: >
                        'The list of sorted batch timestamps'
          error:
            description: 'Reading batch timestamps failed'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'DataStoreEsClient not provided'
                    - 'DataStoreEsClient invalid'
                    - 'MountName not provided'
                    - 'MountName invalid'
                    - 'General processing error'
        deleteExpiredBatches:
          url: # [{/maintain-ds/data-store-url}][/data-store/device={/maintain-ds/mount-name}/batch={/maintain-ds/timestamp}]
          description: >
            'IF ([/maintain-ds/timestamp] older than allowed by {$input.retention-period})
            THEN delete batch from dataStore. Once a timestamp is encountered that is not expired,
            break'
          input:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - retention-period
                  properties:
                    retention-period:
                      type: string
                      description: >
                        'RetentionPeriod
                        from [maintain-ds/retention-period]'
          output:
            success:
              description: 'Expired batch deleted from dataStore'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'Expired batch deleted from dataStore'
            error:
              description: 'Deleting expired batch failed'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'DataStore url invalid'
                      - 'MountName invalid'
                      - 'Timestamp invalid'
                      - 'General processing error'
        getBatchesCountFromDs:
          url: # [{/maintain-ds/data-store-url}][/data-store/device={/maintain-ds/mount-name}/batch=*]
          output:
            success:
              description: 'Batch count provided'
              content:
                application/json:
                  schema:
                    type: object
                    required:
                      - batch-count
                    properties:
                      batch-count:
                        type: integer
                        description: >
                          'The number of batches for the current mountName in the dataStore.'
            error:
              description: 'Reading batch count failed'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'DataStore url invalid'
                      - 'MountName invalid'
                      - 'General processing error'
        deleteExpiredDevice:
          url: # [{/maintain-ds/data-store-url}][/data-store/device={/maintain-ds/mount-name}]
          description: >
            'IF ([/maintain-ds/batch-count] == 0)
            THEN delete complete device from the dataStore.'
          input:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - batch-count
                  properties:
                    batch-count:
                      type: integer
                      description: >
                        'Batch count for the current mountName
                        from [maintain-ds/batch-count]'
          output:
            success:
              description: 'Expired device deleted from dataStore'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'Expired device deleted from dataStore'
            error:
              description: 'Deleting device from dataStore failed'
              content:
                application/json:
                  schema:
                    type: string
                    enum:
                      - 'DataStore url invalid'
                      - 'MountName invalid'
                      - 'BatchCount missing or invalid'
                      - 'General processing error'

paths:
  /:
    description: 'no rest path provided by this module'