@startuml p1MaintainDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1MaintainDs
end title

participant "p1StreamPmData\n" as requestor
participant "p1MaintainDs\n" as cur #LightCyan
participant "p1MaintainDeviceInDs" as dev #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{parameters},\n{configFile},\n{dataStoreEsClient}}
activate cur #LightCyan

loop endless
  note over cur
    Cycically cleanup the dataStore
    according to time interval configured
    in parameters.<i>dataStoreCleanupPeriod</i>.

    With <i>retentionPeriod</i> from
    parameters.<i>dataStoreRetentionPeriod</i>.
  end note

  note over cur
    <u>ReadMountNamesInDs</u>
      Get a list of mountNames
      for all devices in the dataStore.
  end note
  cur -> ds
  cur <-- ds: {{mountNameList}}

  'iterate over each device
  loop FOR EACH mountName in mountNameList
    note over cur
      <u>p1MaintainDeviceInDs</u>
    end note

    cur -> dev: {{parameters},\n{configFile},\n{dataStoreEsClient},\nmountName,\nretentionPeriod}
    activate dev #LightCyan
      note over dev
        Deletes expired
        data from dataStore
      end note
      dev -> ds
      dev <-- ds
    cur <-- dev
    deactivate dev
  end loop

end loop

deactivate cur




@enduml
