@startuml p1MaintainDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1MaintainDs
end title

participant "p1StreamPmData\n" as requestor
participant "p1MaintainDs\n" as cur #LightCyan
participant "p1ReadLotTimestampsFromDs" as lotTs #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{parameters},\n{configFile},\n{dataStoreEsClient}}
activate cur #LightCyan

loop endless
  note over cur
    Cycically cleanup the dataStore
    according to time interval configured
    in parameters.<i>dataStoreCleanupPeriod</i>.

    With <i>retentionPeriod</i> (<i>rp</i>) from
    parameters.<i>dataStoreRetentionPeriod</i>.
  end note


'REDO

end loop

deactivate cur

footer


<b>Retention period</b>: is a parameter of p1MaintainDs, not of its subfunctions, as it is the same for all
  subfunctions. For the subfunctions it is just handled as a normal input.
end footer


@enduml
