@startuml p2DiscardIrrelevantPmRecords
skinparam responseMessageBelowArrow true

title
  p2DiscardIrrelevantPmRecords
end title

participant "requestor\n(e.g. p2LoadRawCc)" as requestor
participant "p1DiscardIrrelevant\nPmRecords" as cur


requestor -> cur: { [historicalPerformanceDataList],\n{offset} }
activate cur

  note over cur
    Initializes:
      newMostRecentPeriodEndTime
      newMostRecentPeriodEndTime24
  end note


loop FOR EACH record in [historicalPerformanceDataList]

  note over cur
    IF record.periodEndTime is not newer than:
      - 15min: /offset/mostRecentPeriodEndTime
      - 24h: /offset/mostRecentPeriodEndTime24
    THEN discard record
  end note

  note over cur
    For granularityPeriod == 15-MIN:
    IF (record.periodEndTime > newMostRecentPeriodEndTime)
      THEN update newMostRecentPeriodEndTime
  end note

  note over cur
    For granularityPeriod == 24-HOURS:
    IF (record.periodEndTime > newMostRecentPeriodEndTime24)
      THEN update newMostRecentPeriodEndTime24
  end note

end loop

note over cur
  /offset/mostRecentPeriodEndTime = newMostRecentPeriodEndTime
  /offset/mostRecentPeriodEndTime24 = newMostRecentPeriodEndTime24
end note

requestor <-- cur: { [filteredHistoricalPerformanceDataList],\n{offset} }

deactivate cur

@enduml
