@startuml p1ReadDataStoreDeviceData
skinparam responseMessageBelowArrequestorw true

title
  p1ReadDataStoreDeviceData
end title

participant "requestor" as requestor
participant "p1ReadDataStoreDeviceData\n" as cur
database "DataStore" as ds


requestor -> cur: { ressourcePath }
activate cur

    cur -> ds: { ressourcePath }
      note over ds
        return data addressed
        by ressourcePath
      end note

    cur <-- ds: { {deviceData} }


  requestor <-- cur: { {deviceData} }
deactivate cur

@enduml
