openapi: 3.0.0
info:
  title: p1IterateEcPmSlices
  version: 1.0.0

x-javascript-interface:
  p1IterateEcPmSlices:
    summary: 'Iterates through all EthernetContainer historical performance data slices and calls the processing Functions'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - historical-performance-data-list
              - aggregation-group
              - result-cc
            properties:
              parameters:
                type: object
                description: 'Hierarchical object holding the parameter settings'
              historical-performance-data-list:
                type: array
                description: >
                  'historicalPerformanceDataList'
              aggregation-group:
                type: object
                description: >
                  'aggregationGroup'
              result-cc:
                type: object
                description: >
                  'resultCc'
    output:
      success:
        description: 'historicalPerformanceDataList processed'
        content:
          application/json:
            schema:
              type: object
              required:
                - historical-performance-data-list
              properties:
                historical-performance-data-list:
                  type: array
                  description: >
                    'historicalPerformanceDataList
                    from [/iterate-ec-pm-slices/historical-performance-data-list]'
                most-recent-period-end-time:
                  type: string
                  description: >
                    'mostRecentPeriodEndTime
                    from [/iterate-ec-pm-slices/most-recent-period-end-time]'
                most-recent-period-end-time-24:
                  type: string
                  description: >
                    'mostRecentPeriodEndTime24
                    from [/iterate-ec-pm-slices/most-recent-period-end-time-24]'
      error:
        description: 'historicalPerformanceDataList could not be processed'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'parameters not provided'
                - 'parameters invalid'
                - 'historicalPerformanceDataList not provided'
                - 'historicalPerformanceDataList invalid'
                - 'Ethernet KPIs could not be calculated'
                - 'Default values could not be removed'
                - 'Utilization could not be calculated'
                - 'historicalPerformanceDataList could not be provided'
                - 'mostRecentPeriodEndTime could not be provided'
                - 'mostRecentPeriodEndTime24 could not be provided'
                - 'General processing error'
    processing:
      p1CalculateEthernetKpis:
        summary: 'Adds Ethernet KPIs to a historicalPerformanceData set'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - historical-performance-data
                properties:
                  historical-performance-data:
                    type: array
                    description: >
                      'historicalPerformanceData set
                      from [/iterate-ec-pm-slices/historical-performance-data-list=*/performance-data]'
        output:
          success:
            description: 'Ethernet KPIs added'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - historical-performance-data
                  properties:
                    historical-performance-data:
                      type: object
                      description: >
                        'historicalPerformanceData'
          error:
            description: 'Ethernet KPIs could not be added'
            content:
              application/json:
                schema:
                  type: string
      p1RemoveDefaultValues:
        summary: 'Deletes attributes with default values from the transferred object'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - input-object
                properties:
                  parameters:
                    type: object
                    description: >
                      'Hierarchical object holding the parameter settings
                      from [/iterate-ec-pm-slices/parameters/sub-function=p1RemoveDefaultValues]'
                  input-object:
                    type: object
                    description: >
                      'performanceData set of a single time period
                      from [/iterate-ec-pm-slices/historical-performance-data-list=*/performance-data]'
        output:
          success:
            description: 'Input object cleaned from attributes with default values'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - cleaned-object
                  properties:
                    cleaned-object:
                      type: object
                      description: >
                        'Data object from which attributes with default values have been removed'
          error:
            description: 'Input object could not be cleaned from attributes with default values'
            content:
              application/json:
                schema:
                  type: string
      p1CalculateUtilization:
        summary: 'Calculates utilization of the aggregated physical resources in a performance data slice'
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - historical-performance-data
                  - aggregation-group
                  - result-cc
                properties:
                  historical-performance-data:
                    type: object
                    description: >
                      'historicalPerformanceData set
                      from [/iterate-ec-pm-slices/historical-performance-data-list=*/performance-data]'
                  aggregation-group:
                    type: object
                    description: >
                      'aggregationGroup
                      from [/iterate-ec-pm-slices/aggregation-group]'
                  result-cc:
                    type: object
                    description: >
                      'resultCc
                      from [/iterate-ec-pm-slices/result-cc]'
        output:
          success:
            description: 'Utilization added'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - historical-performance-data
                  properties:
                    historical-performance-data:
                      type: object
                      description: >
                        'historicalPerformanceData'
          error:
            description: 'Utilization could not be added'
            content:
              application/json:
                schema:
                  type: string
      updateMostRecentPeriodEndTime:
        summary: 'Overwrites mostRecentPeriodEndTime or mostRecentPeriodEndTime24 with latest value of periodEndTime'
        input:
          content:
            application/json:
              schema:
                type: object
                required:
                  - most-recent-period-end-time
                  - most-recent-period-end-time-24
                  - granularity-period
                  - period-end-time
                properties:
                  most-recent-period-end-time:
                    type: string
                    description: >
                      'mostRecentPeriodEndTime
                      from [/iterate-ec-pm-slices/most-recent-period-end-time]'
                  most-recent-period-end-time-24:
                    type: string
                    description: >
                      'mostRecentPeriodEndTime24
                      from [/iterate-ec-pm-slices/most-recent-period-end-time-24]'
                  granularity-period:
                    type: string
                    description: >
                      'granularityPeriod
                      from [/iterate-ec-pm-slices/historical-performance-data-list=*/granularity-period]'
                  period-end-time:
                    type: string
                    description: >
                      'periodEndTime
                      from [/iterate-ec-pm-slices/historical-performance-data-list=*/period-end-time]'
        output:
          success:
            description: 'mostRecentPeriodEndTime provided'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - most-recent-period-end-time
                    - most-recent-period-end-time-24
                  properties:
                    most-recent-period-end-time:
                      type: string
                      description: >
                        'mostRecentPeriodEndTime
                        from [{$input#period-end-time} if {$input#granularity-period}==ethernet-container-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN]'
                    most-recent-period-end-time-24:
                      type: string
                      description: >
                        'mostRecentPeriodEndTime24
                        from [{$input#period-end-time} if {$input#granularity-period}==ethernet-container-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS]'
          error:
            description: 'mostRecentPeriodEndTime could not be provided'
            content:
              application/json:
                schema:
                  type: string
                  enum:
                    - 'mostRecentPeriodEndTime not provided'
                    - 'mostRecentPeriodEndTime invalid'
                    - 'mostRecentPeriodEndTime24 not provided'
                    - 'mostRecentPeriodEndTime24 invalid'
                    - 'granularityPeriod not provided'
                    - 'granularityPeriod invalid'
                    - 'periodEndTime not provided'
                    - 'periodEndTime invalid'
                    - 'mostRecentPeriodEndTime could not be provided'
                    - 'General processing error'

paths:
  /:
    description: 'no rest path provided by this module'
