@startuml diagram
skinparam responseMessageBelowArrow true

title
p1LoadRawCc
end title

participant "requestor\n(e.g. p1ProcessingOrchestratorForHistoricalPm)" as requestor
participant "p1LoadRawCc" as cur #LightCyan
database "MWDI ES\nreplica" as MwdiEs #LightCyan
database "datastore" as datastore #LightCyan

note over cur #LightCoral
  shall this function call also contain
  function input and function parameters?
end note

requestor -> cur: {mountName}
activate cur #LightCyan

'Read CC
note over cur
  <u>readControlConstructFromEs</u>
  reads the complete ControlConstruct
  for the mount-name from
  MWDI ElasticSearch replica
end note
cur -> MwdiEs: {mountName}
cur <-- MwdiEs: {raw ControlConstruct}

'Read mostRecentTimestamps
note over cur
  <u>retrieveMostRecentPeriodEndTimesFromDs</u>
  Reads mostRecentPeriodEndTimes for all previously
  seen interfaces of the mountName from the
  DPMDP dataStore.
end note
cur -> datastore: {mountName}
cur <-- datastore: {listOf-(ltpUuid, listOf-(lpLocalId, mostRecentPeriodEndTime))}

'Filter the data
note over cur
  <u>applyFilteringForLtpStructureAugmentAirIfAndEthContainer</u>
  Filter the complete ControlConstruct data from <i>readControlConstructFromEs</i>.
  Only relevant information is kept: from equipmentAugment,
  LTP structure and augment and layerProtocols (AirInterface
  or EthernetContainer).

  Inside kept layerProtocols historical PM data is only kept, if
  - granularity is 15min or 24h
  - and the period-end-time of a record is newer that
    the mostRecentPeriodEndTime for the given interface instance

  If for an interface instance no historical PM records remain
  after the above filtering, this interface instance (layer-protocol) is discarded
  entirely and not kept in the contents of the raw ControlConstruct
  (The ltp the layer-protocol belongs to, is kept!).
end note

note over cur #Orange
  In the pre-release there is no mostRecentPeriodEndTime info
  available.
  This data will be found in the DataStore:
  [/data-store/device/ltp/most-recent-period-end-time].
  But storing anything in the datastore it out of scope for the pre-
  release. Therefore: all 15min/24h historical PM records seen in the raw
  data will be kept!
end note

note over cur
  <u>returnReference</u>
  The function returns a reference (indicated by preceeding "_")
  pointing to where the filtered raw-ControlConstruct
  data object is kept in the DPMDP runtime memory.
end note

requestor <-- cur: {_rawControlConstruct}

deactivate cur



footer


  <i>If future releases require additional data to be kept or filtered out, execution of </i>applyFilteringForLtpStructureAugmentAirIfAndEthContainer
  <i>could be swapped for another filtering step.</i>
end footer