@startuml p1LoadRawCc
skinparam responseMessageBelowArrow true

title
p1LoadRawCc
end title

participant "requestor\n(e.g. p1ProcessingOrchestratorForHistoricalPm)" as requestor
participant "p1LoadRawCc" as cur #LightCyan
database "MWDI ES\nreplica" as MwdiEs #LightCyan
database "p1FieldsFilter" as fieldsFilter #LightCyan
database "datastore" as datastore #LightCyan

requestor -> cur: {mountName, {parameters}}
activate cur #LightCyan

'Read CC
note over cur
  <u>readControlConstructFromEs</u>
  reads the complete ControlConstruct
  for the mount-name from
  MWDI ElasticSearch replica
end note
cur -> MwdiEs: {mountName}
cur <-- MwdiEs: {raw ControlConstruct}

'Apply fields filter
note over cur
  <u>ApplyFieldsFilter</u>
  Reduce the amount of data to relevant classes
  and attributes. Information from ... is kept: 
  - equipmentAugment
  - ltp (structure) and augment
  - layerProtocol (AirInterface, EthernetContainer)

  The fieldsFilter is provided as function parameter/
  stringProfile _todo_. 
end note

cur -> fieldsFilter: {raw ControlConstruct, fieldsFilter}
cur <-- fieldsFilter: {filtered raw ControlConstruct}


'Read mostRecentTimestamps
note over cur
  <u>retrieveMostRecentPeriodEndTimesFromDs</u>
  Reads mostRecentPeriodEndTimes for all previously
  seen interfaces of the mountName from the
  DPMDP dataStore.
end note
cur -> datastore: {mountName}
cur <-- datastore: {listOf-(ltpUuid, listOf-(lpLocalId, mostRecentPeriodEndTime))}

'Filter the data
note over cur #LightCoral
  Maybe add a own function here, which filters out data
  from a list of PM records, which are not newer than a given timestamp (mostRecentPeriodEndTime).
  Input would be:
  - the list of PM records of an interface
  - the mostRecentPeriodEndTime
  Output would be
  - the list of PM records that remain after filtering

  This function could be useful as a generic function, if there are other services,
  where we only want to return data which is newer than a given timestamp.
end note

note over cur
  <u>applyFilteringForRelevantPmData</u>
  The filtered raw ControlConstruct still contains "empty"
  layer protocols (non AirInterface/EthernetContainer).
  Those are filtered out.

  Inside the kept AirInterface/EthernetContainer layerProtocols,
  historical PM data is only kept if:
  - granularity is 15min or 24h
  - and the period-end-time of a record is newer that
    the mostRecentPeriodEndTime for the given interface instance
    (in case of missing mostRecentPeriodEndTime for the interface
    instance all data is treated as newer)

  If for an interface instance no historical PM records remain
  after the above filtering, this interface instance (layer-protocol) is discarded
  entirely and not kept in the contents of the raw ControlConstruct
  (The LTP the layer-protocol belongs to, is kept!).
end note

note over cur #Orange
  In the pre-release there is no mostRecentPeriodEndTime info
  available.
  This data will be found in the DataStore:
  [/data-store/device/ltp/most-recent-period-end-time].
  But storing anything in the datastore it out of scope for the pre-
  release. Therefore: all 15min/24h historical PM records seen in the raw
  data will be kept!
end note

note over cur
  <u>returnReference</u>
  The function returns a reference (indicated by preceeding "_")
  pointing to where the filtered raw-ControlConstruct
  data object is kept in the DPMDP runtime memory.
end note

requestor <-- cur: {_rawControlConstruct}

deactivate cur
