@startuml p1LoadRawCc
skinparam responseMessageBelowArrow true

title
  p1LoadRawCc
end title

participant "p1ProcessingPmData)" as requestor
participant "p1LoadRawCc" as cur #LightCyan
database "MWDI ES\nreplica" as MwdiEs #LightCyan
database "p1FieldsFilter" as fieldsFilter #LightCyan
database "datastore" as datastore #LightCyan
participant "p1DiscardIrrelevantPmRecords" as filterPm #LightCyan

requestor -> cur: {mountName, parameters}
activate cur #LightCyan

== Read CC and apply fieldsFilter ==
 'Read CC
note over cur
  <u>readControlConstructFromEs</u>
  reads the complete ControlConstruct for the
  mountName from MWDI ElasticSearch replica
end note
cur -> MwdiEs: {mountName}
cur <-- MwdiEs: {rawControlConstruct}

'Apply fields filter
note over cur
  <u>applyFieldsFilter</u>
  Reduce the amount of data to relevant classes
  and attributes. Information from ... is kept: 
  - equipmentAugment
  - ltp (structure) and augment
  - layerProtocol (AirInterface, EthernetContainer)

  Set rawControlConstruct := filtered rawControlConstruct
end note

cur -> fieldsFilter: {rawControlConstruct,\n/parameters/sub-function=p1FieldsFilter/parameter=fieldsFilter/value}
cur <-- fieldsFilter: {filtered rawControlConstruct}


== Read mostRecentPeriodEndTimes from dataStore ==
'Read mostRecentTimestamps
note over cur
  <u>retrieveMostRecentPeriodEndTimesFromDs</u>
  Reads mostRecentPeriodEndTimes for all previously
  seen interfaces of the mountName from the
  DPMDP dataStore.
  It retrieves the timestamps for ... granularity:
  - 15min: mostRecentPeriodEndTime
  - 24h: mostRecentPeriodEndTime24
end note
cur -> datastore: {mountName}
cur <-- datastore: {listOf-(ltpUuid, listOf-(lpLocalId, mostRecentPeriodEndTime, mostRecentPeriodEndTime24))}

'Filter the data

== Apply filtering on interface level ==

group Filter remaining rawControlConstruct data
  note over cur
    <u>applyFilteringForRelevantPmData</u>
    Discard any "empty" layer protocols (non AirInterface/EthernetContainer),
    from rawControlConstruct.

    For each AirInterface/EthernetContainer instance (currentInterface) apply
    additional filtering by calling p1DiscardIrrelevantPmRecords.
    IF the length(currentInterface.(filtered historicalPerformanceDataList)) == 0,
    THEN discard the entire currentInterface instance (layerProtocol) from the rawControlConstruct,
    ELSE replace the currentInterface.historicalPerformanceDataList with the filtered
    historicalPerformanceDataList.
  end note

  ' For each relevant interface filter the PM records
  group For each AirInterface and EthernetContainer
    note over cur, datastore
      <u>DiscardIrrelevantPmRecords</u>
      Send the historicalPerformanceDataList to the function, where all irrelevant PM records
      are discarded. Overwrite the original list:
      currentInterface.<i>historicalPerformanceDataList</i> := filtered historicalPerformanceDataList 

      Records are considered irrelevant, if:
      - their granularity is not 15min or 24h
      - their periodEndTime is not newer than <i>mostRecentPeriodEndTime</i> (15min) or <i>mostRecentPeriodEndTime</i> (24h)
      
      (IF <i>mostRecentPeriodEndTime</i> or <i>mostRecentPeriodEndTime24</i>
      are not available for the current interface, treat all seen records as newer.)
    end note
    cur -> filterPm: {historicalPerformanceDataList, mostRecentPeriodEndTime, mostRecentPeriodEndTime24, granularitiesToBeKept}
    cur <-- filterPm: {filtered historicalPerformanceDataList}
  end group

  ' remove after pre-release
  note over cur, filterPm #Orange
    In the pre-release there is no mostRecentPeriodEndTime info available.
    This data will be found in the DataStore: [/data-store/device/ltp/most-recent-period-end-time].
    But storing anything in the datastore it out of scope for the pre-release. Therefore: all 15min/24h historical PM records seen in the raw
    data will be kept!
  end note
end group

note over cur
  <u>returnRawControlConstruct</u>
  The function returns the filtered raw-ControlConstruct
end note

requestor <-- cur: {{rawControlConstruct}}
deactivate cur
