@startuml p1MaintainDs
skinparam responseMessageBelowArrow true
skinparam SequenceDividerBackgroundColor #LightSalmon

title
  p1MaintainDs
end title

participant "p1StreamPmData\n" as requestor
participant "p1MaintainDs\n" as cur #LightCyan
participant "p1GetListOfExpired\nDsInterfaces" as expIf #LightCyan
participant "p1GetListOfExpired\nDsDevice" as expDev #LightCyan
database "DataStore" as ds #LightCyan


activate requestor

requestor -> cur : {{parameters},\n{configFile},\n{dataStoreEsClient}}
activate cur #LightCyan

loop endless
  note over cur
    Cycically cleanup the dataStore
    according to time interval configured
    in parameters.<i>dataStoreCleanupPeriod</i>.

    With <i>retentionPeriod</i> (<i>rp</i>) from
    parameters.<i>dataStoreRetentionPeriod</i>.
  end note

  note over cur
    <u>ReadDeviceInfoFromDs</u>
    Read mountNames and interface
    (= interface list) of all
    devices in datastore
  end note
  cur -> ds
  cur <-- ds: {{listOf-(mountName,{interface})}, retentionPeriod}

  == 1. Expired interfaces ==

  'first get expired interfaces
  note over cur
    Determine which interfaces are expired
    (across all mountNames).
  end note
  cur -> expIf: {{listOf-(mountName,{interface})}}
  activate expIf #LightCyan
    note over expIf
      Check which of the interfaces
      are expired.
      Return uuids of expired interfaces
      for every mountName
    end note
  cur <-- expIf: {{listOf-(mountName,{uuidList})}}
  deactivate expIf

  'then delete the expired interfaces
  loop FOR EACH (mountName, uuid)
    note over cur
      <u>DeleteExpiredInterfaces</u>
      For each (mountName, uuid) from the previous step,
      delete the interface from the datastore, i.e.
      delete [/data-store/device=mountName/interface=uuid]
    end note
    cur -> ds: {mountName, uuid}
    cur <-- ds
  end loop

  == 2. Expired devices ==
  
  'again get the list of mountName,interface
  note over cur
    <u>ReadRemainingDeviceInfoFromDs</u>
    Again, read mountNames and interface
    (= interface list) of all devices in datastore
  end note
  cur -> ds
  cur <-- ds: {{listOf-(mountName,{interface})}, retentionPeriod}

  'from that get the list of expired devices
  note over cur
    <u>GetListOfExpiredDevices</u>
  end note
  cur -> expDev: {{listOf-(mountName,{interface})}}
  activate expDev #LightCyan
    note over expDev
      Determine the list of devices,
      which no longer have interface data
    end note
  cur <-- expDev: {{mountNameList}}
  deactivate expDev

  'now delete expired devices from dataStore
  loop FOR EACH expired mountName
    note over cur
      <u>DeleteExpiredDeviceFromDataStore</u>
      For each mountName from the mountName list
      determined in the previous step, delete the complete
      device from the datastore, by deleting:
      [/data-store/device=mountName]
    end note
    cur -> ds: {mountName}
    cur <-- ds
  end loop

  == Expired lots ==
  'no own subfunction, for getting a list of timestamps, because the timestamp is not a x-key
  
  'get remaining mountNames
  note over cur
    <u>ReadRemainingDevices</u>
    Read mountNames of all remaining devices
    in the dataStore.
  end note
  cur -> ds
  cur <-- ds: {{mountNameList}}

  'iterate over mountNames
  loop FOR EACH mountName
    note over cur
      <u>ReadLotTimestamps</u>
      Get the list of lot timestamps
      of the mountName from the dataStore
      (result-cc doesn't need to be read).
    end note
    cur -> ds: {mountName}
    cur <-- ds: {{timestampList}}

    loop FOR EACH timestamp
      note over cur
        IF (timestamp older than retentionPeriod)
        THEN delete array item with this timestamp from the lot.
      end note
      cur -> ds: {mountName, timestamp}
      cur <-- ds

    end loop
  end loop


end loop

deactivate cur

footer


<b>Retention period</b>: is a parameter of p1MaintainDs, not of its subfunctions, as it is the same for all
  subfunctions. For the subfunctions it is just handled as a normal input.

Why read list of mountNames & interfaces again for step 2 (expired devices)? -> Data is being written to the datastore constantly.
Between deleting interfaces from a mountName and getting expired devices, new interface data can be written. Reading again counters data loss.
end footer


@enduml
