@startuml 015_ProvideInterfaceDataOnDemand
skinparam responseMessageBelowArrow true

title
PromptForProvidingInterfaceDataOnDemandCausesReadingMwdiLtpStructureAndAugment
end title

participant "external" as requestor
participant "DPMDP://v1/provide-interface-\ndata-on-demand" as dpmdp
participant "MWDI://<i>CC_CACHE</i>?fields=\ndpmdp-*-*-*-string-p-003" as ltp
'Id translation
participant "p1ProvideCcIdentifiers\nForAirInterface" as idsAir #LightBlue
participant "p1ProvideCcIdentifiers\nForEthernetContainer" as idsEth #LightBlue
'DeviceType
participant "MWDI://v1/provide-device-\nstatus-metadata" as devType
'live AirInterface
participant "MWDI\n<i>AirIfLive</i>\n<i>Capability</i>" as airCap
participant "MWDI\n<i>AirIfLive</i>\n<i>Config</i>" as airConf
participant "MWDI\n<i>AirIfLive</i>\n<i>Status</i>" as airStatus
participant "MWDI\n<i>AirIfLive</i>\n<i>HistoPm</i>" as airPm
'live EthContainer
participant "MWDI\n<i>EthContLive</i>\n<i>HistoPm</i>" as ethPm
'internal functions - shall all be executed or only depending on interfaceType?
participant "p1ProvideAirInterface\nAndEthernetContainer\nInterfaceNames" as ifNames #LightBlue
participant "p1ProvideAirInterface\nPhysicalLinkAggregation" as lag #LightBlue

'Diese Function ist noch nicht spezifiziert:
participant "p1CreateOnDemand\nInterfaceData\nOutputObject" as createOutput #LightBlue

participant "p1SetOutOfLevelValues\nToDefault" as setLevel #LightBlue
participant "p1Inquire15min\nAirInterfaceKpis\nFromCaca" as kpiAi #LightBlue
participant "p1Inquire15min\nEthernetContainerKpis\nFromCaca" as kpiEth #LightBlue
participant "p1ReplaceOnfDefaultValues" as replaceDef #LightBlue

requestor -> dpmdp: {mountName, linkId or portId}(BasicAuth)
activate dpmdp

note over dpmdp #LightGrey
  Target depends on input parameters:
  - mountName & linkId -> AirInterface
  - mountName & portId -> EthernetContainer
end note

' ---- Get IDs ---------------------------------------------------------------------------------
== Translate input IDs into ControlConstruct IDs ==

group Translate IDs into ControlConstruct IDs
  note over dpmdp
    <u>GetLtpStructureAndAugment</u>
  end note
  dpmdp -> ltp: {mountName} (apiAuthKey)
  ltp --> dpmdp: {ltpStructureAndAugment}

  note over dpmdp
    <u>GetTranslatedIdsAirIf</u>
    IF (target == AirInterface)
  end note
  dpmdp -> idsAir: {mountName && linkId}
  idsAir --> dpmdp: {mountName, uuid, localId}

  note over dpmdp
    <u>GetTranslatedIdsEth</u>
    IF (target == EthernetContainer)
  end note
  dpmdp -> idsEth: {mountName && portId}
  idsEth --> dpmdp: {mountName, uuid, localId}
end group

note over dpmdp
  If no mapping found <u>Terminate</u>
end note
dpmdp --> requestor: {errorResponse}


' ---- Get MWDI ---------------------------------------------------------------------------------
== Get MWDI data ==
note over dpmdp
  <u>GetDeviceType</u>
  DeviceType might be required
  for deviceType specific processing
end note
dpmdp -> devType: {mountName} (apiAuthKey)
devType --> dpmdp: {deviceType}

note over dpmdp
  IF (target == AirInterface)
end note
group Get Live AirInterface data from MWDI
  dpmdp -> airCap: {mountName} (apiAuthKey)
  airCap --> dpmdp: {AirInterfaceCapability}
  dpmdp -> airConf: {mountName} (apiAuthKey)
  airConf --> dpmdp: {AirInterfaceConfiguration}
  dpmdp -> airStatus: {mountName} (apiAuthKey)
  airStatus --> dpmdp: {AirInterfaceStatus}
  dpmdp -> airPm: {mountName} (apiAuthKey)
  airPm --> dpmdp: {AirInterfaceHistoricalPerformances}
end group

note over dpmdp
  IF (target == EthernetContainer)
end note
group Get Live EthernetContainer data from MWDI
  dpmdp -> ethPm: {mountName} (apiAuthKey)
  ethPm --> dpmdp: {EthernetContainerHistoricalPerformances}
end group

== Process Interface data ==

note over dpmdp
  <u>GetInterfaceNames</u>
  Identifiers are extracted from ltpStructureAndAugment information,
  - AirInterface: linkEndpointId (=unitId), linkId
  - EthContainer: interfaceName
  
  Note: for reusage of internal functions, both a list of AirInterfaces
  and EthernetContainers is provided as input, but only
  information for the target interface is provided there
end note
dpmdp -> ifNames: {ltpStructureAndAugment, AirInterfaceList, EthernetContainerList}
ifNames --> dpmdp: {listOf-(uuid, interfaceIdentifiers)}

note over dpmdp
  <u>GetAirInterfaceLinkAggregationInfo</u>
  IF (target == AirInterface)
end note
  'LAG
  dpdmp -> lag: {ltpStructureAndAugment, AirInterfaceList}
  lag --> dpmdp: {listOf(uuid, linkAggregationIdentifiers)}


note over dpmdp #Red
  function noch nicht erstellt
  kann ggf. auch zum schluss kommen, 
  -> Daten dann erst zusammensetzen
end note

note over dpmdp
  <u>CreateOutputObject</u>
  Create the output object from the data
  gathered from the various MWDI requests
  (output format as described in T1out_Output.yaml) 
  if (target==AirInterface), EthernetContainer data = null,
  elseIf (target==EthernetContainer), AirInterface data = null
end note
  dpmdp -> createOutput: {AirInterface data, EthernetContainer data}

note over dmpmdp
  Apply functions to process data
  <u>SetOutOfRangeLevelValues</u>
  <u>Inquire15minAirIfKpis</u>
  <u>Inquire15minEthContainerKpis</u>
  <u>ReplaceOnfDefaultValues</u> 
end note

'level
dmpdm -> setLevel: {AirInterface data (level)}
setLevel --> dpmdp: {modified AirInterface data (level)}



deactivate dpmdp



footer
 With MWDI paths
 - CC_CACHE = /core-model-1-4:network-control-domain=cache/control-construct={mountName}
 - AirIfLiveCapability = /core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-capability
 - AirIfLiveConfig = /core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-configuration
 - AirIfLiveStatus = /core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-status
 - AirIfLiveHistoPm = /core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-historical-performances
 - EthContLiveHistoPm = /core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances
end footer

@enduml
