@startuml p1DiscardIrrelevantPmRecords
skinparam responseMessageBelowArrow true

title
  p1DiscardIrrelevantPmRecords
end title

participant "requestor\n(e.g. p2LoadRawCc)" as requestor
participant "p1DiscardIrrelevant\nPmRecords" as cur


requestor -> cur: { [historicalPerformanceDataList]\n<color:LightGray>relevantGranularities\n<color:LightGray>mostRecentPeriodEndTime\n<color:LightGray>mostRecentPeriodEndTime24</color> }
activate cur

loop FOR all [historicalPerformanceDataList]

  note over cur
    IF granularityPeriod does not match relevantGranularities
    THEN discard record
  end note

  note over cur
    IF periodEndTime is not newer than:
      - 15min: mostRecentPeriodEndTime
      - 24h: mostRecentPeriodEndTime24
    THEN discard record
  end note

end loop

requestor <-- cur: { [filteredHistoricalPerformanceDataList] }

deactivate cur

@enduml
