@startuml p2StreamPmData
skinparam responseMessageBelowArrow true

title
  p2StreamPmData
end title

participant "embedYourself\n" as embed
participant "p2StreamPmData\n" as p2Stream
participant "p1LoadParameters\n" as p1LP
participant "p1ResolveEsAddress\n" as p1REA
participant "p1InitKafka\n" as p1InitKafka
participant "p1UpdateMwdiReplica\n" as p1UMR
participant "p2ProcessDevice\n" as p2ProcessDev
participant "p1Transmitting\nKafka" as p1Trans
participant "p1MaintainDs\n" as p1MDS

note right embed
  Automatically starts
  p2StreamPmData
end note
embed -> p2Stream : {}
activate p2Stream

  p2Stream -> p1LP : {functionName=\n"p2StreamPmData"}
  activate p1LP
    note over p1LP
      Loads parameters
      from configFile
    end note
  p2Stream <-- p1LP : { {parameters}\n{configFile} }
  deactivate p1LP

  Loop FOR all esName
    p2Stream -> p1REA : { {parameters}\n{configFile}\nesName }
    activate p1REA
      note over p1REA
        Resolves ES address
      end note
    p2Stream <-- p1REA : { {esAddress} }
    deactivate p1REA
  end Loop

    p2Stream -> p1InitKafka : { {parameters}\n{configFile} }
    activate p1InitKafka

      note over p1InitKafka
        Resolves Kafka address
        Establishes session
      end note

    p2Stream <-- p1InitKafka
    deactivate p1InitKafka

  p2Stream -> p1MDS : { {parameters}\n{dataStoreEsClient} }
  activate p1MDS
    note over p1MDS
      Periodically deletes
      old records
    end note

  loop endless

    p2Stream -> p1UMR : { {parameters}\nlastReplicaTime\n{mwdiEsClient}\n{mwdiReplicaEsClient}\n{loggingEsClient} }
    activate p1UMR
      note over p1UMR
        Replicates updated CCs
      end note
    p2Stream <-- p1UMR : { [updatedMountNames]\ntimestamp }
    deactivate p1UMR

    loop FOR all [updatedMountNames]
      p2Stream -> p2ProcessDev : { {parameters}\n{configFile}\nmountName\n{mwdiReplicaEsClient}\n{dataStoreEsClient} }
      activate p2ProcessDev
        note over p2ProcessDev
          Processes PM data
        end note
      p2Stream <-- p2ProcessDev: { {deviceQualityPmData} }
      deactivate p2ProcessDev
    end loop
  
  p2Stream -> p1Trans : { {/parameters/sub-function=p1TransmittingKafka},\n{configFile},\n[outputFormat] }
  activate p1Trans

    note over p1Trans
      Transmits object
      to Kafka
    end note

  p2Stream <-- p1Trans
  deactivate p1Trans

  end loop

@enduml
