@startuml p1ProcessDevice
skinparam responseMessageBelowArrow true

title
  p1ProcessDevice
end title

participant "p1StreamPmData\n" as requestor
participant "p1ProcessDevice\n" as p1ProOrch #LightCyan
participant "p1LoadRawCc\n" as p1AddRaw #LightCyan
participant "p1CreateResultCc\n" as p1CRC #LightCyan
participant "p1Formatting\nOutputApt" as p1Output #LightCyan
participant "p1Transmitting\nKafka" as p1Trans #LightCyan
participant "p1Storing\n" as p1Store #LightBlue


activate requestor

requestor -> p1ProOrch : {mountName,\n{parameters},\n{mwdiReplicaEsClient},\n{dataStoreEsClient},\n{configFile}}
activate p1ProOrch #LightCyan

  note over p1ProOrch
    Create data structure
    for processing
  end note

  p1ProOrch -> p1AddRaw : {{/parameters/sub-function=loadRawCc},\n{mwdiReplicaEsClient},\n{dataStoreEsClient},\n{configFile},\nmountName}
  activate p1AddRaw #LightCyan

    note over p1AddRaw
      - Load rawCC from MWDI ES
      - Reduce structure of rawCC
      - Delete PM data that has
        already been processed in past
    end note

  p1ProOrch <-- p1AddRaw : {{rawCC}}
  deactivate p1AddRaw

  note over p1ProOrch
    Add rawCC to
    data structure
  end note

  p1ProOrch -> p1CRC : {{/parameters/sub-function=createResultCc},\n{rawCC}}
  activate p1CRC #LightCyan

    note over p1CRC
      - Create resultCC from rawCC
      - Process and complement PM data
    end note

  p1ProOrch <-- p1CRC : {{resultCC}}
  deactivate p1CRC

  note over p1ProOrch
    Add resultCC to
    data structure
  end note

  p1ProOrch -> p1Output : {{/parameters/sub-function=p1FormattingOutputApt},\n{resultCC}}
  activate p1Output #LightCyan

    note over p1Output
      Create aptOutputFormat
      from resultCC
    end note

  p1ProOrch <-- p1Output : {{aptOutputFormat}}
  deactivate p1Output

  note over p1ProOrch
    Add aptOutputFormat
    to data structure
  end note

  p1ProOrch -> p1Trans : {{/parameters/sub-function=p1TransmittingKafka},\n{configFile},\n{aptOutputFormat}}
  activate p1Trans #LightCyan

    note over p1Trans
      Transmit outputFormat
      via Kafka
    end note

  p1ProOrch <-- p1Trans
  deactivate p1Trans

  p1ProOrch -> p1Store : {{/parameters/sub-function=p1Storing},\n{dataStoreEsClient},\n{configFile},\n{resultCC}}
  activate p1Store #LightBlue

    note over p1Store
      Store resultCC
    end note

  p1ProOrch <-- p1Store
  deactivate p1Store

deactivate p1ProOrch

@enduml
