openapi: 3.0.0
info:
  title: p2ProcessDevice
  version: 1.0.0

x-javascript-interface:
  p2ProcessDevice:
    summary: 'Orchestrates the device-wise processing, formatting, sending and storing of PM data.'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - config-file
              - mount-name
              - mwdi-replica-es-client
              - data-store-es-client
            properties:
              parameters:
                type: object
                description: >
                  'Hierarchical object holding the parameter settings'
              config-file:
                type: object
                description: >
                  'configFile content'
              mount-name:
                type: string
                description: >
                  'MountName'
              mwdi-replica-es-client:
                type: object
                description: >
                  'MWDI Replica ElasticSearch address'
              data-store-es-client:
                type: object
                description: >
                  'Data Store ElasticSearch address'
    output:
      success:
        description: 'PM data processed, sent and stored'
        content:
          application/json:
            schema:
              type: object
              required:
                - device-pm-data-quality
              properties:
                device-pm-data-quality:
                  type: object
                  description: >
                    'Information about the quality of the provided PM data of all AirInterfaces and EthernetContainers at the device
                    from [/process-device/device-pm-data-quality]'
      error:
        description: 'Processing of PM data failed'
        content:
          application/json:
            schema:
              type: string
              enum:
                - 'parameters not provided'
                - 'parameters invalid'
                - 'configFile not provided'
                - 'configFile invalid'
                - 'mountName not provided'
                - 'mountName invalid'
                - 'mwdiReplicaEsClient not provided'
                - 'mwdiReplicaEsClient invalid'
                - 'dataStoreEsClient not provided'
                - 'dataStoreEsClient invalid'
                - 'raw CC data missing or invalid'
                - 'result CC data missing or invalid'
                - 'output format missing or invalid'
                - 'kafka transmission failed'
                - 'storing resultCc failed'
                - 'pmDataQuality could not be provided'
                - 'general processing error'
    processing:
      p1LoadOffsetsAndStatusData:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - mount-name
                  - data-store-es-client
                properties:
                  mount-name:
                    type: string
                    description: >
                      'MountName
                      from [/process-device/mount-name]'
                  data-store-es-client:
                    type: object
                    description: >
                      'Data Store ElasticSearch address
                      from [/process-device/data-store-es-client]'
        output:
          success:
            description: 'Offsets and statusData loaded'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - offsets
                    - status-data
                  properties:
                    offsets:
                      type: array
                      description: >
                        'offsets'
                    status-data:
                      type: array
                      description: >
                        'statusData'
          error:
            description: 'rawCc could not be loaded'
            content:
              application/json:
                schema:
                  type: string
      p2LoadRawCc:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - mwdi-replica-es-client
                  - mount-name
                  - offsets
                properties:
                  parameters:
                    type: object
                    description: >
                      'Subtree of the parameters object for p2LoadRawCc
                      from [/process-device/parameters/sub-function=p2LoadRawCc]'
                  mwdi-replica-es-client:
                    type: object
                    description: >
                      'MWDI Replica ElasticSearch address
                      from [/process-device/mwdi-replica-es-client]'
                  mount-name:
                    type: string
                    description: >
                      'MountName
                      from [/process-device/mount-name]'
                  offsets:
                    type: array
                    description: >
                      'Offsets
                      from [/process-device/offsets]'
        output:
          success:
            description: 'rawCc loaded'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - raw-cc
                    - offsets
                    - device-pm-data-quality
                  properties:
                    raw-cc:
                      type: object
                      description: >
                        'rawCc read from Replica ES, but reduced by irrelevant data'
                    offsets:
                      type: array
                      description: >
                        'Array of all Offsets'
                    device-pm-data-quality:
                      type: object
                      description: >
                        'Information about the quality of the provided PM data of all AirInterfaces and EthernetContainers at the device'
          error:
            description: 'rawCc could not be loaded'
            content:
              application/json:
                schema:
                  type: string
      p2CreateResultCc:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - raw-cc
                  - status-data
                properties:
                  parameters:
                    type: object
                    description: >
                      'Subtree of the parameters object for p2CreateResultCc
                      from [/process-device/parameters/sub-function=p2CreateResultCc]'
                  raw-cc:
                    type: object
                    description: >
                      'rawCc
                      from [/process-device/raw-cc]'
                  status-data:
                    type: array
                    description: >
                      'statusData
                      from [/process-device/status-data]'
        output:
          success:
            description: 'Result CC data created'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result-cc:
                      type: object
                      description: >
                        'resultCc'
                    status-data:
                      type: array
                      description: >
                        'statusData'
          error:
            description: 'Result CC data could not be created'
            content:
              application/json:
                schema:
                  type: string
      p1FormattingOutputApt:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - result-cc
                properties:
                  result-cc:
                    type: object
                    description: >
                      'resultCc
                      from [/process-device/result-cc]'
        output:
          success:
            description: 'aptOutputFormat created'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - format-name
                    - output-format
                  properties:
                    format-name:
                      type: string
                      description: >
                        'Name of the output format'
                    output-format:
                      type: object
                      description: >
                        'outputFormat'
          error:
            description: 'aptOutputFormat could not be created'
            content:
              application/json:
                schema:
                  type: string
      p1FormattingOutputOnf:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - result-cc
                properties:
                  parameters:
                    type: object
                    description: >
                      'Subtree of the parameters object for p1FormattingOutputOnf
                      from [/process-device/parameters/sub-function=p1FormattingOutputOnf]'
                  result-cc:
                    type: object
                    description: >
                      'resultCc
                      from [/process-device/result-cc]'
        output:
          success:
            description: 'onfOutputFormat created'
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - format-name
                    - output-format
                  properties:
                    format-name:
                      type: string
                      description: >
                        'Name of the output format'
                    output-format:
                      type: object
                      description: >
                        'outputFormat'
          error:
            description: 'onfOutputFormat could not be created'
            content:
              application/json:
                schema:
                  type: string
      p1TransmittingKafka:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - parameters
                  - config-file
                  - output-format
                properties:
                  parameters:
                    type: object
                    description: >
                      'Subtree of the parameters object for p1TransmittingKafka
                      from [/process-device/parameters/sub-function=p1TransmittingKafka]'
                  config-file:
                    type: object
                    description: >
                      'configFile content
                      from [/process-device/config-file]'
                  output-format:
                    type: array
                    x-key: format-name
                    description: >
                      'Array of output formats potentially to be transmitted
                      from [/process-device/output-format]'
        output:
          success:
            description: 'Objects sent via Kafka'
          error:
            description: 'Objects could not be sent via Kafka'
            content:
              application/json:
                schema:
                  type: string
      p2Storing:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - data-store-es-client
                  - result-cc
                  - offsets
                  - status-data
                properties:
                  data-store-es-client:
                    type: object
                    description: >
                      'Data Store ElasticSearch address
                      from [/process-device/data-store-es-client]'
                  result-cc:
                    type: object
                    description: >
                      'resultCc
                      from [/process-device/result-cc]'
                  offsets:
                    type: array
                    description: >
                      'offsets
                      from [/process-device/offsets]'
                  status-data:
                    type: array
                    description: >
                      'offsets
                      from [/process-device/status-data]'
        output:
          success:
            description: 'resultCc stored'
          error:
            description: 'resultCc could not be stored'
            content:
              application/json:
                schema:
                  type: string

paths:
  /:
    description: 'no rest path provided by this module'
