@startuml 00_hl_overview
skinparam responseMessageBelowArrow true

title
  DevicePerformanceManagementDataProcessor
end title

participant "MWDI\n" as mwdi
participant "cronjob\nin ES" as cjes
participant "regardAttribute-\nValueChange" as rAVC #LightCyan

participant "p1ProcessingOrchestrator\nForHistoricalPm" as p1ProOrch #LightCyan

participant "p1LoadRawDeviceData" as p1AddRaw #LightCyan
database  "MWDI ES\nReplica" as MwdiEs #LightCyan

participant "example\np1ProcessingSpecific" as p1Specific #LightBlue
participant "example\np1ProcessingGeneric" as p1Generic #LightBlue

participant "p1FormattingOutputApt" as p1Output #LightCyan
participant "p1TransmittingKafka" as p1Trans #LightCyan

participant "p1PrepareStoring" as p1PrepStore #LightBlue

participant "p1Storing" as p1Store #LightBlue
database "dataStore" as db #LightBlue

note right mwdi #Orange
  If the Pre-Release does not comprise Storing
  the processing and sending cannot be limited to new PM data
  It is recommended to configure a testing MWDI with
  a very small sliding window to limit the amount of data  
end note

activate rAVC #LightCyan

mwdi -> rAVC
note over rAVC
  AVC notifications are collected
  and categorized by MountName
end note

cjes -> rAVC
note over rAVC
  AVC notification from cronjob
  is initiating processing
end note

rAVC -> p1ProOrch : separate for every MountName
activate p1ProOrch #LightCyan

  note over p1ProOrch
    DataStructureForProcessing
    gets created
  end note

  p1ProOrch -> p1AddRaw
  activate p1AddRaw #LightCyan

    p1AddRaw -> MwdiEs
    p1AddRaw <-- MwdiEs : {rawCC}
    note over p1AddRaw
      Content of {rawCC} is reduced 
      to the necessary data
      Sub-functions might be applied
    end note

  p1ProOrch <-- p1AddRaw : {rawCC*}
  deactivate p1AddRaw

  note over p1ProOrch
    Add {rawCC*} to
    DataStructureForProcessing
  end note

  p1ProOrch -> p1Specific : {_rawCC*, {input}, {parameters}}
  activate p1Specific

    note over p1Specific
      categorization into processes 
      in unclear, and undesigned
      potentially, 
        - adding capability, config, performance
        - processing Ericsson, Huawei, SIAE
        - processing AirInterface, EthernetContainer
    end note

    p1Specific -> p1Generic
    activate p1Generic
  
      note over p1Generic
        e.g., 
          - capacity calculation
          - default value replacement
          - semantical harmonization
      end note

    p1Specific <-- p1Generic
    deactivate p1Generic
    
  p1ProOrch <-- p1Specific : {{result}, [responseCode]}
  deactivate p1Specific

  note over p1ProOrch
    DataStructureForProcessing
    gets filled with results
    and "responseCodes"
  end note

  p1ProOrch -> p1Output : {_resultCC, {input}, {parameters}}
  activate p1Output #LightCyan

    note over p1Output #Orange
      idea: in pre-release, _rawCC* instead of _resultCC gets passed
      -> {output} gets created from raw data instead of not yet calculated results
    end note
    note over p1Output #LightCoral
      Both the rawCC* [DSFP/raw-control-construct] and the resultCC [DSFP/control-construct]
      follow ONF structure BUT the resultCC has some additional attributes (e.g. KPIs),
      which the rawCC DOES NOT HAVE. So just passing _rawCC* instead of _resultCC,
      will lead to some attributes not being there for mapping.
      The target attributes in the generated output should be created, but filled with a default.
      (This will not be specified in the function explicitly, as this is just done for the pre-release)

      Update: besser, wenn Felder im Input nicht da sind, das aber nur normale Attribute und keine Key-Felder sind:
      einfach mit einem Default erzeugen. Dann bleibt man flexibel.
    end note

    note over p1Output
      formatting the results
      for transmitting
    end note

  p1ProOrch <-- p1Output : {output}
  deactivate p1Output

  note over p1ProOrch
    {output} gets added to
    DataStructureForProcessing
  end note

  p1ProOrch -> p1Trans : {_output, {input}, {parameters}}
  activate p1Trans #LightCyan

    note over p1Trans
      {output} gets transmitted
    end note

  p1ProOrch <-- p1Trans
  deactivate p1Trans

  p1ProOrch -> p1PrepStore : {_DataStructureForProcessing}
  activate p1PrepStore

    note over p1PrepStore
      Prepare DataStructureForProcessing
      for storing (e.g., delete {rawCC*}
      and {output})
    end note

  p1ProOrch <-- p1PrepStore
  deactivate p1PrepStore

  p1ProOrch -> p1Store : {_DataStructureForProcessing}
  activate p1Store

    note over p1Store
      DataStructureForProcessing
      gets stored
    end note

    p1Store -> db

    note over p1Store
      Content elder than
      48h gets deleted
    end note

    p1Store -> db

  p1ProOrch <-- p1Store
  deactivate p1Store

deactivate p1ProOrch

@enduml