@startuml 117_p1ProvideAirInterfacePhysicalLinkAggregation
skinparam responseMessageBelowArrow true

title
p1ProvideAirInterfacePhysicalLinkAggregation
end title

participant "requestor" as requestor
participant "p1ProvideAirInterfacePhysicalLinkAggregation" as getLag #LightBlue

activate getLag

note over requestor
The requestor hands over the following information:
- LTP structure and augment (uuid, localId, ServerLtp,
  ClientLtp, LayerProtocolName)
- a list of air interfaces (identified by LTP uuid)
end note
requestor -> getLag: {ltp-structure-and-augment, air-interface-list}

loop for each LTP uuid in LtpStructureAndAugment where LayerProtocolName == AIR_LAYER
  note over getLag
  <u>PrepareLagLookupMap</u>
	Starting from an AirInterfaceUuid, navigate recursively upwards thru the hierarchy of client ltps up to the associated EthernetContainerUuid:
	AirInterface -> HybridMWStructure/PureEthernetStructure -> EthernetContainer
	Then from this EthernetContainerUuid, navigate downwards thru the hierarchy of server ltps, in order to determine 
	all the AirInterfaces/WireInterfaces that (also) point to this EthernetContainer
	EthernetContainer ->List-of HybridMWStructure/PureEthernetStructure -> AirInterface/WireInterface
	As follows:

		ClientLtp OF **AirInterfaceUuid** = **ClientStructureUuid** 
		ClientLtp OF **ClientStructureUuid** = **ClientEthernetContainerUuid**
		ServerLtp OF **ClientEthernetContainerUuid** = LIST-OF **ServingStructureUuid**	

		FOR EACH **ServingStructureUuid** in LIST-OF **ServingStructureUuid**:	
				ServerLtp OF **ServingStructureUuid** = **Wire/AirInterfaceUuid**

	(Result: LIST-OF **Wire/AirInterfaceUuid**)
  end note
end

loop for each LTP uuid in air-interface-list
  note over getLag
  <u>FetchLAGsFromLookupMap</u>
  Traverse the air-interface-list ltp uuids
  and lookup the LAG information in the previously
  computed LIST-OF **Wire/AirInterfaceUuid** as follows:

  For the current LTP uuid:
  IF (related LtpStructureAndAugment.LayerProtocolName):
  - is WIRE_LAYER
    THEN interfaceName = originalLtpName
  - is AIR_LAYER
    THEN linkId = externalLabel.substring(0,9)
  end note

end

getLag --> requestor: {list-of(airInterfaceUuid, LAG-identifiers (list-of(linkId/interfaceName))}
deactivate getLag