@startuml p2TransmittingKafka
skinparam responseMessageBelowArrow true

title
  p2TransmittingKafka
end title

participant "requestor\n" as requestor
participant "p2TransmittingKafka\n" as p1Trans #LightCyan
participant "kafkaProducerService.\nsendMessage" as p1KafkaP #LightCyan
queue "kafka\n" as kafka

activate p1KafkaP #LightCyan

requestor -> p1Trans : { {parameters},\n{configFile},\n[outputFormat] }
activate p1Trans #LightCyan

  loop FOR all [outputFormat]

    note over p1Trans
      Check parameters with 
      purpose==kafkaClient
      for entry with 
      parameterName==formatName
    end note

    note over p1Trans
      if such entry found,
      use kafkaClientUuid
      for reading kafkaClient
      info from configFile
    end note

    p1Trans -> p1KafkaP : {topicName,\n{messageObject}}

      note over p1KafkaP
        Sends object
        to Kafka
      end note

      p1KafkaP -> kafka : {SEND_MESSAGE event}
      p1KafkaP <-- kafka

    p1Trans <-- p1KafkaP

  end loop

requestor <-- p1Trans
deactivate p1Trans

@enduml
