@startuml p1CreateResultCc
skinparam responseMessageBelowArrow true

title
  p1CreateResultCc
end title

participant "p1ProcessDevice\n" as requestor
participant "p1CreateResultCc\n" as cur #LightCyan

participant "p1Cleanup\nTxModes" as cleanTxModes #LightCyan
participant "p1Find\nLastTime" as lastTime #LightCyan
participant "p1Cleanup\nAdmCounters" as cleanAdmCounters #LightCyan
participant "p1Substring\nLinkId" as substrLinkId #LightCyan
participant "p1Compute\nPhysicalLag" as computePhyLag #LightCyan

participant "p1AirInterface\nCapacityCalculation" as airIfKpis #LightBlue
participant "p1Ethernet\nKpiCalculation" as ethKpis #LightBlue

participant "p1Default\nValueTreatment" as defaultValues #LightBlue
participant "p1OutOfRange\nValueTreatment" as outOfRange #LightBlue

requestor -> cur: {_rawCC,\n{parameters}}
activate cur #LightCyan

  note over cur #LightCyan
    Create resultCC from rawCC
  end note



  note over cleanAdmCounters #LightCoral
    Priority: Facilitate generating the APT output format
      - create resultCC structure
      - add additional attributes to structure

    Categories of comments below:
      - LightCyan: Attribute with correct value needed
      - White: Attribute needed, but might contain default value
      - LightGray: fine tuning that is postponed to next release

    Proceeding:
      - Explicitly (in detail) represent resultCC in variable.yaml
      - Create sub-folders in /p1CreateResultCc for required sub-functions (even if category is white)
        - add readme file with overview chapter describing purpose of sub-function
        - add interface.yaml with input/output description
        - if category=white set output value by enum with one value or min=max for int
      - Add entries in processing section of interface.yaml
        - Reference ("from [/create-result-cc/result-cc/...]") at input
      - Identify source of value in variable.yaml ("from {$p1ComputePhysicalLag.output#/...}")
      until all required attributes are covered
  end note



  loop for all AirInterfaces in resultCC

  ' ----- Reduce Data --------------------------
    note over cur #LightGray
      Liste der timeXStatesList in PM Daten durchgehen
        IF time==0 THEN
          - Eintrag löschen
        ELSE
          - Name notieren
      
      Alle TxModes aus Capability durchgehen
        IF Name not in notierteNamen THEN
          - Eintrag löschen
    end note

  ' ----- OutOfRange TxLevel --------------------------
  note over cur #LightGray
    Delete TxLevel and RxLevel attributes
    with values outside of pre-defined
    range from PM data
  end note

  cur -> outOfRange: {_resultCC}
  activate outOfRange #LightBlue
  cur <-- outOfRange
  deactivate outOfRange

    ' ----- Link ID --------------------------
    note over cur #LightCyan
      Derive LinkId from LinkEndpointId
    end note

    cur -> substrLinkId : {}
    activate substrLinkId #LightCyan
    cur <-- substrLinkId : {}
    deactivate substrLinkId

    ' ----- Aggregation Group --------------------------
    note over cur #White
      Derive aggregation grouping
      from hierarchy of LTPs
    end note

    cur -> computePhyLag : {}
    activate computePhyLag #LightCyan
    cur <-- computePhyLag : {}
    deactivate computePhyLag

    ' ----- AirInterface KPIs --------------------------
    note over cur #White
      Add AirInterfaceCapacity
    end note

    cur -> airIfKpis: {_rawCC}
    activate airIfKpis #LightBlue
    cur <-- airIfKpis: {computed AirInterface KPIs}
    deactivate airIfKpis

  end

  loop for all EthernetContainers in resultCC

    ' ----- EthContainer KPIs --------------------------
    note over cur #White
      Add EthernetContainer KPIs
    end note
    
    cur -> ethKpis: {_rawCC}
    activate ethKpis #LightBlue
    cur <-- ethKpis: {computed EthernetContainer KPIs}
    deactivate ethKpis

  end

  ' ----- Temperature --------------------------
  note over cur #White
    Derive IDU temperature by
    device type specific method
  end note

  cur -> defaultValues: {_resultCC}
  activate defaultValues #LightBlue
  cur <-- defaultValues
  deactivate defaultValues

  ' ----- ONF default values --------------------------
  note over cur #LightGray
    Delete attributes with ONF
    default values
  end note

  cur -> defaultValues: {_resultCC}
  activate defaultValues #LightBlue
  cur <-- defaultValues
  deactivate defaultValues

requestor <-- cur: {{resultCC}}

deactivate cur

