openapi: 3.0.0
info:
  title: p2FormattingOutputOnf
  version: 1.0.0

x-javascript-interface:
  p2FormattingOutputOnf:
    summary: 'Creates a filtered onfOutputFormat'
    input:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - parameters
              - result-cc
            properties:
              parameters:
                type: object
                description: 'Hierarchical object holding the parameter settings'
              result-cc:
                type: object
                description: >
                  'resultCc'
    output:
      success:
        description: 'onfOutputFormats created'
        content:
          application/json:
            schema:
              type: object
              required:
                - onf-output-format
              properties:
                onf-output-format:
                  type: array
                  description: >
                    'List of onfOutputFormats
                    from [/formatting-output-onf/onf-output-format]'
      error:
        description: 'onfOutputFormats could not be created'
        content:
          application/json:
            schema:
              type: string
                - 'parameters not provided'
                - 'parameters invalid'
                - 'resultCc not provided'
                - 'resultCc invalid'
                - 'onfOutputFormats could not be provided'
                - 'general processing error'
    processing:
      p1FieldsFilter:
        input:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - data-structure
                  - fields-filter-string
                properties:
                  data-structure:
                    type: object
                    description: >
                      'The data structure to be filtered according to the provided fields filter string.
                      from [/formatting-output-onf/result-cc]'
                  fields-filter-string:
                    type: string
                    description: >
                      'Fields filter string following NETCONF FieldsFilter syntax and semantics to be applied to the data structure,
                      from [/formatting-output-onf/fields-filter[i]/fields-filter-string]'
        output:
          success:
            description: 'Data structure successfully filtered according to the provided fields filter string'
            content:
              application/json:
                schema:
                  type: object
                properties:
                  filtered-data-structure:
                    type: object
                    description: 'The data structure after filtering according to the provided fields filter string'
          error:
            description: 'Data structure could not be filtered according to the provided fields filter string'
            content:
              application/json:
                schema:
                  type: string

paths:
  /:
    description: 'no rest path provided by this module'
