@startuml p1CalculateAiCapacity
skinparam responseMessageBelowArrow true

title
  p1CalculateAiCapacity
end title

participant "requestor\n" as requestor
participant "p1CalculateAiCapacity\n" as aiCC

requestor -> aiCC : { channelBandwidth,\nsymbolRateReductionFactor,\nnumberOfStatesInModulation,\ncodeRate }
activate aiCC

  note over aiCC
    Calculates AirInterfaceCapacity
    according to ONF TR-532 v2.0 Chapter 6.5
  end note

requestor <-- aiCC : { airInterfaceCapacity }
deactivate aiCC

@enduml
