@startuml p1FormattingOutputApt
skinparam responseMessageBelowArrow true

title
  p1FormattingOutputApt
end title

participant "requestor\n(e.g. p1ProcessDevice)" as requestor
participant "p1FormattingOutputApt" as cur #LightCyan

requestor -> cur: {{resultCC}}
activate cur #LightCyan

  note over cur
    Transform resultCC data into
    aptOutputFormat.
  end note

requestor <-- cur: {{output}}
deactivate cur
