@startuml 00x_RegardAttributeValueChangeNotification
skinparam responseMessageBelowArrow true

title
NotifiedAttributeValueChangeCausesReadingOfDeviceTypeFromMwdi
NotifiedAttributeValueChangeCausesCallingP1ProcessingOrchestrator
NotifiedAttributeValueChangeCausesUpdatingProcessorControllerDataStore
NotifiedAttributeValueChangeCausesProvisioningToKafka
end title

participant "new AVC notification" as notif #LightCyan
participant "DPMDP://v1/regard-attribute-value-change" as dpmdp
participant "MWDI://v1/provide-device-status-metadata" as devType
participant "DPMDP://p1/processingOrchestrator" as po #LightBlue
participant "DPMDP\n[/processor-controller/data-store]" as dataStore
participant "Kafka\n(topic=provisioned_historical_pm_data)" as kafka

note over notif
  AttributeValueChangeNotification can be either 
   - received via REST/Webhook (subscription to MWDI)
   - or pulled from Kafka
end note

== Notification receipt and processing by p1ProcessingOrchestrator ==

note over dpmdp
  If notification received via Kafka,
  execute /v1/regard-attribute-value-change
  as internal javascript code
end note
notif -> dpmdp: {notification}
activate dpmdp

note over dpmdp
<u>GetDeviceType</u>
  First read the deviceType from MWDI
  (input for [/data-structure-for-processing/device-type])
end note
dpmdp -> devType: {(mountName)}
devType -> dpmdp: {deviceType}

note over po
<u>ExecP1ProcessingOrchestrator</u>
  Execute internal function
  p1ProcessingOrchestrator
  to process the notification, 
  if the notification was relevant,
  a Dsfp object is returned
  (204 otherwise)
end note
dpmdp -> po: {notification, deviceType}
po -> dpmdp: 200, {[/data-structure-for-processing]}

note over dpmdp #LightSalmon
  If p1ProcessingOrchestrator did
  not return 200,
  Terminate
end note

== Updating [/processor-controller/data-store] ==


note over dpmdp
<u>CreateOrUpdateDataStore</u>
IF p1ProcessingOrchestrator returned
a 200 (Dsfp object), add it to the
DataStore, if no associated DataStore
item exists yet, create it
end note
dpmdp -> dataStore: {[/data-structure-for-processing]}

note over dataStore
<u>UpdateDataStore</u>
  WITH <i>targetDsItem</i> = null

  IF NOT EXISTS ([/data-store/device]
    WHERE x-key == [/data-structure-for-processing/mount-name])
    THEN 
      create new [data-store/device] item
      with x-key = [/data-structure-for-processing/mount-name]
      <i>targetDsItem</i> = this new item
  ELSE
    <i>targetDsItem</i> = the [/data-store/device], 
    where x-key == [/data-structure-for-processing/mount-name]

  Add [/data-structure-for-processing] to
  <i>targetDsItem</i>
end note

== Provisioning of new data to Kafka ==
dpmdp -> kafka: {[/data-structure-for-processing]}

deactivate dpmdp

@enduml