@startuml 00b_CyclicOperationBasedDataStoreCleanup
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCausesCyclicOperationBasedDataStoreCleanup
end title

participant "RO" as ro
participant "DPMDP://v1/embed-yourself" as dpmdp
participant "DPMDP\n[/processor-orchestrator/data-store]" as ds

ro -> dpmdp
activate dpmdp

'general info
note over dpmdp
<b>Cyclic operation starts</b>
 cleanup expired items from
 dataStore, time interval
 configured in integerProfile
 <i>dataStoreCleanupPeriod</i>
end note

'read the dataStore
note over dpmdp
  Read the dataStore items:
  - for each [data-store/device/lot] item,
    where new-value expired:
    delete the item from the lot
  - if no lots remain for a [data-store/device]
    item: delete also the device item

  new-values are expired, when they are older
  than configured in
  <i>dataStoreRetentionPeriod</i>
end note
dpmdp -> ds: delete expired items

deactivate dpmdp

@enduml