@startuml 09x_BequeathYourDataAndDie
skinparam responseMessageBelowArrow true

title
  PromptForBequeathingDataCausesUnsubscribingFromAvcNotificationsAtMwdi
end title

participant "NR://v1/embed-yourself" as NewRelease
participant "OR://v1/bequeath-your-data-and-die" as OldRelease
participant "KafkaMessageBroker: \n<i>AttributeValueChangeNotifications</i> topic" as kafka
participant "NP://v1/end-subscription" as mwdi

NewRelease -> OldRelease
activate OldRelease

note over OldRelease
Terminate existing subscriptions 
of discontinued release at Kafka,
with topic-name: <i>mwdi_avc_notifications</i>
end note
OldRelease -> kafka: {own application info, topic-name=<i>mwdi_avc_notifications</i>}

note over OldRelease
Terminate any existing subscription
of AVC notifications 
of discontinued release at MWDI
end note
OldRelease -> mwdi: {own application info}

deactivate OldRelease

@enduml