@startuml hl_sequence_service_changes
skinparam responseMessageBelowArrow true

title
  New Services
end title

participant "embedYourself\n" as embed
participant "provideDevice\nDataStoreDump" as deviceDump #LightSalmon
participant "documentPmData\nProcessing" as docuPm #LightSalmon
participant "initiatePm\nDataUpdate" as initPmData #LightSalmon
participant "p2Stream\nPmData" as p2StreamPm #LightYellow
participant "p1LoadParameters\n" as p1LoadParams
participant "p1Resolve\nEsAddress" as p1ResolveAddress
participant "p1InitKafka\n" as p1InitKafka
participant "p1Update\nMwdiReplica" as p1UpdateMwdiRep

participant "p2Process\nDevice" as p2ProcessPm #LightYellow

participant "p1LoadOffsets\nAndStatusData" as p1LoadStatus #LightSalmon
participant "p2LoadRawCc\n" as p2AddRaw #LightYellow
participant "p1FieldsFilter\n" as p1FieldsFilter
participant "p2DiscardIrrelevant\nPmRecords" as p2filterPm #LightYellow
participant "p1CalculateInterface\nPmDataQuality" as calPmQual #LightSalmon

participant "p2Create\nResultCc" as p2CreateResultCc #LightYellow
participant "p2Prepare\nTxModes" as p1prepTxModes #LightYellow
participant "p1Calculate\nAiCapacity" as aiCC
participant "p2IterateAi\nPmSlices" as aiSlices #LightYellow
participant "p1Calculate\nIntervalCapacity" as intCC
participant "p1RemoveOutOf\nRangeLevels" as p1RORL
participant "p1Remove\nDefaultValues" as p1RemDefault
participant "p2IterateEc\nPmSlices" as ecSlices #LightYellow
participant "p1Calculate\nEthernetKpis" as p1EthKpi
participant "p2Calculate\nUtilization" as p2Util #LightYellow
participant "p1Categorize\nDataVolume" as p1CatDV #LightSalmon
participant "p1CalculateBusyHour\nPerformanceIndicators" as p1CalcBH #LightSalmon
participant "p1RemoveOutOf\nRangeTemperature" as p1ROoRT

participant "p1Formatting\nOutputApt" as p1OutputApt
participant "p2Formatting\nOutputOnf" as p1OutputOnf #LightYellow

participant "p1Transmitting\nKafka" as p1Trans

participant "p2Storing\n" as p2Store #LightYellow
participant "p1MaintainDs\n" as p1MaintainDs
participant "p1ReadData\nStoreDeviceData" as p1ReadDevice #LightSalmon
participant "p1Document\nFunction" as p1Doc #LightSalmon

' Release Notes

== Changes for DeviceDump Service ==

note over deviceDump
  - Load ES address
  - Retrieve data 
    from DataStore
end note

note over p1ReadDevice
  - Read device data
end note

== Changes for ProcessingDocumentation Service ==

note over docuPm
  - Load parameters
  - Create documentation
end note

note over p1Doc
  - Create documentation
    from parameters
end note

== Changes for On-demand PmData Service ==

note over initPmData
  - Address live paths at MWDI
end note

== End of Changes ==


-> deviceDump
activate deviceDump

  deviceDump -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters
      from configFile
    end note
  deviceDump <-- p1LoadParams
  deactivate p1LoadParams

    deviceDump -> p1ResolveAddress
    activate p1ResolveAddress
      note over p1ResolveAddress
        Resolves ES address
      end note
    deviceDump <-- p1ResolveAddress
    deactivate p1ResolveAddress

    deviceDump -> p1ReadDevice
    activate p1ReadDevice
      note over p1ReadDevice
        Reads device PM
        data from DataStore
      end note
    deviceDump <-- p1ReadDevice
    deactivate p1ReadDevice

<-- deviceDump
deactivate deviceDump


-> docuPm
activate docuPm

  docuPm -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads own parameters
      from configFile
    end note
  docuPm <-- p1LoadParams
  deactivate p1LoadParams

  docuPm -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters of PM
      data processing function
      from configFile
    end note
  docuPm <-- p1LoadParams
  deactivate p1LoadParams

  docuPm -> p1Doc
  activate p1Doc
    note over p1Doc
      Creates documentation
      from {parameters}
    end note
  docuPm <-- p1Doc
  deactivate p1Doc

<-- docuPm
deactivate docuPm


-> initPmData
activate initPmData

  initPmData -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters
      from configFile
    end note
  initPmData <-- p1LoadParams
  deactivate p1LoadParams

  loop
    note over initPmData
      Triggers liveCC
      path at MWDI
    end note
  end loop
<-- initPmData
deactivate initPmData


@enduml
