@startuml hl_sequence
skinparam responseMessageBelowArrow true

title
  DevicePerformanceManagementDataProcessor
end title

participant "embedYourself\n" as embed
participant "p1StreamPmData\n" as p1StreamPm
participant "p1LoadParameters\n" as p1LoadParams
participant "p1ResolveEsAddress\n" as p1ResolveAddress
participant "p1InitKafka\n" as p1InitKafka
participant "p1UpdateMwdiReplica\n" as p1UpdateMwdiRep

participant "p2ProcessDevice\n" as p2ProcessPm #LightYellow

participant "p1LoadOffsets\nAndStatusData" as p1LoadStatus #LightSalmon
participant "p2LoadRawCc\n" as p2AddRaw #LightYellow
participant "p1FieldsFilter\n" as p1FieldsFilter
participant "p2DiscardIrrelevant\nPmRecords" as p2filterPm #LightYellow

participant "p2CreateResultCc\n" as p2CreateResultCc #LightYellow
participant "p1Prepare\nTxModes" as p1prepTxModes 
participant "p1Calculate\nAiCapacity" as aiCC
participant "p2IterateAi\nPmSlices" as aiSlices #LightYellow
participant "p1Calculate\nIntervalCapacity" as intCC
participant "p1RemoveOutOf\nRangeLevels" as p1RORL
participant "p1Remove\nDefaultValues" as p1RemDefault
participant "p2IterateEc\nPmSlices" as ecSlices #LightYellow
participant "p1Calculate\nEthernetKpis" as p1EthKpi
participant "p1Calculate\nUtilization" as p1Util
participant "p1Categorize\nDataVolume" as p1CatDV #LightSalmon
participant "p1CalculateBusyHour\nPerformanceIndicators" as p1CalcBH #LightSalmon
participant "p1RemoveOutOf\nRangeTemperature" as p1ROoRT

participant "p1Formatting\nOutputApt" as p1OutputApt
participant "p1Formatting\nOutputOnf" as p1OutputOnf

participant "p1Transmitting\nKafka" as p1Trans

participant "p2Storing\n" as p2Store #LightYellow
participant "p1MaintainDs\n" as p1MaintainDs

note right embed
  Automatically starts
  p1StreamPmData
end note
embed -> p1StreamPm

' Release Notes
===== Changes for preventing mostRecentPeriodEndTimes poison pills  =====

note over p2ProcessPm
  - Add interface to p1LoadOffsetsAndStatusData
  - Complement interface to p2LoadRawCc by:
    - offsets
  - Complement interface from p2LoadRawCc by:
    - offsets
  - Complement interface to p2Storing by:
    - offsets
end note

note over p1LoadStatus
  - Load offsets about:
    - which PM values have already been processed in past
      (mostRecentPeriodEndTime and mostRecentPeriodEndTime24)
end note

note over p2AddRaw
  - Complement own input interface by:
    - offsets
  - Remove from own input interface:
    - dataStoreEsClient (mostRecentPeriodEndTimes 
      have been loaded in p1LoadOffsetsAndStatusData)
  - Remove loading mostRecentPeriodEndTimes from DataStore
  - Complement interface to p2DiscardIrrelevantPmRecords by:
    - offset (mostRecentPeriodEndTimes only)
  - Complement interface from p2DiscardIrrelevantPmRecords by:
    - offset (mostRecentPeriodEndTimes only)
  - Wrap updated offset into offsets
  - Complement own output interface by:
    - offsets
end note

note over p2filterPm
  - Complement own input interface by:
    - offset (mostRecentPeriodEndTimes only)
  - Update mostRecentPeriodEndTimes in offset
  - Complement own output interface by:
    - offset (mostRecentPeriodEndTimes only)
end note

note over p2CreateResultCc
  - Remove from interface to p2IterateAiPmSlices:
    - most-recent-period-end-time
    - most-recent-period-end-time-24
  - Remove from interface to p2IterateEcPmSlices:
    - 
end note

note over aiSlices
  - Remove from own input interface
    - most-recent-period-end-time
    - most-recent-period-end-time-24
  - Remove update of mostRecentPeriodEndTimes
end note

note over ecSlices
  - Remove from own input interface
    - most-recent-period-end-time
    - most-recent-period-end-time-24
  - Remove update of mostRecentPeriodEndTimes
end note

note over p2Store
  - store offsets about:
    which PM values have already been processed
end note

===== Changes for adding BH KPIs =====

note over p2ProcessPm
  - Add interface to p1LoadOffsetsAndStatusData
  - Complement interface to p2CreateResultCc by:
    - statusData
  - Complement interface from p2CreateResultCc by:
    - statusData
  - Complement interface to p2Storing by:
    - statusData
end note

note over p1LoadStatus
  - Load statusData about:
    - total-bytes-output in 15-min records in already processed batches
end note

note over p2AddRaw
  - Remove deleting 15-min or 24-hours granularity
end note

note over p2CreateResultCc
  - Complement interface to p2IterateEcPmSlices by:
    - statusData
end note

note over ecSlices
  - Complement own input interface by:
    - statusData
  - Add interface to p1CategorizeDataVolume
  - Add interface to p1CalculateBusyHourPerformanceIndicators
end note

note over p1CatDV
  - Reads from statusData:
    - buckets (representing hours of the day) with:
      - total-bytes-output values from already processed 15-min periods
      - further 15-min values
  - In case of new day:
    - creates 24 new buckets
    - deletes 24 oldest buckets
  - Categorizes new total-bytes-output values into the buckets
  - Writes buckets back into statusData
end note

note over p1CalcBH
  - Reads from statusData:
    - buckets with total-bytes-output values
  - Bucket with highest sum of total-bytes-output values defines busy hour
  - Calculates KPIs for busy hour
  - Writes busy hour KPIs into 24-hours values
end note

note over p2Store
  - Complement own input interface by:
    - statusData
  - Writes statusData about:
    - total-bytes-output in processed 15-min records
end note

== End of Changes ==

activate p1StreamPm

  ' Load parameters
  p1StreamPm -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters
      from configFile
    end note
  p1StreamPm <-- p1LoadParams
  deactivate p1LoadParams

  ' Resolve ES address
  Loop FOR all esName
    p1StreamPm -> p1ResolveAddress
    activate p1ResolveAddress
      note over p1ResolveAddress
        Resolves ES address
      end note
    p1StreamPm <-- p1ResolveAddress
    deactivate p1ResolveAddress

  end Loop

  ' Init Kafka
  p1StreamPm -> p1InitKafka
  activate p1InitKafka

    note over p1InitKafka
      Resolves Kafka
      address
    end note

    note over p1InitKafka
      Establishes Kafka
      session
    end note

  p1StreamPm <-- p1InitKafka
  deactivate p1InitKafka

  ' Maintain DataStore
  p1StreamPm -> p1MaintainDs
  activate p1MaintainDs

  Loop endless
    note over p1MaintainDs
      Deletes old
      resultCc
    end note
  end loop

  Loop endless

    ' Update MWDI replica
    p1StreamPm -> p1UpdateMwdiRep
    activate p1UpdateMwdiRep
      note over p1UpdateMwdiRep
        Replicates updated CCs
      end note
    p1StreamPm <-- p1UpdateMwdiRep
    deactivate p1UpdateMwdiRep

    Loop for every updated CC

      ' ProcessDevice
      p1StreamPm -> p2ProcessPm
      activate p2ProcessPm


        ' Load offsets and statusData
        p2ProcessPm -> p1LoadStatus
        activate p1LoadStatus

          note over p1LoadStatus
            Loads offsets and status data
            from DataStore
          end note

        p2ProcessPm <-- p1LoadStatus
        deactivate p1LoadStatus

        ' Load RawCC
        p2ProcessPm -> p2AddRaw
        activate p2AddRaw

          note over p2AddRaw
            Loads raw data to rawCc
          end note

          ' Apply fieldsFilter
          p2AddRaw -> p1FieldsFilter
          activate p1FieldsFilter

            note over p1FieldsFilter
              Reduces structure of rawCc
            end note

          p2AddRaw <-- p1FieldsFilter
          deactivate p1FieldsFilter

          ' DiscardIrrelvantPmRecords
          p2AddRaw -> p2filterPm
          activate p2filterPm

            note over p2filterPm
              Deletes PM data that has
              already been processed in past
            end note

          p2AddRaw <-- p2filterPm
          deactivate p2filterPm

          note over p2AddRaw
            addBatchTimestamp
          end note

          note over p2AddRaw
            update offset
          end note

        p2ProcessPm <-- p2AddRaw : {rawCc}
        deactivate p2AddRaw

        ' Create resultCC
        p2ProcessPm -> p2CreateResultCc
        activate p2CreateResultCc

          note over p2CreateResultCc
            Copies rawCc to resultCc
          end note

          note over p2CreateResultCc
            Creates aggregationGroupList
          end note

          ' AirInterfaces
          loop FOR all AirInterfaces in resultCc

            ' prepTxModes
            p2CreateResultCc -> p1prepTxModes
            activate p1prepTxModes

              note over p1prepTxModes
                Prepares TxModes
              end note

              p1prepTxModes -> aiCC
              activate aiCC

                note over aiCC
                  Calculates
                  AirInterfaceCapacity
                end note

              p1prepTxModes <-- aiCC
              deactivate aiCC

            p2CreateResultCc <-- p1prepTxModes
            deactivate p1prepTxModes

            ' iterateAiPmSlices
            p2CreateResultCc -> aiSlices
            activate aiSlices

                ' capacityCalculation
                aiSlices -> intCC
                activate intCC

                  note over intCC
                    Calculates
                    IntervalCapacity
                  end note

                aiSlices <-- intCC
                deactivate intCC

                ' RemoveOutOfRangeLevelValues
                aiSlices -> p1RORL
                activate p1RORL

                  note over p1RORL
                    Deletes RxLevel and TxLevel
                    attributes with values
                    outside pre-defined range
                  end note

                aiSlices <-- p1RORL
                deactivate p1RORL

                ' RemoveOnfDefaultValues
                aiSlices -> p1RemDefault
                activate p1RemDefault

                  note over p1RemDefault
                    Deletes attributes with
                    ONF default value
                  end note

                aiSlices <-- p1RemDefault
                deactivate p1RemDefault

            p2CreateResultCc <-- aiSlices
            deactivate aiSlices

            note over p2CreateResultCc
              Add linkId
            end note

            note over p2CreateResultCc
              Add list of parallel LTPs
            end note

          end loop


          ' EthernetContainers
          loop FOR all EthernetContainers in resultCc

            ' IterateEcPmSlices
            p2CreateResultCc -> ecSlices
            activate ecSlices

              'EthernetKPIs
              ecSlices -> p1EthKpi
              activate p1EthKpi

                note over p1EthKpi
                  Add Ethernet KPIs
                end note

              ecSlices <-- p1EthKpi
              deactivate p1EthKpi

              ' RemoveOnfDefaultValues
              ecSlices -> p1RemDefault
              activate p1RemDefault

                note over p1RemDefault
                  Deletes default values
                  from Ec Pm data
                end note

              ecSlices <-- p1RemDefault
              deactivate p1RemDefault

              ' Utilization
              ecSlices -> p1Util
              activate p1Util

                note over p1Util
                  Add utilization
                end note

              ecSlices <-- p1Util
              deactivate p1Util

              ' categorizeDataVolume
              ecSlices -> p1CatDV
              activate p1CatDV

                note over p1CatDV
                  Categorize total-bytes-output values
                end note

              ecSlices <- p1CatDV
              deactivate p1CatDV

              ' calculateBH
              ecSlices -> p1CalcBH
              activate p1CalcBH

                note over p1CalcBH
                  Calculate busy hour KPIs
                end note

              ecSlices <- p1CalcBH
              deactivate p1CalcBH


            p2CreateResultCc <-- ecSlices
            deactivate ecSlices

            note over p2CreateResultCc
              Update statusData
            end note

          end loop

        ' RemoveOutOfRangeTemperatureValues
          p2CreateResultCc -> p1ROoRT
          activate p1ROoRT

            note over p1ROoRT
              Delete temperature attributes with
              values outside pre-defined range
            end note

          p2CreateResultCc <-- p1ROoRT
          deactivate p1ROoRT

        p2ProcessPm <-- p2CreateResultCc : {resultCc}
        deactivate p2CreateResultCc

        ' OutputApt
        p2ProcessPm -> p1OutputApt
        activate p1OutputApt

          note over p1OutputApt
            Create APT format
          end note

        p2ProcessPm <-- p1OutputApt : {aptOutputFormat}
        deactivate p1OutputApt

        ' OutputOnf
        p2ProcessPm -> p1OutputOnf
        activate p1OutputOnf

          note over p1OutputOnf
            Create ONF format
          end note

          p1OutputOnf -> p1FieldsFilter
          activate p1FieldsFilter

            note over p1FieldsFilter
              Reduces structure of
              ONF output format
            end note

          p1OutputOnf <-- p1FieldsFilter
          deactivate p1FieldsFilter

        p2ProcessPm <-- p1OutputOnf : {onfOutputFormat}
        deactivate p1OutputOnf

        ' KafkaTransmission
        p2ProcessPm -> p1Trans
        activate p1Trans

          note over p1Trans
            Transmit object to
            KafkaProducerService
          end note

        p2ProcessPm <-- p1Trans
        deactivate p1Trans

        ' Storing
        p2ProcessPm -> p2Store
        activate p2Store

          note over p2Store
            Store resultCc, offsets and
            status data to DataStore
          end note

        p2ProcessPm <-- p2Store
        deactivate p2Store

      deactivate p2ProcessPm

    end Loop

  end Loop

@enduml
