@startuml hl_sequence_bh-changes
skinparam responseMessageBelowArrow true

title
  Busy Hour Changes
end title

participant "embedYourself\n" as embed
participant "p2StreamPmData\n" as p2StreamPm #LightYellow
participant "p1LoadParameters\n" as p1LoadParams
participant "p1ResolveEsAddress\n" as p1ResolveAddress
participant "p1InitKafka\n" as p1InitKafka
participant "p1UpdateMwdiReplica\n" as p1UpdateMwdiRep

participant "p2ProcessDevice\n" as p2ProcessPm #LightYellow

participant "p1LoadOffsets\nAndStatusData" as p1LoadStatus #LightSalmon
participant "p2LoadRawCc\n" as p2AddRaw #LightYellow
participant "p1FieldsFilter\n" as p1FieldsFilter
participant "p2DiscardIrrelevant\nPmRecords" as p2filterPm #LightYellow

participant "p2CreateResultCc\n" as p2CreateResultCc #LightYellow
participant "p1Prepare\nTxModes" as p1prepTxModes
participant "p1Calculate\nAiCapacity" as aiCC
participant "p2IterateAi\nPmSlices" as aiSlices #LightYellow
participant "p1Calculate\nIntervalCapacity" as intCC
participant "p1RemoveOutOf\nRangeLevels" as p1RORL
participant "p1Remove\nDefaultValues" as p1RemDefault
participant "p2IterateEc\nPmSlices" as ecSlices #LightYellow
participant "p1Calculate\nEthernetKpis" as p1EthKpi
participant "p1Calculate\nUtilization" as p1Util
participant "p1Categorize\nDataVolume" as p1CatDV #LightSalmon
participant "p1CalculateBusyHour\nPerformanceIndicators" as p1CalcBH #LightSalmon
participant "p1RemoveOutOf\nRangeTemperature" as p1ROoRT

participant "p1Formatting\nOutputApt" as p1OutputApt
participant "p1Formatting\nOutputOnf" as p1OutputOnf

participant "p1Transmitting\nKafka" as p1Trans

participant "p2Storing\n" as p2Store #LightYellow
participant "p1MaintainDs\n" as p1MaintainDs

== Changes for adding BH KPIs ==

note over p2ProcessPm
  - Add interface to p1LoadOffsetsAndStatusData
  - Complement interface to p2CreateResultCc by:
    - statusData
  - Complement interface from p2CreateResultCc by:
    - statusData
  - Complement interface to p2Storing by:
    - statusData
end note

note over p1LoadStatus
  - retrieveStatusDataFromDs for functions:
    - p1CategorizeDataVolume
      (total-bytes-output of already processed batches in buckets)
end note

note over p2AddRaw
  - Remove from interface to p2DiscardIrrelevantPmRecords:
    - relevant-granularities
end note

note over p2filterPm
  - Remove from own input interface:
    -  relevant-granularities
  - Remove deleting of 15-min or 24-hours granularity
end note

note over p2CreateResultCc
  - Complement own input interface by:
    - statusData
  - Complement interface to p2IterateEcPmSlices by:
    - interfaceStatus
  - Complement interface from p2IterateEcPmSlices by:
    - interfaceStatus
  - Complement own output interface by:
    - statusData
end note

note over ecSlices
  - Complement own input interface by:
    - interfaceStatus
  - Add interface to p1CategorizeDataVolume
  - Add interface to p1CalculateBusyHourPerformanceIndicators
  - Complement own output interface by:
    - interfaceStatus
end note

note over p1CatDV
  - Read from statusData:
    - buckets (representing hours of the day) with:
      - total-bytes-output values from already processed 15-min periods
      - further 15-min values
  - In case of new day:
    - create 24 new buckets
    - delete 24 oldest buckets
  - Categorize new total-bytes-output values into the buckets
  - Write buckets back into statusData
end note

note over p1CalcBH
  - Read from statusData:
    - buckets with total-bytes-output values
  - Calculate sum of total-bytes-output values for each bucket
  - Highest sum of total-bytes-output values defines busy hour
  - Calculate KPIs for busy hour
  - Write busy hour KPIs into 24-hours values
end note

note over p2Store
  - Complement own input interface by:
    - statusData
  - storeStatusData
end note

@enduml
