@startuml hl_sequence
skinparam responseMessageBelowArrow true

title
  DevicePerformanceManagementDataProcessor
end title

participant "embedYourself\n" as embed
participant "p1StreamPmData\n" as p1RMWDI #LightBlue
participant "p1LoadParameters\n" as p1LoadParams #LightBlue
participant "p1ResolveEsAddress\n" as p1REA #LightBlue
participant "p1InitKafka\n" as p1InitKafka #LightBlue
participant "p1UpdateMwdiReplica\n" as p1UMR #LightBlue

participant "p1ProcessDevice\n" as p1ProcessPm #LightBlue

participant "p1LoadRawCc\n" as p1AddRaw #LightCyan
participant "p1FieldsFilter\n" as p1FieldsFilter #LightBlue
participant "p1DiscardIrrelevant\nPmRecords" as filterPm #LightBlue

participant "p1CreateResultCc\n" as p1CreateResultCc #LightCyan
participant "p1Prepare\nTxModes" as p1prepTxModes #BurlyWood
participant "p2Prepare\nTxModes" as p2prepTxModes #LightCyan
participant "p1Calculate\nAiCapacity" as aiCC #LightBlue
participant "p1Calculate\nIntervalCapacity" as intCC #LightBlue
participant "p1IterateAi\nPmSlices" as aiSlices #LightCyan
participant "p1RemoveOutOf\nRangeLevels" as p1RORL #LightCyan
participant "p1Remove\nDefaultValues" as p1RemDefault #LightCyan
participant "p1Calculate\nEthernetKpis" as p1EthKpi #BurlyWood
participant "p1IterateEc\nPmSlices" as ecSlices #LightCyan
participant "p2Calculate\nEthernetKpis" as p2EthKpi #LightCyan
participant "p1RemoveOutOf\nRangeTemperature" as p1ROoRT #LightCyan

participant "p1Formatting\nOutputApt" as p1Output #LightCyan

participant "p1Transmitting\nKafka" as p1Trans #LightBlue

participant "p1Storing\n" as p1Store #Yellow
participant "p1MaintainDs\n" as p1MDS #Yellow

participant "kafkaProducer\nService" as kafkaProd #LightBlue

note right embed
  Automatically start
  p1StreamPmData
end note
embed -> p1RMWDI

' replicate MWDI ES ->
activate p1RMWDI #LightBlue

  p1RMWDI -> p1LoadParams
  activate p1LoadParams #LightBlue
    note over p1LoadParams
      Load parameters
      from configFile
    end note
  p1RMWDI <-- p1LoadParams
  deactivate p1LoadParams

  Loop FOR all esName
    p1RMWDI -> p1REA
    activate p1REA #LightBlue
      note over p1REA
        Resolve ES address
      end note
    p1RMWDI <-- p1REA
    deactivate p1REA

  end Loop

  p1RMWDI -> p1InitKafka
  activate p1InitKafka #LightBlue

    note over p1InitKafka
      Resolve Kafka
      address
    end note

    p1InitKafka -> kafkaProd
    activate kafkaProd #LightBlue
      note over kafkaProd
        Establish session
      end note
    p1InitKafka <-- kafkaProd

  p1RMWDI <-- p1InitKafka
  deactivate p1InitKafka

  p1RMWDI -> p1MDS
  activate p1MDS #Yellow
    note over p1MDS
      Maintain DataStore
    end note

  Loop endless

    p1RMWDI -> p1UMR
    activate p1UMR #LightBlue
      note over p1UMR
        Replicate updated CCs
      end note
    p1RMWDI <-- p1UMR
    deactivate p1UMR

    Loop for every updated CC

      p1RMWDI -> p1ProcessPm
      activate p1ProcessPm #LightBlue

        note over p1ProcessPm
          Create data structure
          for processing
        end note

        ' create RawCC ->
        p1ProcessPm -> p1AddRaw
        activate p1AddRaw #LightCyan

          note over p1AddRaw
            Load raw data to rawCc
          end note

          ' apply fieldsFilter ->
          p1AddRaw -> p1FieldsFilter
          activate p1FieldsFilter #LightBlue

            note over p1FieldsFilter
              Reduce structure of rawCc
            end note

          p1AddRaw <-- p1FieldsFilter
          deactivate p1FieldsFilter

          note over p1AddRaw
            Get mostRecentPeriodEndTimes
          end note

          ' discard irrelevant PM records
          p1AddRaw -> filterPm
          activate filterPm #LightBlue

            note over filterPm
              Delete PM data that has
              already been processed in past
            end note

          p1AddRaw <-- filterPm
          deactivate filterPm

          note over p1AddRaw
            addBatchTimestamp
          end note

        p1ProcessPm <-- p1AddRaw
        deactivate p1AddRaw

        note over p1ProcessPm
          Add rawCc to data structure
          for processing
        end note

        ' create resultCc ->
        p1ProcessPm -> p1CreateResultCc
        activate p1CreateResultCc #LightCyan

          note over p1CreateResultCc
            Copies rawCc to resultCc
          end note

          note over p1CreateResultCc
            Creates aggregationGroupList
          end note

          loop FOR all AirInterfaces in resultCc

            p1CreateResultCc -> p1prepTxModes
            activate p1prepTxModes #BurlyWood

              note over p1prepTxModes
                Prepare TxModes
              end note

              p1prepTxModes -> aiCC
              activate aiCC #LightBlue

                note over aiCC
                  Calculate
                  AirInterfaceCapacity
                end note

              p1prepTxModes <-- aiCC
              deactivate aiCC

              p1prepTxModes -> intCC
              activate intCC #LightBlue

                note over intCC
                  Calculate
                  IntervalCapacity
                end note

              p1prepTxModes <-- intCC
              deactivate intCC

            p1CreateResultCc <-- p1prepTxModes
            deactivate p1prepTxModes

            p1CreateResultCc -> p2prepTxModes
            activate p2prepTxModes #LightCyan

              note over p2prepTxModes
                Prepare TxModes
              end note

              p2prepTxModes -> aiCC
              activate aiCC #LightBlue

                note over aiCC
                  Calculate
                  AirInterfaceCapacity
                end note

              p2prepTxModes <-- aiCC
              deactivate aiCC

            p1CreateResultCc <-- p2prepTxModes
            deactivate p2prepTxModes

            p1CreateResultCc -> aiSlices
            activate aiSlices #LightCyan

                aiSlices -> intCC
                activate intCC #LightBlue

                  note over intCC
                    Calculate
                    IntervalCapacity
                  end note

                aiSlices <-- intCC
                deactivate intCC

                aiSlices -> p1RORL
                activate p1RORL #LightCyan

                  note over p1RORL
                    Delete RxLevel and TxLevel
                    attributes with values
                    outside pre-defined range
                  end note

                aiSlices <-- p1RORL
                deactivate p1RORL        

                aiSlices -> p1RemDefault
                activate p1RemDefault #LightCyan

                  note over p1RemDefault
                    Delete attributes with
                    ONF default value
                  end note

                aiSlices <-- p1RemDefault
                deactivate p1RemDefault        

            p1CreateResultCc <-- aiSlices
            deactivate aiSlices

            note over p1CreateResultCc
              Add linkId
            end note

            note over p1CreateResultCc
              Add list of parallel LTPs
            end note

            note over p1CreateResultCc
              Add mostRecentPeriodEndTime
              (AirInterface)
            end note

            note over p1CreateResultCc
              Add mostRecentPeriodEndTime24
              (AirInterface)
            end note

          end loop

          loop FOR all EthernetContainers in resultCc

            p1CreateResultCc -> p1EthKpi
            activate p1EthKpi #BurlyWood

              note over p1EthKpi
                Add Ethernet KPIs
                to resultCc
              end note

            p1CreateResultCc <-- p1EthKpi
            deactivate p1EthKpi

            p1CreateResultCc -> ecSlices
            activate ecSlices #LightCyan

              ecSlices -> p2EthKpi
              activate p2EthKpi #LightCyan

                note over p2EthKpi
                  Add Ethernet KPIs to
                  historicalPerformanceData
                end note

              ecSlices <-- p2EthKpi
              deactivate p2EthKpi

              ecSlices -> p1RemDefault
              activate p1RemDefault #LightCyan

                note over p1RemDefault
                  Delete attributes with
                  ONF default value
                end note

              ecSlices <-- p1RemDefault
              deactivate p1RemDefault        

            p1CreateResultCc <-- ecSlices
            deactivate ecSlices

            note over p1CreateResultCc
              Add mostRecentPeriodEndTime
              (EthernetContainer)
            end note

            note over p1CreateResultCc
              Add mostRecentPeriodEndTime24
              (EthernetContainer)
            end note

          end loop

          p1CreateResultCc -> p1ROoRT
          activate p1ROoRT #LightCyan

            note over p1ROoRT
              Delete temperature attributes with
              values outside pre-defined range
            end note

          p1CreateResultCc <-- p1ROoRT
          deactivate p1ROoRT

        p1ProcessPm <-- p1CreateResultCc
        deactivate p1CreateResultCc

        note over p1ProcessPm
          Add resultCc to data 
          structure for processing
        end note

        ' Format OutputAPT ->
        p1ProcessPm -> p1Output
        activate p1Output #LightCyan

          note over p1Output
            Create APT format
          end note

        p1ProcessPm <-- p1Output
        deactivate p1Output

        note over p1ProcessPm
          Add APT format to data
          structure for processing
        end note

        ' transmit data ->
        p1ProcessPm -> p1Trans
        activate p1Trans #LightBlue

          note over p1Trans
            Transmit object
            to Kafka
          end note
          p1Trans -> kafkaProd
            note over kafkaProd
              Send message
            end note
          p1Trans <-- kafkaProd

        p1ProcessPm <-- p1Trans
        deactivate p1Trans

        ' storing ->
        p1ProcessPm -> p1Store
        activate p1Store #Yellow

          note over p1Store
            Store resultCc
            to DataStore
          end note

        p1ProcessPm <-- p1Store
        deactivate p1Store

      deactivate p1ProcessPm

    end Loop

  end Loop

@enduml
