@startuml hl_workflow
skinparam responseMessageBelowArrow true

title
  DevicePerformanceManagementDataProcessor
  (v1.0.x)
end title

participant "Test\nDesign\n0" as testDesign #PapayaWhip
participant "Kafka\nDesign\n0" as kafkaDesign #PapayaWhip
participant "DPMDP\nBody\n0" as body #PapayaWhip

participant "iVeritas\nDesign\n0" as iVeritas #LightCyan
participant "NEP\n1.2.0\n0" as nep #LightCyan

participant "embedYourself\n\n1" as embed #PapayaWhip
participant "p1StreamPmData\n\n1" as p1StreamPm #PapayaWhip
participant "p1LoadParameters\n\n1" as p1LoadParams #PapayaWhip
participant "p1ResolveEsAddress\n\n2" as p1ResolveAddress #PapayaWhip
participant "p1InitKafka\n\n4" as p1InitKafka #PapayaWhip
participant "p1UpdateMwdiReplica\n\n2" as p1UpdateMwdiRep #PapayaWhip

participant "p1ProcessDevice\n\n3" as p1ProcessPm #PapayaWhip

participant "p1LoadRawCc\n\n3" as p1AddRaw #PapayaWhip
participant "p1FieldsFilter\n\n6" as p1FieldsFilter #PapayaWhip
participant "p1DiscardIrrelevant\nPmRecords\n7" as filterPm #LightCyan

participant "p1CreateResultCc\n\n3" as p1CreateResultCc #PapayaWhip
participant "p1Prepare\nTxModes\n1" as p1prepTxModes #LightCyan
participant "p1Calculate\nAiCapacity\n1" as aiCC #LightCyan
participant "p1IterateAi\nPmSlices\n2" as aiSlices #LightCyan
participant "p1Calculate\nIntervalCapacity\n2" as intCC #LightCyan
participant "p1RemoveOutOf\nRangeLevels\n2" as p1RORL #LightCyan
participant "p1Remove\nDefaultValues\n2" as p1RemDefault #LightCyan
participant "p1IterateEc\nPmSlices\n4" as ecSlices #LightCyan
participant "p1Calculate\nEthernetKpis\n4" as p1EthKpi #LightCyan
participant "p1Calculate\nUtilization\n4" as p1Util #LightCyan
participant "p1RemoveOutOf\nRangeTemperature\n3" as p1ROoRT #LightCyan

participant "p1Formatting\nOutputApt\n5" as p1OutputApt #LightCyan
participant "p1Formatting\nOutputOnf\n6" as p1OutputOnf #LightCyan

participant "p1Transmitting\nKafka\n4" as p1Trans #PapayaWhip

participant "p1Storing\n\n5" as p1Store #PapayaWhip
participant "p1MaintainDs\n\n5" as p1MaintainDs #PapayaWhip

participant "CDM\n1.0.0\n7" as cdm #PapayaWhip

note right embed
  Automatically starts
  p1StreamPmData
end note
embed -> p1StreamPm

activate p1StreamPm

  p1StreamPm -> p1LoadParams
  activate p1LoadParams
    note over p1LoadParams
      Loads parameters
      from configFile
    end note
  p1StreamPm <-- p1LoadParams
  deactivate p1LoadParams

  Loop FOR all esName
    p1StreamPm -> p1ResolveAddress
    activate p1ResolveAddress
      note over p1ResolveAddress
        Resolves ES address
      end note
    p1StreamPm <-- p1ResolveAddress
    deactivate p1ResolveAddress

  end Loop

  p1StreamPm -> p1InitKafka
  activate p1InitKafka

    note over p1InitKafka
      Resolves Kafka
      address
    end note

    note over p1InitKafka
      Establishes Kafka
      session
    end note

  p1StreamPm <-- p1InitKafka
  deactivate p1InitKafka

  p1StreamPm -> p1MaintainDs
  activate p1MaintainDs

  Loop endless
    note over p1MaintainDs
      Deletes old
      resultCc
    end note
  end loop

  Loop endless

    p1StreamPm -> p1UpdateMwdiRep
    activate p1UpdateMwdiRep
      note over p1UpdateMwdiRep
        Replicates updated CCs
      end note
    p1StreamPm <-- p1UpdateMwdiRep
    deactivate p1UpdateMwdiRep

    Loop for every updated CC

      p1StreamPm -> p1ProcessPm
      activate p1ProcessPm

        p1ProcessPm -> p1AddRaw
        activate p1AddRaw

          note over p1AddRaw
            Loads raw data to rawCc
          end note

          p1AddRaw -> p1FieldsFilter
          activate p1FieldsFilter

            note over p1FieldsFilter
              Reduces structure of rawCc
            end note

          p1AddRaw <-- p1FieldsFilter
          deactivate p1FieldsFilter

          note over p1AddRaw
            Get mostRecentPeriodEndTimes
          end note

          p1AddRaw -> filterPm
          activate filterPm

            note over filterPm
              Deletes PM data that has
              already been processed in past
            end note

          p1AddRaw <-- filterPm
          deactivate filterPm

          note over p1AddRaw
            addBatchTimestamp
          end note

        p1ProcessPm <-- p1AddRaw : {rawCc}
        deactivate p1AddRaw

        p1ProcessPm -> p1CreateResultCc
        activate p1CreateResultCc

          note over p1CreateResultCc
            Copies rawCc to resultCc
          end note

          note over p1CreateResultCc
            Creates aggregationGroupList
          end note

          loop FOR all AirInterfaces in resultCc

            p1CreateResultCc -> p1prepTxModes
            activate p1prepTxModes

              note over p1prepTxModes
                Prepares TxModes
              end note

              p1prepTxModes -> aiCC
              activate aiCC

                note over aiCC
                  Calculates
                  AirInterfaceCapacity
                end note

              p1prepTxModes <-- aiCC
              deactivate aiCC

            p1CreateResultCc <-- p1prepTxModes
            deactivate p1prepTxModes

            p1CreateResultCc -> aiSlices
            activate aiSlices

                aiSlices -> intCC
                activate intCC

                  note over intCC
                    Calculates
                    IntervalCapacity
                  end note

                aiSlices <-- intCC
                deactivate intCC

                aiSlices -> p1RORL
                activate p1RORL

                  note over p1RORL
                    Deletes RxLevel and TxLevel
                    attributes with values
                    outside pre-defined range
                  end note

                aiSlices <-- p1RORL
                deactivate p1RORL

                aiSlices -> p1RemDefault
                activate p1RemDefault

                  note over p1RemDefault
                    Deletes attributes with
                    ONF default value
                  end note

                aiSlices <-- p1RemDefault
                deactivate p1RemDefault

                note over aiSlices
                  Derives most recent
                  periodEndTime
                end note

            p1CreateResultCc <-- aiSlices
            deactivate aiSlices

            note over p1CreateResultCc
              Update interfaceMetadata
            end note

            note over p1CreateResultCc
              Add linkId
            end note

            note over p1CreateResultCc
              Add list of parallel LTPs
            end note

          end loop

          loop FOR all EthernetContainers in resultCc

            p1CreateResultCc -> ecSlices
            activate ecSlices

              ecSlices -> p1EthKpi
              activate p1EthKpi

                note over p1EthKpi
                  Add Ethernet KPIs
                end note

              ecSlices <-- p1EthKpi
              deactivate p1EthKpi

              ecSlices -> p1RemDefault
              activate p1RemDefault

                note over p1RemDefault
                  Deletes default values
                  from Ec Pm data
                end note

              ecSlices <-- p1RemDefault
              deactivate p1RemDefault

              ecSlices -> p1Util
              activate p1Util

                note over p1Util
                  Add utilization
                end note

              ecSlices <-- p1Util
              deactivate p1Util

              note over ecSlices
                Derives most recent
                periodEndTime
              end note

            p1CreateResultCc <-- ecSlices
            deactivate ecSlices

            note over p1CreateResultCc
              Update interfaceMetadata
            end note

          end loop

          p1CreateResultCc -> p1ROoRT
          activate p1ROoRT

            note over p1ROoRT
              Delete temperature attributes with
              values outside pre-defined range
            end note

          p1CreateResultCc <-- p1ROoRT
          deactivate p1ROoRT

        p1ProcessPm <-- p1CreateResultCc : {resultCc}
        deactivate p1CreateResultCc

        p1ProcessPm -> p1OutputApt
        activate p1OutputApt

          note over p1OutputApt
            Create APT format
          end note

        p1ProcessPm <-- p1OutputApt : {aptOutputFormat}
        deactivate p1OutputApt

        p1ProcessPm -> p1OutputOnf
        activate p1OutputOnf

          note over p1OutputOnf
            Create ONF format
          end note

          p1OutputOnf -> p1FieldsFilter
          activate p1FieldsFilter

            note over p1FieldsFilter
              Reduces structure of
              ONF output format
            end note

          p1OutputOnf <-- p1FieldsFilter
          deactivate p1FieldsFilter

        p1ProcessPm <-- p1OutputOnf : {onfOutputFormat}
        deactivate p1OutputOnf

        p1ProcessPm -> p1Trans
        activate p1Trans

          note over p1Trans
            Transmit object to
            KafkaProducerService
          end note

        p1ProcessPm <-- p1Trans
        deactivate p1Trans

        p1ProcessPm -> p1Store
        activate p1Store

          note over p1Store
            Store resultCc
            to DataStore
          end note

        p1ProcessPm <-- p1Store
        deactivate p1Store

      deactivate p1ProcessPm

    end Loop

  end Loop

@enduml
