@startuml p1Inquire15minAirInterfaceKpisFromCaca
skinparam responseMessageBelowArrow true

title
p1Inquire15minAirInterfaceKpisFromCaca
end title

participant "requestor" as requestor
participant "p1Inquire15minAirInterfaceKpisFromCaca" as setKpi #LightBlue
participant "CaCa://v1/compute-air-interface-capacity-kpis-for-list-of-air-interfaces" as caca

activate setKpi
requestor -> setKpi: {todo: list airIf attributes/classes}

note over setKpi #LightCoral
 tb decided: shall DPDMP compute KPIs by itself
 or will new app be created for that?
end note

setKpi -> caca: {todo: copy list of parameters here}
setKpi <-- caca: {computed AirIf KPIs}

setKpi <-- requestor: {computed AirIf KPIs}

deactivate setKpi
