@startuml p1RemoveOutOfRangeTemperature
skinparam responseMessageBelowArrow true

title
  p1RemoveOutOfRangeTemperature
end title

participant "p2CreateResultCc\n" as requestor
participant "p1RemoveOutOfRange\nTemperature" as removeTemp


  requestor -> removeTemp : { parameters,\n[equipment] }
  activate removeTemp

    loop FOR [equipment]

      note over removeTemp
        IF value of temperature outside [lowerTemperatureLimit, upperTemperatureLimit]
          THEN delete {physicalProperties} incl. temperature attribute
      end note

    end loop

  requestor <-- removeTemp: { [equipment] }
  deactivate removeTemp

@enduml
